const duocLieuData1 = [
    // --- NHÓM THANH NHIỆT (Tả hỏa, Lợi thấp, Giải độc, Lương huyết) ---
    { nhom: "Thanh nhiệt", ten: "Sinh địa (Địa hoàng)", cong_dung: "Thanh nhiệt lương huyết, dưỡng âm sinh tân dịch.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Hoàng liên", cong_dung: "Thanh nhiệt táo thấp, tả hỏa giải độc.", kieng_ky: "Âm hư, thiếu máu." },
    { nhom: "Thanh nhiệt", ten: "Kim ngân hoa (Nhẫn đông hoa)", cong_dung: "Thanh nhiệt giải độc biểu, trị mụn nhọt.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Liên kiều", cong_dung: "Thanh nhiệt giải độc, tiêu thũng tán kết.", kieng_ky: "Tỳ hư tiết tả." },
    { nhom: "Thanh nhiệt", ten: "Bồ công anh (Diếp dại)", cong_dung: "Thanh nhiệt giải độc, tiêu viêm.", kieng_ky: "Tỳ vị hư nhược." },
    { nhom: "Thanh nhiệt", ten: "Hoàng cầm", cong_dung: "Thanh nhiệt táo thấp, tả hỏa, an thai.", kieng_ky: "Phế hàn ho đờm." },
    { nhom: "Thanh nhiệt", ten: "Hoàng bá", cong_dung: "Thanh nhiệt táo thấp, tả hỏa hạ tiêu.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Thạch cao", cong_dung: "Thanh nhiệt tả hỏa cực mạnh, trừ phiền.", kieng_ky: "Chứng dương hư, hàn chứng." },
    { nhom: "Thanh nhiệt", ten: "Đăng tâm", cong_dung: "Thanh tâm hỏa, lợi tiểu.", kieng_ky: "Tiểu tiện không tự chủ." },
    { nhom: "Thanh nhiệt", ten: "Đạm trúc diệp", cong_dung: "Thanh tâm hỏa, trừ phiền, lợi tiểu.", kieng_ky: "Thể hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Bạch mao căn (Rễ cỏ tranh)", cong_dung: "Lương huyết, chỉ huyết, lợi niệu thanh nhiệt.", kieng_ky: "Chứng hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Đan bì", cong_dung: "Thanh nhiệt, lương huyết, hoạt huyết.", kieng_ky: "Thai phụ, kinh nguyệt nhiều." },
    { nhom: "Thanh nhiệt", ten: "Mộc thông", cong_dung: "Thanh nhiệt lợi tiểu, thông kinh hạ sữa.", kieng_ky: "Phụ nữ mang thai, tinh hoạt, tỳ hư." },
    { nhom: "Thanh nhiệt", ten: "Trúc diệp", cong_dung: "Thanh nhiệt trừ phiền, sinh tân lợi niệu.", kieng_ky: "Người tỳ vị hư hàn, tiểu nhiều." },
    { nhom: "Thanh nhiệt", ten: "Nhân trần", cong_dung: "Thanh nhiệt lợi thấp, thoái hoàng trị vàng da.", kieng_ky: "Người không có thấp nhiệt, tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cù mạch", cong_dung: "Thanh nhiệt lợi thủy thông lâm, phá huyết thông kinh.", kieng_ky: "Phụ nữ mang thai, người tỳ vị hư nhược." },
    { nhom: "Thanh nhiệt", ten: "Biển súc", cong_dung: "Lợi niệu thông lâm, sát trùng chỉ ngứa.", kieng_ky: "Người thể trạng suy nhược, đi tiểu nhiều do khí hư." },
    { nhom: "Thanh nhiệt", ten: "Tri mẫu", cong_dung: "Thanh nhiệt tả hỏa, tư âm nhuận táo.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy lỏng." },
    { nhom: "Thanh nhiệt", ten: "Rau má", cong_dung: "Thanh nhiệt lợi thấp, giải độc, trị mụn nhọt, rôm sảy, hạ sốt.", kieng_ky: "Người tỳ vị hư hàn, đang bị đại tiện lỏng." },
    { nhom: "Thanh nhiệt", ten: "Mướp đắng (Khổ qua)", cong_dung: "Thanh nhiệt giải thử, minh mục giải độc, trị sốt, mụn nhọt.", kieng_ky: "Người tỳ vị hư hàn, phụ nữ có thai không dùng nhiều." },
    { nhom: "Thanh nhiệt", ten: "Rau ngót", cong_dung: "Thanh nhiệt giải độc, hoạt huyết hóa ứ, trị tưa lưỡi, sót nhau.", kieng_ky: "Phụ nữ có thai (nguy cơ gây co thắt tử cung)." },
    { nhom: "Thanh nhiệt", ten: "Bí đao (Đông qua)", cong_dung: "Thanh nhiệt giải thử, sinh tân chỉ khát, lợi thủy tiêu thũng.", kieng_ky: "Người tỳ vị hư hàn, đầy bụng đi lỏng." },
    { nhom: "Thanh nhiệt", ten: "Dưa hấu", cong_dung: "Thanh nhiệt giải thử, trừ phiền chỉ khát, lợi tiểu, trị sốt cao.", kieng_ky: "Người tỳ vị hư hàn, tiểu tiện quá nhiều." },
    { nhom: "Thanh nhiệt", ten: "Cà chua", cong_dung: "Thanh nhiệt sinh tân, kiện tỳ tiêu thực, trị khát nước, sốt cao.", kieng_ky: "Người tỳ vị hư hàn, dạ dày nhiều acid." },
    { nhom: "Thanh nhiệt", ten: "Rau sam", cong_dung: "Thanh nhiệt giải độc, lương huyết trị kiết lỵ, mụn nhọt, giun kim.", kieng_ky: "Người tỳ vị hư hàn, phụ nữ có thai." },
    { nhom: "Thanh nhiệt", ten: "Khế chua", cong_dung: "Thanh nhiệt giải độc, lợi tiểu, trị ho, dị ứng mẩn ngứa, mụn nhọt.", kieng_ky: "Người bị bệnh thận, sỏi thận (chứa nhiều acid oxalic)." },
    { nhom: "Thanh nhiệt", ten: "Chi tử (Dành dành)", cong_dung: "Thanh nhiệt trừ phiền, tả hỏa lợi thấp, lương huyết giải độc.", kieng_ky: "Người tỳ vị hư hàn, đại tiện lỏng." },
    { nhom: "Thanh nhiệt", ten: "Hạ khô thảo", cong_dung: "Thanh nhiệt, tả hỏa, tán kết, làm sáng mắt, hạ huyết áp.", kieng_ky: "Người tỳ vị hư hàn, không có nhiệt tà." },
    { nhom: "Thanh nhiệt", ten: "Thảo quyết minh (Hạt muồng)", cong_dung: "Thanh nhiệt, mát gan, sáng mắt, nhuận tràng, hạ huyết áp.", kieng_ky: "Người tỳ vị hư hàn, đại tiện lỏng." },
    { nhom: "Thanh nhiệt", ten: "Atiso", cong_dung: "Mát gan, lợi mật, thanh nhiệt, giải độc, hạ cholesterol.", kieng_ky: "Người bị tắc ống dẫn mật, tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cỏ ngọt (Stevia)", cong_dung: "Thanh nhiệt, lợi tiểu, điều vị thay đường, hỗ trợ hạ đường huyết.", kieng_ky: "Người huyết áp thấp, phụ nữ có thai dùng liều lượng vừa phải." },
    { nhom: "Thanh nhiệt", ten: "Quả la hán", cong_dung: "Thanh nhiệt, nhuận phế, lợi hầu, nhuận tràng.", kieng_ky: "Người tỳ vị hư hàn, hay đi lỏng." },
    { nhom: "Thanh nhiệt", ten: "Hoa hồng", cong_dung: "Hành khí, giải uất, hòa huyết, thanh nhiệt.", kieng_ky: "Người tỳ vị hư hàn, đại tiện lỏng." },
    { nhom: "Thanh nhiệt", ten: "Mía lau", cong_dung: "Thanh nhiệt, sinh tân, chỉ khát, lợi tiểu.", kieng_ky: "Người tỳ vị hư hàn, bụng đầy trướng." },
    { nhom: "Thanh nhiệt", ten: "Lô căn (Rễ sậy)", cong_dung: "Thanh nhiệt sinh tân, trừ phiền chỉ nôn, lợi niệu.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Thiên hoa phấn", cong_dung: "Thanh nhiệt sinh tân, tiêu thũng bài nùng.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Thanh nhiệt", ten: "Bạch đầu ông", cong_dung: "Thanh nhiệt giải độc, lương huyết trị lỵ.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy thuần hàn." },
    { nhom: "Thanh nhiệt", ten: "Tần bì", cong_dung: "Thanh nhiệt táo thấp, thu liễm chỉ lỵ, minh mục.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Xạ can (Rẻ quạt)", cong_dung: "Thanh nhiệt giải độc, tiêu thũng, hóa đàm lợi yết.", kieng_ky: "Phụ nữ có thai, tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Thanh hao", cong_dung: "Thanh hư nhiệt, tiệt ngược, lương huyết thấu biểu.", kieng_ky: "Ngoại cảm phong hàn, tỳ vị hư hàn tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Địa cốt bì", cong_dung: "Lương huyết, thanh phế giáng hỏa, lui chưng cốt triệt nhiệt.", kieng_ky: "Ngoại cảm phong hàn, tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Xuyên tâm liên", cong_dung: "Thanh nhiệt giải độc, táo thấp tiêu thũng.", kieng_ky: "Tỳ vị hư hàn, không dùng kéo dài." },
    { nhom: "Thanh nhiệt", ten: "Sâm đại hành", cong_dung: "Thanh nhiệt lương huyết, tiêu độc, sinh tân, chỉ huyết.", kieng_ky: "Âm hư hỏa vượng không có nhiệt độc." },
    { nhom: "Thanh nhiệt", ten: "Cây xương khỉ (Bìm bịp)", cong_dung: "Thanh nhiệt giải độc, tiêu thũng, hoạt huyết tán ứ, liền cốt.", kieng_ky: "Tỳ vị hư hàn, thể hàn." },
    { nhom: "Thanh nhiệt", ten: "Sơn đậu căn", cong_dung: "Thanh nhiệt giải độc, tiêu thũng lợi yết hầu.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Bản lam căn", cong_dung: "Thanh nhiệt giải độc, lương huyết lợi yết hầu.", kieng_ky: "Tỳ vị hư hàn, không có nhiệt độc." },
    { nhom: "Thanh nhiệt", ten: "Khổ sâm", cong_dung: "Thanh nhiệt táo thấp, sát trùng, trị ngứa da, kiết lỵ.", kieng_ky: "Tỳ vị hư hàn, huyết hư." },
    { nhom: "Thanh nhiệt", ten: "Bạch tiễn bì", cong_dung: "Thanh nhiệt táo thấp, khu phong chỉ ngứa, giải độc.", kieng_ky: "Huyết hư phong táo." },
    { nhom: "Thanh nhiệt", ten: "Thổ phục linh", cong_dung: "Tiêu viêm giải độc, trừ thấp lợi khớp, trị mẩn ngứa, giải độc thủy ngân.", kieng_ky: "Can thận âm hư, tỳ vị quá yếu." },
    { nhom: "Thanh nhiệt", ten: "Diệp hạ châu (Chó đẻ răng cưa)", cong_dung: "Thanh nhiệt giải độc, mát gan, thoái hoàng, lợi tiểu.", kieng_ky: "Người tỳ vị hư hàn, phụ nữ có thai." },
    { nhom: "Thanh nhiệt", ten: "Sài đất", cong_dung: "Thanh nhiệt giải độc, tiêu viêm, trị mụn nhọt, rôm sảy, viêm họng.", kieng_ky: "Người thể trạng hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cà gai leo", cong_dung: "Thanh nhiệt giải độc gan, tiêu viêm, tán phong thấp, trừ ho.", kieng_ky: "Phụ nữ mang thai giai đoạn đầu." },
    { nhom: "Thanh nhiệt", ten: "Giảo cổ lam", cong_dung: "Thanh nhiệt kiện tỳ, ích khí, hạ mỡ máu, tăng cường miễn dịch.", kieng_ky: "Phụ nữ có thai, người huyết áp quá thấp." },
    { nhom: "Thanh nhiệt", ten: "Xạ đen", cong_dung: "Thanh nhiệt giải độc, hoạt huyết tiêu sưng, hỗ trợ kháng u.", kieng_ky: "Phụ nữ có thai, người suy thận nặng." },

    // --- NHÓM BỔ KHÍ (Ích khí, Kiện tỳ) ---
    { nhom: "Bổ khí", ten: "Nhân sâm", cong_dung: "Đại bổ nguyên khí, bổ tỳ ích phế, sinh tân an thần.", kieng_ky: "Huyết áp cao, thực nhiệt, đau bụng thể hàn." },
    { nhom: "Bổ khí", ten: "Đẳng sâm", cong_dung: "Ích khí kiện tỳ vị, bổ phế, dưỡng huyết.", kieng_ky: "Thực tà ngoại cảm." },
    { nhom: "Bổ khí", ten: "Hoàng kỳ", cong_dung: "Bổ khí thăng dương, cố biểu chỉ hãn, lợi niệu tiêu thũng.", kieng_ky: "Thực tà nhiệt thịnh, âm hư hỏa vượng." },
    { nhom: "Bổ khí", ten: "Bạch truật", cong_dung: "Kiện tỳ ích khí, táo thấp lợi thủy, an thai.", kieng_ky: "Âm hư hỏa vượng, tân dịch khô." },
    { nhom: "Bổ khí", ten: "Hoài sơn (Sơn dược)", cong_dung: "Ích khí dưỡng âm, bổ tỳ phế thận, cố tinh chỉ đới.", kieng_ky: "Thực tà tích trệ, thấp nhiệt." },
    { nhom: "Bổ khí", ten: "Đại táo (Táo tàu)", cong_dung: "Bổ trung ích khí, dưỡng huyết an thần, hòa hoãn dược tính.", kieng_ky: "Đàm thịnh, bụng trướng, sâu răng." },
    { nhom: "Bổ khí", ten: "Bố chính sâm", cong_dung: "Bổ khí kiện tỳ, dưỡng âm nhuận phế.", kieng_ky: "Ngoại cảm phong hàn." },
    { nhom: "Bổ khí", ten: "Gạo tẻ (Ngạnh mễ)", cong_dung: "Ích khí kiện tỳ, hòa vị chỉ khát.", kieng_ky: "Đàm thấp tích trệ." },
    { nhom: "Bổ khí", ten: "Đinh lăng", cong_dung: "Bổ khí, thông huyết mạch, bồi bổ cơ thể, tăng sinh lực, giảm mệt mỏi.", kieng_ky: "Dùng quá liều gây tiêu chảy, nôn mửa." },
    { nhom: "Bổ khí", ten: "Đậu xanh (Lục đậu)", cong_dung: "Thanh nhiệt giải độc, tiêu thử lợi thủy, bổ khí kiện tỳ.", kieng_ky: "Người tỳ vị hư hàn, đang uống thuốc đông y (làm giảm tác dụng)." },
    { nhom: "Bổ khí", ten: "Cam thảo (Bao gồm Chích cam thảo)", cong_dung: "Thanh nhiệt giải độc, nhuận phế chỉ khái, bổ tỳ ích khí, điều hòa các vị thuốc.", kieng_ky: "Tỳ vị thấp thịnh, bụng trướng đầy, phù thũng, tăng huyết áp không dùng liều cao kéo dài." },
    { nhom: "Bổ khí", ten: "Khiếm thực", cong_dung: "Ích thận cố tinh, kiện tỳ chỉ tả, trừ thấp.", kieng_ky: "Đại tiện táo kết, tiểu tiện dắt." },
    { nhom: "Bổ khí", ten: "Thỏ ty tử", cong_dung: "Bổ thận cố tinh, dưỡng can minh mục, an thai, kiện tỳ.", kieng_ky: "Âm hư hỏa vượng, táo bón." },
    { nhom: "Bổ khí", ten: "Tây dương sâm", cong_dung: "Ích khí dưỡng âm, thanh hỏa sinh tân.", kieng_ky: "Dương hư, tỳ vị hư hàn." },
    { nhom: "Bổ khí", ten: "Hoàng tinh", cong_dung: "Bổ khí dưỡng âm, kiện tỳ nhuận phế ích thận.", kieng_ky: "Tỳ vị hư hàn đàm thấp, tiêu chảy." },
    { nhom: "Bổ khí", ten: "Sâm dây Ngọc Linh", cong_dung: "Đại bổ nguyên khí, kiện tỳ ích phế, tăng sinh lực.", kieng_ky: "Người thực tà ngoại cảm, sốt cao uất nhiệt." },

    // --- NHÓM BỔ HUYẾT (Dưỡng huyết, Tư âm) ---
    { nhom: "Bổ huyết", ten: "Thục địa (Địa hoàng chế)", cong_dung: "Tư âm dưỡng huyết, bổ thận tráng tinh, làm đen râu tóc.", kieng_ky: "Tỳ vị hư nhược, đàm thấp, tiêu chảy." },
    { nhom: "Bổ huyết", ten: "Đương quy", cong_dung: "Bổ huyết hoạt huyết, điều kinh chỉ thống, nhuận tràng.", kieng_ky: "Tiêu chảy, kinh nguyệt ra quá nhiều." },
    { nhom: "Bổ huyết", ten: "Bạch thược", cong_dung: "Dưỡng huyết liễm âm, bình can chỉ thống, dãn cơ.", kieng_ky: "Dương hư hạ liệt, tiêu chảy do lạnh." },
    { nhom: "Bổ huyết", ten: "Hà thủ ô đỏ (Chế)", cong_dung: "Bổ can thận, ích tinh huyết, làm đen râu tóc, dưỡng tâm an thần.", kieng_ky: "Tỳ hư đàm thấp, tiêu chảy." },
    { nhom: "Bổ huyết", ten: "Mạch môn (Mạch đông)", cong_dung: "Dưỡng âm sinh tân, nhuận phế thanh tâm.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Bổ huyết", ten: "Thiên môn", cong_dung: "Tư âm nhuận táo, thanh phế giáng hỏa.", kieng_ky: "Tỳ vị hư hàn, ho do phong hàn." },
    { nhom: "Bổ huyết", ten: "Long nhãn", cong_dung: "Bổ tâm tỳ, dưỡng huyết an thần.", kieng_ky: "Đầy trướng bụng, đàm ẩm, thực nhiệt." },
    { nhom: "Bổ huyết", ten: "Thạch hộc", cong_dung: "Tư âm thanh nhiệt, bổ thận sinh tân, dưỡng vị.", kieng_ky: "Thể trầm hàn, thực tà chưa giải." },
    { nhom: "Bổ huyết", ten: "Bách hợp", cong_dung: "Nhuận phế chỉ khái, thanh tâm an thần.", kieng_ky: "Tiêu chảy do tỳ hư, ho do phong hàn." },
    { nhom: "Bổ huyết", ten: "Ngọc trúc", cong_dung: "Dưỡng âm nhuận táo, sinh tân chỉ khát.", kieng_ky: "Tỳ hư đàm thấp, tiêu chảy." },
    { nhom: "Bổ huyết", ten: "Huyền sâm", cong_dung: "Tư âm giáng hỏa, thanh nhiệt lương huyết, giải độc tán kết.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy, kỵ Lệ lô." },
    { nhom: "Bổ huyết", ten: "Sa sâm", cong_dung: "Dưỡng âm thanh phế, ích vị sinh tân.", kieng_ky: "Ho do phong hàn, tỳ vị hư hàn." },
    { nhom: "Bổ huyết", ten: "Ngũ vị tử", cong_dung: "Thu liễm phế khí, tư thận ninh tâm, sáp tràng chỉ tả, sinh tân.", kieng_ky: "Ngoại cảm tà khí chưa tan, sốt cao ho mới phát." },
    { nhom: "Bổ huyết", ten: "Sơn thù (Sơn thù nhục)", cong_dung: "Bổ ích can thận, thu liễm cố sáp, viễn niệu.", kieng_ky: "Mệnh môn hỏa vượng, tiểu buốt dắt." },
    { nhom: "Bổ huyết", ten: "Kỷ tử (Câu kỷ tử)", cong_dung: "Bổ can thận, sáng mắt, nhuận phế.", kieng_ky: "Tỳ hư tiết tả, đang sốt cảm mạo." },
    { nhom: "Bổ huyết", ten: "A giao", cong_dung: "Bổ huyết chỉ huyết, tư âm nhuận phế.", kieng_ky: "Tỳ vị hư hàn, ăn không tiêu, đầy bụng." },
    { nhom: "Bổ huyết", ten: "Quả dâu tằm (Tang thầm)", cong_dung: "Bổ huyết trừ phong, dưỡng âm sinh tân, làm đen tóc, trị ù tai.", kieng_ky: "Người tiêu chảy do tỳ vị hư hàn." },

    // --- NHÓM HOẠT HUYẾT (Hóa ứ, Thông kinh) ---
    { nhom: "Hoạt huyết", ten: "Đào nhân", cong_dung: "Hoạt huyết khứ ứ, nhuận tràng thông tiện.", kieng_ky: "Phụ nữ có thai, người không có ứ trệ." },
    { nhom: "Hoạt huyết", ten: "Hồng hoa", cong_dung: "Hoạt huyết thông kinh, tán ứ chỉ thống.", kieng_ky: "Phụ nữ có thai, rong kinh." },
    { nhom: "Hoạt huyết", ten: "Đan sâm", cong_dung: "Hoạt huyết hóa ứ, dưỡng tâm an thần, lương huyết.", kieng_ky: "Phụ nữ có thai, không dùng chung với Lê lô." },
    { nhom: "Hoạt huyết", ten: "Xuyên khung", cong_dung: "Hoạt huyết hành khí, khu phong chỉ thống.", kieng_ky: "Âm hư hỏa vượng, chảy máu cấp." },
    { nhom: "Hoạt huyết", ten: "Ngưu tất", cong_dung: "Hoạt huyết thông kinh, bổ can thận, cường gân cốt, dẫn huyết hạ hành.", kieng_ky: "Phụ nữ có thai, băng lậu." },
    { nhom: "Hoạt huyết", ten: "Ích mẫu", cong_dung: "Hoạt huyết điều kinh, khử ứ sinh tân, lợi thủy tiêu thũng.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Tam thất", cong_dung: "Hóa ứ chỉ huyết, tiêu thũng chỉ thống, bổ huyết.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Uất kim (Củ xả nghệ)", cong_dung: "Hoạt huyết, hành khí, thanh tâm, lợi mật thoái hoàng.", kieng_ky: "Phụ nữ có thai, âm hư không khí trệ." },
    { nhom: "Hoạt huyết", ten: "Kê huyết đằng", cong_dung: "Hành huyết bổ huyết, thư cân thông lạc.", kieng_ky: "Thực nhiệt, phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Nghệ vàng (Khương hoàng)", cong_dung: "Hoạt huyết phá ứ, hành khí chỉ thống, trị bế kinh, chấn thương.", kieng_ky: "Phụ nữ có thai, sỏi mật gây tắc mạch." },
    { nhom: "Hoạt huyết", ten: "Xích thược", cong_dung: "Thanh nhiệt lương huyết, tán ứ chỉ thống.", kieng_ky: "Huyết hư không có ứ trệ, tỳ vị hư hàn." },
    { nhom: "Hoạt huyết", ten: "Diên hồ sách", cong_dung: "Hành khí hoạt huyết, chỉ thống chuyên biệt.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Nga truật", cong_dung: "Hành khí phá ứ, tiêu tích chỉ thống.", kieng_ky: "Phụ nữ có thai, tỳ vị hư nhược." },
    { nhom: "Hoạt huyết", ten: "Tam lăng", cong_dung: "Phá huyết hành khí, tiêu tích chỉ thống.", kieng_ky: "Phụ nữ có thai, cơ thể suy nhược." },
    { nhom: "Hoạt huyết", ten: "Tô mộc (Gỗ vang)", cong_dung: "Hoạt huyết thông kinh, khứ ứ chỉ thống, tiêu thũng.", kieng_ky: "Phụ nữ có thai, huyết hư không ứ." },

    // --- NHÓM ÔN TRUNG TÁN HÀN (Khu hàn, Bổ hỏa) ---
    { nhom: "Khu hàn", ten: "Can khương (Gừng khô)", cong_dung: "Ôn trung hồi dương, ấm tỳ vị, chỉ nôn, ôn phế hóa đờm.", kieng_ky: "Âm hư nội nhiệt, xuất huyết do nhiệt." },
    { nhom: "Khu hàn", ten: "Nhục quế (Quế vỏ)", cong_dung: "Bổ mệnh môn hỏa, ôn tỳ vị, tán hàn chỉ thống, thông huyết mạch.", kieng_ky: "Phụ nữ có thai, âm hư hỏa vượng." },
    { nhom: "Khu hàn", ten: "Phụ tử chế", cong_dung: "Hồi dương cứu nghịch, bổ hỏa trợ dương, tán hàn chỉ thống.", kieng_ky: "Phụ nữ có thai, chứng thực nhiệt, âm hư hỏa vượng (chú ý độc tính)." },
    { nhom: "Khu hàn", ten: "Ngô thù du", cong_dung: "Tán hàn chỉ thống, giáng nghịch chỉ nôn, trợ dương chỉ tả.", kieng_ky: "Âm hư nội nhiệt." },
    { nhom: "Khu hàn", ten: "Đinh hương", cong_dung: "Ôn trung giáng nghịch, ấm tỳ vị, tráng dương.", kieng_ky: "Âm hư hỏa vượng, kỵ Uất kim." },
    { nhom: "Khu hàn", ten: "Tiểu hồi hương", cong_dung: "Tán hàn chỉ thống, lý khí hòa vị.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khu hàn", ten: "Sa nhân", cong_dung: "Hóa thấp hành khí, ôn trung chỉ tả, an thai.", kieng_ky: "Âm hư nội nhiệt." },
    { nhom: "Khu hàn", ten: "Sinh khương (Gừng tươi)", cong_dung: "Phát biểu tán hàn, ôn trung chỉ nôn, giải độc.", kieng_ky: "Âm hư nội nhiệt, phế nhiệt ho." },
    { nhom: "Khu hàn", ten: "Cao lương khương (Củ riềng)", cong_dung: "Ôn trung tán hàn, chỉ thống tiêu thực, trị đau dạ dày do lạnh.", kieng_ky: "Nôn mửa hoặc đau dạ dày do hỏa uất nhiệt chứng." },
    { nhom: "Khu hàn", ten: "Nhục đậu khấu", cong_dung: "Ôn trung sáp tràng, hành khí tiêu thực.", kieng_ky: "Tiêu chảy mạn tính do thấp nhiệt, lỵ cấp tính." },
    { nhom: "Khu hàn", ten: "Đại hồi", cong_dung: "Ôn trung tán hàn, lý khí chỉ thống, trị đau bụng co thắt do lạnh.", kieng_ky: "Người âm hư hỏa vượng, các chứng âm hư nội nhiệt." },

    // --- NHÓM GIẢI BIỂU (Phát tán phong hàn / phong nhiệt) ---
    { nhom: "Giải biểu", ten: "Ma hoàng", cong_dung: "Phát hãn giải biểu, bình suyễn, lợi thủy tiêu thũng.", kieng_ky: "Biểu hư tự hãn, âm hư hỏa vượng, tăng huyết áp." },
    { nhom: "Giải biểu", ten: "Quế chi (Cành quế)", cong_dung: "Giải biểu tán hàn, ôn thông kinh mạch, thông dương hóa khí.", kieng_ky: "Phụ nữ có thai, âm hư hỏa vượng, sốt cao." },
    { nhom: "Giải biểu", ten: "Tế tân", cong_dung: "Giải biểu tán hàn, khu phong chỉ thống, thông khiếu, ôn phế hóa đờm.", kieng_ky: "Khí hư tự hãn, âm hư ho khan." },
    { nhom: "Giải biểu", ten: "Thăng ma", cong_dung: "Phát biểu thấu chẩn, thanh nhiệt giải độc, thăng dương cử hãm.", kieng_ky: "Âm hư hỏa vượng, ho suyễn khí nghịch." },
    { nhom: "Giải biểu", ten: "Sài hồ", cong_dung: "Thấu biểu tiết nhiệt, sơ can giải uất, thăng dương cử hãm.", kieng_ky: "Âm hư hỏa vượng, can dương bốc hỏa." },
    { nhom: "Giải biểu", ten: "Tô diệp (Lá tía tô)", cong_dung: "Phát tán phong hàn, lý khí an thai, giải độc cua cá.", kieng_ky: "Biểu hư tự hãn, âm hư phát sốt." },
    { nhom: "Giải biểu", ten: "Kinh giới", cong_dung: "Phát tán phong hàn, thấu chẩn, chỉ huyết (sao đen).", kieng_ky: "Biểu hư tự hãn, mụn nhọt đã vỡ mủ." },
    { nhom: "Giải biểu", ten: "Bạc hà", cong_dung: "Sơ tán phong nhiệt, thấu chẩn, giải độc, thanh lợi đầu mục.", kieng_ky: "Cơ thể suy nhược, ra nhiều mồ hôi, trẻ sơ sinh." },
    { nhom: "Giải biểu", ten: "Phòng phong", cong_dung: "Khu phong giải biểu, thắng thấp chỉ thống, trừ co giật.", kieng_ky: "Huyết hư phát sốt, âm hư đầu thống." },
    { nhom: "Giải biểu", ten: "Cát căn (Sắn dây)", cong_dung: "Giải cơ thoái nhiệt, sinh tân chỉ khát, thấu chẩn, thăng dương chỉ tả.", kieng_ky: "Biểu hư tự hãn, vị hàn." },
    { nhom: "Giải biểu", ten: "Bạch chỉ", cong_dung: "Giải biểu tán hàn, khu phong chỉ thống, thông khiếu, táo thấp.", kieng_ky: "Âm hư hỏa vượng, mụn nhọt đã vỡ." },
    { nhom: "Giải biểu", ten: "Hương nhu", cong_dung: "Phát hãn giải thử, hóa thấp điều trung, lợi thủy tiêu thũng.", kieng_ky: "Biểu hư tự hãn, âm hư hỏa vượng." },
    { nhom: "Giải biểu", ten: "Tân di (Hoa mộc lan)", cong_dung: "Khu phong tán hàn, thông mũi ngạt (chuyên trị viêm mũi xoang).", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Giải biểu", ten: "Thương nhĩ tử (Ké đầu ngựa)", cong_dung: "Khu phong tán hàn, thông khiếu, trừ thấp chỉ ngứa.", kieng_ky: "Huyết hư đầu thống, cấm dùng quả mọc mầm." },
        // --- NHÓM LÝ KHÍ (Hành khí, Tiêu trệ, Sơ can) ---
    { nhom: "Lý khí", ten: "Hương phụ (Cỏ cú)", cong_dung: "Sơ can lý khí, điều kinh chỉ thống, giải uất.", kieng_ky: "Âm hư huyết nhiệt, khí hư không có uất trệ." },
    { nhom: "Lý khí", ten: "Hậu phác", cong_dung: "Hành khí táo thấp, tiêu tích bình suyễn.", kieng_ky: "Phụ nữ có thai, tỳ vị khí hư." },
    { nhom: "Lý khí", ten: "Mộc hương", cong_dung: "Hành khí chỉ thống, kiện tỳ tiêu thực.", kieng_ky: "Âm hư hỏa vượng, tân dịch khô kiệt." },
    { nhom: "Lý khí", ten: "Trần bì (Vỏ quýt)", cong_dung: "Lý khí kiện tỳ, táo thấp hóa đờm, trị đầy bụng, nôn mửa.", kieng_ky: "Ho khan không có đờm, âm hư khô khát." },
    { nhom: "Lý khí", ten: "Chỉ thực", cong_dung: "Phá khí tiêu tích, hóa đờm trừ bĩ.", kieng_ky: "Tỳ vị hư nhược, phụ nữ có thai." },
    { nhom: "Lý khí", ten: "Chỉ xác", cong_dung: "Lý khí khoan hung, hành trệ tiêu tích.", kieng_ky: "Phụ nữ có thai, cơ thể suy nhược." },
    { nhom: "Lý khí", ten: "Thanh bì (Vỏ quýt non)", cong_dung: "Sơ can phá khí, tán kết tiêu tích.", kieng_ky: "Tỳ vị khí hư, phụ nữ có thai." },
    { nhom: "Lý khí", ten: "Ô dược", cong_dung: "Hành khí chỉ thống, ôn thận tán hàn.", kieng_ky: "Khí hư nội nhiệt." },
    { nhom: "Lý khí", ten: "Trầm hương", cong_dung: "Hành khí chỉ thống, ôn trung giáng nghịch, nạp khí bình suyễn.", kieng_ky: "Âm hư hỏa vượng, khí hư hạ hãm." },
    { nhom: "Lý khí", ten: "Quả Phật thủ", cong_dung: "Sơ can lý khí, hòa vị chỉ thống, táo thấp hóa đờm.", kieng_ky: "Âm hư nội nhiệt, không có khí trệ uất kết." },
    { nhom: "Lý khí", ten: "Vỏ bưởi (Nam trầm hương)", cong_dung: "Lý khí hóa đờm, tiêu thực kiện tỳ, trị đầy bụng khó tiêu.", kieng_ky: "Âm hư ho khan, cơ thể suy nhược." },
    { nhom: "Lý khí", ten: "Hạt tiêu", cong_dung: "Ôn trung tán hàn, hạ khí tiêu đàm, trị đau bụng lạnh, nôn mửa.", kieng_ky: "Âm hư hỏa vượng, mụn nhọt, thực nhiệt." },
    { nhom: "Lý khí", ten: "Tỏi", cong_dung: "Hành khí tiêu tích, sát trùng giải độc, trị đầy bụng, ăn không tiêu.", kieng_ky: "Âm hư hỏa vượng, đau mắt đỏ, loét dạ dày nặng." },
    { nhom: "Lý khí", ten: "Hoắc hương", cong_dung: "Táo thấp giải thử, hòa trung ngưng nôn, phát biểu giải cảm.", kieng_ky: "Âm hư hỏa vượng, âm hư ho khan." },
    { nhom: "Lý khí", ten: "Rau ngổ (Ngổ hương)", cong_dung: "Thanh nhiệt giải độc, hành khí chỉ thống, lợi tiểu, trị sỏi thận.", kieng_ky: "Phụ nữ có thai dùng liều cao." },

    // --- NHÓM AN THẦN (Dưỡng tâm, Trấn kinh) ---
    { nhom: "An thần", ten: "Bá tử nhân", cong_dung: "Dưỡng tâm an thần, nhuận tràng thông tiện.", kieng_ky: "Tiêu chảy do tỳ hư, đàm thấp." },
    { nhom: "An thần", ten: "Viễn chí", cong_dung: "Ninh tâm an thần, khư đàm khai khiếu, tiêu ung thũng.", kieng_ky: "Âm hư hỏa vượng, viêm loét dạ dày." },
    { nhom: "An thần", ten: "Toan táo nhân (Táo nhân)", cong_dung: "Dưỡng tâm an thần, liễm hãn sinh tân.", kieng_ky: "Tiêu chảy nặng, thực nhiệt uất hỏa." },
    { nhom: "An thần", ten: "Long cốt", cong_dung: "Trấn kinh an thần, bình can tiềm dương, thu liễm cố sáp.", kieng_ky: "Thấp nhiệt thực tà, sốt cao uất nhiệt." },
    { nhom: "An thần", ten: "Hạt sen (Liên nhục)", cong_dung: "Dưỡng tâm an thần, bổ tỳ ích thận, sáp tràng.", kieng_ky: "Táo bón nặng, đầy trướng bụng." },
    { nhom: "An thần", ten: "Tâm sen (Liên tâm)", cong_dung: "Thanh tâm an thần, hạ huyết áp, trị mất ngủ do tâm hỏa vượng.", kieng_ky: "Tỳ vị hư hàn, huyết áp thấp." },
    { nhom: "An thần", ten: "Lạc tiên (Chùm bao)", cong_dung: "Thanh tâm an thần, giải độc lợi tiểu, trị mất ngủ, lo âu.", kieng_ky: "Không dùng quá liều." },
    { nhom: "An thần", ten: "Lá vông nem (Vông diệp)", cong_dung: "An thần thông lạc, sát trùng chỉ ngứa, trị mất ngủ.", kieng_ky: "Không dùng liều quá cao gây rũ cơ." },
    { nhom: "An thần", ten: "Phục thần", cong_dung: "Ninh tâm an thần, kiện tỳ lợi thủy.", kieng_ky: "Thận hư di tinh, tiểu quá nhiều." },
    { nhom: "An thần", ten: "Nữ lang", cong_dung: "An thần, giảm lo âu, trấn kinh, trị mất ngủ.", kieng_ky: "Phụ nữ có thai, người dùng thuốc an thần mạnh." },
    { nhom: "An thần", ten: "Củ bình vôi", cong_dung: "Trấn kinh an thần, trấn thống, hạ huyết áp, trị mất ngủ.", kieng_ky: "Không dùng quá liều vì chứa độc tính rotundin." },
    { nhom: "An thần", ten: "Cây xấu hổ (Trinh nữ)", cong_dung: "An thần, khu phong trừ thấp, giảm đau, hạ áp nhẹ.", kieng_ky: "Thể trạng hư hàn, phụ nữ có thai." },
    { nhom: "An thần", ten: "Hợp hoan bì", cong_dung: "Giải uất an thần, hoạt huyết tiêu thũng.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "An thần", ten: "Dạ giao đằng (Dây hà thủ ô)", cong_dung: "Dưỡng tâm an thần, khu phong thông lạc.", kieng_ky: "Tỳ vị hư hàn tiêu chảy." },

    // --- NHÓM CÔNG HẠ (Nhuận tràng, Tả hạ) ---
    { nhom: "Công hạ", ten: "Đại hoàng", cong_dung: "Tả hạ thông tiện, thanh nhiệt tả hỏa, hoạt huyết hóa ứ.", kieng_ky: "Phụ nữ có thai, cho con bú, tỳ vị hư hàn." },
    { nhom: "Công hạ", ten: "Mang tiêu", cong_dung: "Tả hạ thông tiện, nhuận táo, nhuyễn kiên tán kết.", kieng_ky: "Phụ nữ có thai, tỳ vị hư hàn." },
    { nhom: "Công hạ", ten: "Lô hội (Nha đam)", cong_dung: "Tả hạ thông tiện, thanh can tả hỏa, sát trùng.", kieng_ky: "Phụ nữ có thai, đang hành kinh, tỳ vị hư hàn." },
    { nhom: "Công hạ", ten: "Ma tử nhân (Hỏa ma nhân)", cong_dung: "Nhuận tràng thông tiện, dưỡng âm.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy mạn." },
    { nhom: "Công hạ", ten: "Khiên ngưu tử", cong_dung: "Tả hạ trục thủy, sát trùng tiêu tích.", kieng_ky: "Phụ nữ có thai, cơ thể suy nhược." },
    { nhom: "Công hạ", ten: "Khoai lang", cong_dung: "Nhuận tràng thông tiện, bổ trung ích khí, trị táo bón.", kieng_ky: "Người đang bị tiêu chảy." },
    { nhom: "Công hạ", ten: "Vừng đen (Mè đen)", cong_dung: "Bổ can thận, nhuận ngũ tạng, nhuận tràng thông tiện, dưỡng huyết.", kieng_ky: "Tỳ hư đàm thấp, đại tiện lỏng nhão." },

    // --- NHÓM TRỪ THẤP (Lợi thủy, Thẩm thấp, Thông lâm) ---
    { nhom: "Trừ thấp", ten: "Trư linh", cong_dung: "Lợi thủy thẩm thấp.", kieng_ky: "Âm hư tân dịch khô." },
    { nhom: "Trừ thấp", ten: "Trạch tả", cong_dung: "Lợi thủy thẩm thấp, thanh nhiệt hạ tiêu.", kieng_ky: "Thận hư không có thấp nhiệt." },
    { nhom: "Trừ thấp", ten: "Xa tiền tử (Hạt mã đề)", cong_dung: "Lợi niệu thông lâm, thanh nhiệt minh mục, hóa đàm.", kieng_ky: "Thận hư, dương khí hạ hãm." },
    { nhom: "Trừ thấp", ten: "Phục linh (Bạch phục linh)", cong_dung: "Lợi thủy thẩm thấp, kiện tỳ, an thần.", kieng_ky: "Âm hư tiểu nhiều." },
    { nhom: "Trừ thấp", ten: "Long đởm thảo", cong_dung: "Thanh nhiệt táo thấp, tả can đởm hỏa.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Trừ thấp", ten: "Ý dĩ (Bo bo)", cong_dung: "Kiện tỳ thấm thấp, trừ tý, thanh nhiệt bài nùng.", kieng_ky: "Phụ nữ mang thai thời kỳ đầu cẩn trọng." },
    { nhom: "Trừ thấp", ten: "Râu ngô (Ngọc mễ tu)", cong_dung: "Lợi tiểu thanh nhiệt, lợi đởm thoái hoàng, trị sỏi mật, phù thũng.", kieng_ky: "Người đi tiểu quá nhiều, mất nước." },
    { nhom: "Trừ thấp", ten: "Mã đề (Xa tiền thảo)", cong_dung: "Lợi thủy thông lâm, thanh phế hóa đàm, thanh can minh mục.", kieng_ky: "Phụ nữ có thai, người già tiểu đêm nhiều." },
    { nhom: "Trừ thấp", ten: "Đậu đỏ (Xích tiểu đậu)", cong_dung: "Lợi thủy tiêu thũng, giải độc bài nùng.", kieng_ky: "Người đi tiểu quá nhiều, cơ thể khô gầy." },
    { nhom: "Trừ thấp", ten: "Thạch xương bồ", cong_dung: "Hóa thấp hòa vị, khai khiếu tỉnh thần, thông họng.", kieng_ky: "Âm hư huyết táo." },
    { nhom: "Trừ thấp", ten: "Hoạt thạch", cong_dung: "Thanh nhiệt lợi thấp, giải thử thông lâm.", kieng_ky: "Phụ nữ có thai, tỳ khí hư." },
    { nhom: "Trừ thấp", ten: "Tỳ giải", cong_dung: "Lợi thấp phân thanh trọc, khu phong thấp, trị tiểu đục.", kieng_ky: "Âm hư hỏa vượng, thận hư." },
    { nhom: "Trừ thấp", ten: "Hải kim sa", cong_dung: "Thanh nhiệt lợi niệu, thông lâm chỉ thống, trị sỏi niệu.", kieng_ky: "Âm hư tân dịch khô kiệt." },

    // --- NHÓM BÌNH CAN TỨC PHONG (Tiềm dương, Định kinh) ---
    { nhom: "Bình can tức phong", ten: "Cúc hoa (Hoa cúc)", cong_dung: "Tán phong thanh nhiệt, bình can minh mục, hạ huyết áp.", kieng_ky: "Tỳ vị hư hàn, đại tiện lỏng nhão." },
    { nhom: "Bình can tức phong", ten: "Ngải cứu", cong_dung: "Ôn kinh chỉ huyết, tán hàn chỉ thống, an thai.", kieng_ky: "Âm hư huyết nhiệt." },
    { nhom: "Bình can tức phong", ten: "Tang diệp (Lá dâu)", cong_dung: "Tán phong thanh nhiệt, thanh phế nhuận táo, bình can minh mục.", kieng_ky: "Phế hàn ho đờm loãng, tỳ vị hư hàn." },
    { nhom: "Bình can tức phong", ten: "Mẫu lệ (Vỏ hàu)", cong_dung: "Bình can tiềm dương, nhuyễn kiên tán kết, thu liễm cố sáp.", kieng_ky: "Hư hàn không có thực nhiệt." },
    { nhom: "Bình can tức phong", ten: "Thiên ma", cong_dung: "Bình can tiềm dương, tức phong chỉ kinh, trị đau đầu chóng mặt.", kieng_ky: "Huyết hư sinh phong không do can dương vượng." },
    { nhom: "Bình can tức phong", ten: "Bạch tật lê", cong_dung: "Bình can minh mục, khu phong chỉ ngứa, hành khí tán uất.", kieng_ky: "Phụ nữ có thai, huyết hư khí nhược." },
    { nhom: "Bình can tức phong", ten: "Câu đằng", cong_dung: "Thanh can tức phong, định kinh, thanh nhiệt hạ áp.", kieng_ky: "Huyết áp thấp, chứng hàn." },
    { nhom: "Bình can tức phong", ten: "Cương tàm (Bạch cương tàm)", cong_dung: "Khu phong định kinh, hóa đàm tán kết, trừ phong chẩn.", kieng_ky: "Huyết hư sinh phong." },
    { nhom: "Bình can tức phong", ten: "Địa long (Giun đất)", cong_dung: "Thanh nhiệt định kinh, thông lạc, bình can hạ áp, lợi niệu.", kieng_ky: "Tỳ vị hư hàn, không có thực nhiệt." },
    { nhom: "Bình can tức phong", ten: "Toàn yết (Bọ cạp)", cong_dung: "Tức phong định kinh, thông lạc chỉ thống, giải độc tán kết.", kieng_ky: "Phụ nữ có thai, huyết hư sinh phong." },
    { nhom: "Bình can tức phong", ten: "Thạch quyết minh (Vỏ bào ngư)", cong_dung: "Bình can tiềm dương, thanh can minh mục.", kieng_ky: "Tỳ vị hư hàn, không do can dương vượng." },

    // --- NHÓM TRỪ ĐÀM (Hóa đàm, Chỉ khái, Bình suyễn) ---
    { nhom: "Trừ đàm", ten: "Hạnh nhân", cong_dung: "Chỉ khái bình suyễn, nhuận tràng thông tiện.", kieng_ky: "Ho khan do âm hư, tiêu chảy." },
    { nhom: "Trừ đàm", ten: "Bối mẫu (Xuyên bối mẫu)", cong_dung: "Thanh nhiệt hóa đàm, nhuận phế chỉ khái, tán kết.", kieng_ky: "Ho do phong hàn, kỵ Ô đầu." },
    { nhom: "Trừ đàm", ten: "Tang bạch bì (Vỏ rễ dâu)", cong_dung: "Tả phế bình suyễn, lợi thủy tiêu thũng.", kieng_ky: "Ho hen do phế hàn hoặc khí hư." },
    { nhom: "Trừ đàm", ten: "Tử uyển", cong_dung: "Nhuận phế hạ khí, hóa đàm chỉ khái.", kieng_ky: "Ho khan do âm hư hỏa vượng." },
    { nhom: "Trừ đàm", ten: "Bán hạ chế", cong_dung: "Táo thấp hóa đàm, giáng nghịch chỉ nôn, tiêu bĩ tán kết.", kieng_ky: "Ho khan do âm hư, kỵ Ô đầu." },
    { nhom: "Trừ đàm", ten: "Trúc nhự", cong_dung: "Thanh nhiệt hóa đàm, trừ phiền chỉ nôn, lương huyết.", kieng_ky: "Nôn mửa do dạ dày hư hàn, hàn đàm." },
    { nhom: "Trừ đàm", ten: "Củ cải trắng (La phục tử/Củ)", cong_dung: "Tiêu thực hóa trệ, hạ khí hóa đàm, trị ho nhiều đờm.", kieng_ky: "Cơ thể hư nhược, ho khan không đờm." },
    { nhom: "Trừ đàm", ten: "Cát cánh", cong_dung: "Tuyên phế khứ đờm, lợi hầu bài nùng, dẫn thuốc đi lên.", kieng_ky: "Âm hư hỏa vượng, ho ra máu." },
    { nhom: "Trừ đàm", ten: "Đởm nam tinh", cong_dung: "Thanh nhiệt hóa đàm, tức phong định kinh.", kieng_ky: "Âm hư táo đờm, hàn đờm." },
    { nhom: "Trừ đàm", ten: "Khoản đông hoa", cong_dung: "Nhuận phế giáng khí, chỉ khái bình suyễn.", kieng_ky: "Ho ra máu, phế hỏa thịnh." },
    { nhom: "Trừ đàm", ten: "Bách bộ", cong_dung: "Nhuận phế chỉ khái, sát trùng diệt rận.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Trừ đàm", ten: "Tỳ bà diệp (Lá nhót tây)", cong_dung: "Thanh phế chỉ khái, giáng nghịch chỉ nôn.", kieng_ky: "Ho do phong hàn, nôn do vị hàn." },
    { nhom: "Trừ đàm", ten: "Cây bọ mắm (Thuốc dòi)", cong_dung: "Thanh phế, hóa đờm, chỉ khái, trị ho lao, viêm họng.", kieng_ky: "Phụ nữ có thai, tỳ vị hư hàn." },
    { nhom: "Trừ đàm", ten: "Hoa đu đủ đực", cong_dung: "Thanh phế chỉ khái, hóa đờm, trị ho mất tiếng, ho gà.", kieng_ky: "Phụ nữ mang thai (nguy cơ sẩy thai do papain)." },

    // --- NHÓM CHỈ HUYẾT (Cầm máu, Lương huyết) ---
    { nhom: "Chỉ huyết", ten: "Cỏ mực (Nhọ nồi)", cong_dung: "Lương huyết chỉ huyết, tư âm bổ thận.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Chỉ huyết", ten: "Trắc bách diệp", cong_dung: "Lương huyết chỉ huyết, hóa đờm chỉ khái.", kieng_ky: "Tỳ vị hư hàn nặng." },
    { nhom: "Chỉ huyết", ten: "Hoa hòe", cong_dung: "Lương huyết chỉ huyết, thanh can tả hỏa, hạ huyết áp.", kieng_ky: "Tỳ vị hư hàn, huyết áp quá thấp." },
    { nhom: "Chỉ huyết", ten: "Ngó sen (Ngẫu tiết)", cong_dung: "Thu liễm chỉ huyết, hóa ứ thanh nhiệt.", kieng_ky: "Thể trạng quá hư hàn, đầy bụng." },
    { nhom: "Chỉ huyết", ten: "Lá huyết dụ", cong_dung: "Lương huyết chỉ huyết, tán ứ tiêu thũng.", kieng_ky: "Phụ nữ có thai, phụ nữ sau sinh chưa sạch sản dịch." },
    { nhom: "Chỉ huyết", ten: "Bồ hoàng (Phấn hoa cỏ nến)", cong_dung: "Lương huyết chỉ huyết, hoạt huyết hóa ứ.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Chỉ huyết", ten: "Ô tặc cốt (Hải phiêu tiêu)", cong_dung: "Thu liễm chỉ huyết, cố tinh sáp niệu, chế acid dạ dày.", kieng_ky: "Âm hư hỏa vượng." },

    // --- NHÓM KHU PHONG THẤP (Thư cân, Trừ đau khớp) ---
    { nhom: "Khu phong thấp", ten: "Dây đau xương", cong_dung: "Khu phong thấp, thư cân hoạt lạc, trị đau nhức xương khớp.", kieng_ky: "Thể hư hàn, huyết hư không phong thấp." },
    { nhom: "Khu phong thấp", ten: "Hy thiêm", cong_dung: "Khu phong thấp, lợi gân cốt, giải độc.", kieng_ky: "Huyết hư phong thịnh, thận hư." },
    { nhom: "Khu phong thấp", ten: "Ngũ gia bì", cong_dung: "Khu phong thấp, mạnh gân cốt, bổ thận.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khu phong thấp", ten: "Tang ký sinh", cong_dung: "Bổ can thận, mạnh gân cốt, khu phong thấp, an thai.", kieng_ky: "Thấp nhiệt thực tà." },
    { nhom: "Khu phong thấp", ten: "Uy linh tiên", cong_dung: "Khu phong thấp, thông kinh lạc, tiêu tích thống.", kieng_ky: "Khí huyết hư nhược, phụ nữ có thai." },
    { nhom: "Khu phong thấp", ten: "Độc hoạt", cong_dung: "Khu phong thấp, chỉ thống, giải biểu hạ tiêu.", kieng_ky: "Âm hư huyết táo, khí huyết hư." },
    { nhom: "Khu phong thấp", ten: "Khương hoạt", cong_dung: "Phát biểu tán hàn, khu phong thấp, chỉ thống thượng tiêu.", kieng_ky: "Âm hư huyết hư." },
    { nhom: "Khu phong thấp", ten: "Tần giao", cong_dung: "Khu phong thấp, thanh thấp nhiệt, thối hoàng.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Khu phong thấp", ten: "Phòng kỷ", cong_dung: "Khu phong lợi thủy, tiêu thũng chỉ thống.", kieng_ky: "Khí hư, âm hư không thấp." },
    { nhom: "Khu phong thấp", ten: "Thiên niên kiện", cong_dung: "Khu phong thấp, cường gân cốt, ôn trung tán hàn.", kieng_ky: "Âm hư nội nhiệt." },
    { nhom: "Khu phong thấp", ten: "Dây gắm", cong_dung: "Khu phong trừ thấp, thư cân thông lạc, hạ acid uric.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Khu phong thấp", ten: "Cây chìa vôi", cong_dung: "Khu phong trừ thấp, thông kinh phá huyết, tiêu thũng.", kieng_ky: "Phụ nữ mang thai." },

    // --- NHÓM BỔ THẬN (Bổ dương, Cố tinh, Tráng gân cốt) ---
    { nhom: "Bổ thận", ten: "Cốt toái bổ", cong_dung: "Bổ thận, mạnh gân cốt, hóa ứ chỉ huyết, liền xương.", kieng_ky: "Âm hư hỏa vượng, huyết hư không ứ." },
    { nhom: "Bổ thận", ten: "Ba kích", cong_dung: "Ôn bổ thận dương, cường gân cốt, khu phong thấp.", kieng_ky: "Âm hư hỏa vượng, tiểu buốt, táo bón." },
    { nhom: "Bổ thận", ten: "Nhục thung dung", cong_dung: "Ôn bổ thận dương, ích tinh huyết, nhuận tràng thông tiện.", kieng_ky: "Tỳ vị hư hàn tiêu chảy, âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Tiên mao (Sâm cau)", cong_dung: "Ôn thận dương, tráng cân cốt, khu phong thấp, tán hàn.", kieng_ky: "Âm hư hỏa vượng, thực nhiệt." },
    { nhom: "Bổ thận", ten: "Dâm dương hoắc", cong_dung: "Ôn bổ thận dương, cường gân cốt, khu phong thấp.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Ích trí nhân", cong_dung: "Ôn thận cố sáp, ôn tỳ chỉ tả, nhiếp niệu.", kieng_ky: "Âm hư hỏa vượng, tiểu buốt do thấp nhiệt." },
    { nhom: "Bổ thận", ten: "Hải mã (Cá ngựa)", cong_dung: "Ôn thận tráng dương, tán kết tiêu thũng, hoạt huyết.", kieng_ky: "Phụ nữ có thai, âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Lộc nhung (Nhung hươu)", cong_dung: "Ôn thận tráng dương, ích tinh huyết, cường gân cốt.", kieng_ky: "Âm hư hỏa vượng, thực nhiệt, ho đờm vàng." },
    { nhom: "Bổ thận", ten: "Đông trùng hạ thảo", cong_dung: "Bổ phế ích thận, định suyễn hóa đờm, cầm máu.", kieng_ky: "Đang sốt, có chứng thực nhiệt ngoại cảm." },
    { nhom: "Bổ thận", ten: "Đỗ trọng", cong_dung: "Bổ can thận, mạnh gân cốt, an thai, hạ huyết áp.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Tục đoạn", cong_dung: "Bổ can thận, mạnh gân cốt, hành huyết ứ, an thai.", kieng_ky: "Thực nhiệt, thấp nhiệt." },
    { nhom: "Bổ thận", ten: "Cẩu tích (Lông culy)", cong_dung: "Bổ can thận, cường cơ xương, trừ phong thấp.", kieng_ky: "Âm hư hỏa vượng, tiểu buốt." },
    { nhom: "Bổ thận", ten: "Kim anh tử", cong_dung: "Cố tinh sáp niệu, sáp tràng chỉ tả.", kieng_ky: "Thực hỏa, thấp nhiệt, tiểu tiện khó." },
    { nhom: "Bổ thận", ten: "Nấm ngọc cẩu (Tỏa dương)", cong_dung: "Ôn bổ thận dương, ích tinh bổ huyết, mạnh gân cốt.", kieng_ky: "Âm hư hỏa vượng, tiêu chảy do thấp nhiệt." },
    { nhom: "Bổ thận", ten: "Mật nhân (Bách bệnh)", cong_dung: "Bổ thận tráng dương, thanh nhiệt giải độc, tăng sinh lý.", kieng_ky: "Phụ nữ có thai, người suy gan thận nặng." },
    { nhom: "Bổ thận", ten: "Quả mâm xôi (Phúc bồn tử)", cong_dung: "Bổ can thận, cố tinh sáp niệu, minh mục.", kieng_ky: "Thận âm hư có hỏa, tiểu buốt." },

    // --- CÁC NHÓM KHÁC (Khai khiếu, Tiêu thực, Khu trùng) ---
    { nhom: "Khai khiếu", ten: "Băng phiến", cong_dung: "Khai khiếu tỉnh thần, thanh nhiệt chỉ thống, tiêu thũng.", kieng_ky: "Phụ nữ có thai, thể khí huyết hư." },
    { nhom: "Khai khiếu", ten: "Tô hợp hương", cong_dung: "Khai khiếu tỉnh thần, hành khí chỉ thống.", kieng_ky: "Âm hư hỏa vượng, phụ nữ có thai." },
    { nhom: "Tiêu thực", ten: "Sơn tra (Táo mèo)", cong_dung: "Tiêu thực hóa tích, hoạt huyết hóa ứ, giảm mỡ máu.", kieng_ky: "Tỳ vị hư nhược không có tích trệ, dạ dày thừa acid." },
    { nhom: "Tiêu thực", ten: "Thần khúc", cong_dung: "Tiêu thực hòa vị, kiện tỳ.", kieng_ky: "Tỳ âm hư, dạ dày nhiều acid." },
    { nhom: "Tiêu thực", ten: "Mạch nha", cong_dung: "Tiêu thực hóa tích, kiện tỳ khai vị, hồi sữa.", kieng_ky: "Phụ nữ đang cho con bú không muốn mất sữa." },
    { nhom: "Tiêu thực", ten: "Kê nội kim (Màng mề gà)", cong_dung: "Kiện tỳ tiêu thực, hóa tích trệ, cố tinh hóa niệu.", kieng_ky: "Tỳ vị hư nhược không có tích trệ." },
    { nhom: "Khu trùng", ten: "Binh lang (Hạt cau)", cong_dung: "Sát trùng tiêu tích, hành khí lợi thủy, hạ khí.", kieng_ky: "Khí hư hạ hãm, tỳ vị hư nhược." },
    { nhom: "Khu trùng", ten: "Sử quân tử (Quả giun)", cong_dung: "Trừ giun sán, tiêu tích kiện tỳ.", kieng_ky: "Uống quá liều gây nấc cụt, chóng mặt." },
    { nhom: "Khu trùng", ten: "Trâm bầu", cong_dung: "Sát trùng, tẩy giun sán, tiêu tích trệ.", kieng_ky: "Phụ nữ mang thai, cơ thể suy nhược." },
];
const duocLieuBoSung = [
    // --- NHÓM THANH NHIỆT (Bổ bổ sung) ---
    { nhom: "Thanh nhiệt", ten: "Bạch hoa xà thiệt thảo", cong_dung: "Thanh nhiệt giải độc, tiêu thũng, hỗ trợ kháng u.", kieng_ky: "Phụ nữ có thai, người thể trạng hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Bán chi liên", cong_dung: "Thanh nhiệt giải độc, tiêu sưng giảm đau, chống viêm.", kieng_ky: "Phụ nữ có thai, người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cỏ roi ngựa (Mã tiền thảo)", cong_dung: "Thanh nhiệt giải độc, hoạt huyết hóa ứ, lợi thủy.", kieng_ky: "Phụ nữ mang thai, tỳ vị hư nhược." },
    { nhom: "Thanh nhiệt", ten: "Cỏ sữa lá nhỏ", cong_dung: "Thanh nhiệt giải độc, thông sữa, cầm lỵ.", kieng_ky: "Người tỳ vị hư hàn tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Cỏ sữa lá lớn", cong_dung: "Thanh nhiệt giải độc, tiêu viêm, cầm tiêu chảy.", kieng_ky: "Người thể trạng hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Đơn lá đỏ (Đơn đỏ)", cong_dung: "Thanh nhiệt giải độc, mẩn ngứa, dị ứng, mụn nhọt.", kieng_ky: "Người tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Mộc hoa trắng", cong_dung: "Thanh nhiệt táo thấp, trị kiết lỵ amip, tiêu chảy.", kieng_ky: "Người thể hư hàn không có thấp nhiệt." },
    { nhom: "Thanh nhiệt", ten: "Lá mật gấu", cong_dung: "Thanh nhiệt giải độc, mát gan, hỗ trợ hạ đường huyết.", kieng_ky: "Người huyết áp thấp, phụ nữ có thai." },
    { nhom: "Thanh nhiệt", ten: "Tử hoa địa đinh", cong_dung: "Thanh nhiệt giải độc, mát huyết, tiêu mụn nhọt.", kieng_ky: "Thể chứng âm hư, tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cải trời", cong_dung: "Thanh nhiệt giải độc, cầm máu, làm tan bướu hạch.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cây sống đời (Lá sống đời)", cong_dung: "Thanh nhiệt giải độc, cầm máu, làm lành vết thương.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Hoàng đằng", cong_dung: "Thanh nhiệt táo thấp, trị viêm kết mạc, kiết lỵ.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Vàng đắng", cong_dung: "Thanh nhiệt giải độc, sát trùng, trị lỵ và đau mắt đỏ.", kieng_ky: "Người tỳ vị hư hàn tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Cát hoa (Hoa sắn dây)", cong_dung: "Thanh nhiệt giải độc rượu, sinh tân chỉ khát.", kieng_ky: "Người thể trạng hư hàn, không có nhiệt." },
    { nhom: "Thanh nhiệt", ten: "Cỏ xước (Ngưu tất nam)", cong_dung: "Thanh nhiệt lợi thủy, khu phong thấp, thông kinh.", kieng_ky: "Phụ nữ có thai, người tỳ hư tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Cúc tần", cong_dung: "Thanh nhiệt, khu phong, giảm đau nhức, tiêu viêm.", kieng_ky: "Người thể trạng hư hàn ra nhiều mồ hôi." },
    { nhom: "Thanh nhiệt", ten: "Cỏ mần trầu", cong_dung: "Thanh nhiệt mát gan, hạ huyết áp, lợi tiểu.", kieng_ky: "Người tỳ vị hư hàn, huyết áp thấp." },
    { nhom: "Thanh nhiệt", ten: "Dây thìa canh", cong_dung: "Thanh nhiệt, giải độc, hỗ trợ hạ đường huyết.", kieng_ky: "Người tụt đường huyết, phụ nữ có thai." },
    { nhom: "Thanh nhiệt", ten: "Lá ổi", cong_dung: "Thanh nhiệt, sáp tràng chỉ tả, chữa tiêu chảy.", kieng_ky: "Người đang bị táo bón." },
    { nhom: "Thanh nhiệt", ten: "Lá bàng", cong_dung: "Thanh nhiệt giải độc, sát trùng, trị viêm họng, dạ dày.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Rau mương", cong_dung: "Thanh nhiệt giải độc, tiêu sưng, hỗ trợ trị dạ dày HP.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Cỏ chỉ (Rễ cỏ ống)", cong_dung: "Thanh nhiệt lợi tiểu, mát huyết, trị tiểu buốt.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Quả sung", cong_dung: "Thanh nhiệt giải độc, nhuận tràng, hỗ trợ trị trĩ.", kieng_ky: "Người tỳ vị hư hàn tiêu chảy." },
    { nhom: "Thanh nhiệt", ten: "Cây đơn răng cưa", cong_dung: "Thanh nhiệt giải độc, hạ sốt, trị mụn nhọt.", kieng_ky: "Người tỳ vị hư hàn." },
    { nhom: "Thanh nhiệt", ten: "Bạch hoa xà (Cây hoa xà)", cong_dung: "Thanh nhiệt giải độc, tiêu thũng, trừ phong thấp.", kieng_ky: "Phụ nữ mang thai." },

    // --- NHÓM BỔ DƯỠNG (Bổ khí, Bổ huyết, Tư âm, Bổ dương) ---
    { nhom: "Bổ khí", ten: "Sâm đất (Thổ nhân sâm)", cong_dung: "Bổ khí huyết, kiện tỳ vị, nhuận phế.", kieng_ky: "Người thực tà tích trệ." },
    { nhom: "Bổ dương", ten: "Sâm cau đỏ", cong_dung: "Bổ thận tráng dương, tăng cường khí lực, cường gân cốt.", kieng_ky: "Âm hư hỏa vượng, thể nhiệt." },
    { nhom: "Bổ khí", ten: "Sâm đá", cong_dung: "Bổ khí, tăng sức đề kháng, phục hồi sức khỏe.", kieng_ky: "Người sốt cao, thực nhiệt." },
    { nhom: "Bổ huyết", ten: "Hà thủ ô trắng", cong_dung: "Bổ huyết, thanh nhiệt giải độc, mỏi gối.", kieng_ky: "Tỳ hư đàm thấp, tiêu chảy." },
    { nhom: "Bổ huyết", ten: "Tử hà xa (Nhau thai)", cong_dung: "Đại bổ khí huyết, bổ thận ích tinh.", kieng_ky: "Thực nhiệt ngoại cảm, âm hư hỏa vượng." },
    { nhom: "Bổ dương", ten: "Cáp giới (Tắc kè)", cong_dung: "Bổ phế khí, ích thận tinh, tráng dương bình suyễn.", kieng_ky: "Phế nhiệt ho suyễn, ngoại cảm." },
    { nhom: "Bổ dương", ten: "Lộc giác (Sừng hươu)", cong_dung: "Bổ thận trợ dương, sinh tinh tủy, cường gân cốt.", kieng_ky: "Âm hư hỏa vượng, sốt cao." },
    { nhom: "Bổ huyết", ten: "Lộc giác giao (Keo sừng hươu)", cong_dung: "Bổ huyết chỉ huyết, ích tinh bổ thận.", kieng_ky: "Tỳ vị hư hàn tiêu chảy." },
    { nhom: "Bổ dương", ten: "Lộc giác sương", cong_dung: "Ôn bổ thận dương, thu liễm cố sáp.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ dương", ten: "Cao hổ cốt", cong_dung: "Bổ thận tráng dương, cường gân cốt, trừ phong thấp.", kieng_ky: "Âm hư hỏa vượng, sốt cao." },
    { nhom: "Bổ dưỡng", ten: "Mật gấu (Hùng đởm)", cong_dung: "Thanh nhiệt, giải độc, tán ứ, sáng mắt.", kieng_ky: "Phụ nữ có thai, thể hư hàn." },
    { nhom: "Tư âm", ten: "Tổ yến (Yến sào)", cong_dung: "Dưỡng âm nhuận phế, bổ trung ích khí, sinh tân.", kieng_ky: "Tỳ vị hư hàn, sốt cao cảm mạo." },
    { nhom: "Bổ dương", ten: "Bổ cốt chỉ (Phá cố chỉ)", cong_dung: "Ôn thận tráng dương, cố tinh sáp niệu, ôn tỳ chỉ tả.", kieng_ky: "Âm hư hỏa vượng, đại tiện táo bón." },
    { nhom: "Bổ thận", ten: "Sa uyển tử", cong_dung: "Bổ can thận, cố tinh sáp niệu, sáng mắt.", kieng_ky: "Âm hư hỏa vượng, tiểu buốt." },
    { nhom: "Bổ khí", ten: "Củ đinh lăng lá nhỏ (Rễ đinh lăng)", cong_dung: "Bổ khí huyết, tăng lực, thông huyết mạch.", kieng_ky: "Dùng quá liều gây tiêu chảy." },
    { nhom: "Bổ khí", ten: "Đảng sâm Nam", cong_dung: "Bổ khí dưỡng huyết, kiện tỳ lợi tiểu.", kieng_ky: "Thực tà tích trệ." },
    { nhom: "Bổ huyết", ten: "Củ ngải đen", cong_dung: "Bổ huyết, hành khí, tiêu viêm, đẹp da.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Bổ huyết", ten: "Hạt hà thủ ô", cong_dung: "Bổ huyết, nhuận tràng, làm đen tóc.", kieng_ky: "Tỳ vị hư hàn tiêu chảy." },
    { nhom: "Bổ huyết", ten: "Cao ban long", cong_dung: "Bổ huyết, bổ tinh, ích khí, dưỡng tủy.", kieng_ky: "Âm hư hỏa vượng, sốt cao." },
    { nhom: "Bổ huyết", ten: "Sâm quy đá", cong_dung: "Bổ huyết, hoạt huyết, giảm đau nhức xương khớp.", kieng_ky: "Phụ nữ có thai, tiêu chảy." },

    // --- NHÓM HOẠT HUYẾT - CHỈ HUYẾT ---
    { nhom: "Hoạt huyết", ten: "Củ xáo tam phân", cong_dung: "Hoạt huyết, thông kinh, tiêu viêm, kháng u.", kieng_ky: "Phụ nữ có thai, thể trạng suy nhược." },
    { nhom: "Hoạt huyết", ten: "Xuyên sơn giáp (Vảy tê tê)", cong_dung: "Hoạt huyết thông kinh, tiêu thũng bài nùng, hạ sữa.", kieng_ky: "Phụ nữ mang thai, thể hư không ứ." },
    { nhom: "Hoạt huyết", ten: "Một dược (Mộc dược)", cong_dung: "Hoạt huyết tán ứ, tiêu thũng sinh cơ, chỉ thống.", kieng_ky: "Phụ nữ mang thai, không có ứ trệ." },
    { nhom: "Hoạt huyết", ten: "Nhũ hương", cong_dung: "Hoạt huyết hành khí, tiêu thũng sinh cơ, chỉ thống.", kieng_ky: "Phụ nữ mang thai, tỳ vị hư nhược." },
    { nhom: "Hoạt huyết", ten: "Thủy điệt (Con đỉa sấy)", cong_dung: "Phá huyết khứ ứ, thông kinh tiêu tích.", kieng_ky: "Phụ nữ mang thai, xuất huyết cấp." },
    { nhom: "Hoạt huyết", ten: "Manh trùng (Ruồi trâu)", cong_dung: "Phá huyết khứ ứ, thông kinh tích trệ.", kieng_ky: "Phụ nữ mang thai, thể hư." },
    { nhom: "Hoạt huyết", ten: "Huyết kiệt", cong_dung: "Chỉ huyết hoạt huyết, tán ứ chỉ thống, sinh cơ.", kieng_ky: "Phụ nữ mang thai, không do ứ trệ." },
    { nhom: "Hoạt huyết", ten: "Lá ngải đen", cong_dung: "Hoạt huyết tiêu ứ, giảm đau nhức, điều kinh.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Chỉ huyết", ten: "Cỏ nhọ nồi thán (Sao cháy)", cong_dung: "Thu liễm chỉ huyết, cầm máu nhanh.", kieng_ky: "Không dùng khi có khối máu tụ." },
    { nhom: "Chỉ huyết", ten: "Hoa hòe thán (Hoa hòe sao cháy)", cong_dung: "Thu liễm chỉ huyết, trị trĩ ra máu.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Chỉ huyết", ten: "Lá đinh lăng thán", cong_dung: "Bổ huyết, cầm máu, tiêu uất.", kieng_ky: "Dùng quá liều." },
    { nhom: "Chỉ huyết", ten: "Chi tử thán (Dành dành sao cháy)", cong_dung: "Lương huyết chỉ huyết, thanh hỏa.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Chỉ huyết", ten: "Địa kim thảo", cong_dung: "Lương huyết chỉ huyết, thanh nhiệt giải độc.", kieng_ky: "Tỳ hư tiêu chảy." },
    { nhom: "Hoạt huyết", ten: "Hoa chuối (Bắp chuối)", cong_dung: "Hóa đờm nhuyễn kiên, bình can, thông kinh huyết.", kieng_ky: "Người thể hư hàn." },
    { nhom: "Hoạt huyết", ten: "Hạt gấc (Mộc biệt tử)", cong_dung: "Hành khí hoạt huyết, tiêu thũng, trị quai bị, mụn nhọt.", kieng_ky: "Có độc, không dùng liều cao đường uống." },
    { nhom: "Hoạt huyết", ten: "Vỏ thân cây gạo", cong_dung: "Thanh nhiệt lợi thấp, hoạt huyết tiêu thũng.", kieng_ky: "Người thể hư hàn." },
    { nhom: "Hoạt huyết", ten: "Thạch thượng bách nhật", cong_dung: "Hoạt huyết tiêu viêm, thanh nhiệt.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Dây đơn xương", cong_dung: "Khu phong trừ thấp, hoạt huyết giảm đau.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Củ gấu đỏ", cong_dung: "Hoạt huyết điều kinh, lý khí chỉ thống.", kieng_ky: "Khí hư huyết nhiệt." },
    { nhom: "Hoạt huyết", ten: "Cây gừng gió", cong_dung: "Hoạt huyết tán ứ, ôn trung, hỗ trợ giảm béo.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Hoạt huyết", ten: "Củ nần vàng", cong_dung: "Hoạt huyết, hạ mỡ máu, giảm béo.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Hoạt huyết", ten: "Rễ cau đỏ", cong_dung: "Hoạt huyết, tráng dương, sáp tinh.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Hoạt huyết", ten: "Lá xương sông", cong_dung: "Khu phong trừ thấp, thông kinh, trừ ho đờm.", kieng_ky: "Người âm hư hỏa vượng." },
    { nhom: "Hoạt huyết", ten: "Tía tô dại", cong_dung: "Hành khí hoạt huyết, giải cảm phong hàn.", kieng_ky: "Biểu hư tự hãn." },

    // --- NHÓM KHU HÀN - ÔN TRUNG - LÝ KHÍ ---
    { nhom: "Khu hàn", ten: "Xuyên tiêu (Sơn phục)", cong_dung: "Ôn trung tán hàn, chỉ thống, sát trùng đường ruột.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khu hàn", ten: "Hạt muồng sao cháy", cong_dung: "Thanh can, mát mắt, nhuận tràng.", kieng_ky: "Tỳ hư tiêu chảy." },
    { nhom: "Khu hàn", ten: "Biền đậu (Đậu ván trắng)", cong_dung: "Kiện tỳ hòa trung, tiêu thử hóa thấp.", kieng_ky: "Trúng hàn ngoại cảm." },
    { nhom: "Khu hàn", ten: "Quế thông (Quế dày)", cong_dung: "Bổ hỏa trợ dương, tán hàn chỉ thống.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Khu hàn", ten: "Quế tâm (Lõi quế)", cong_dung: "Ôn bổ tâm dương, hành huyết chỉ thống.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khu hàn", ten: "Bạc hà núi", cong_dung: "Ôn trung tán hàn, giải cảm, trừ thấp.", kieng_ky: "Thể âm hư hỏa vượng." },
    { nhom: "Lý khí", ten: "Trần bì lâu năm (Lão trần bì)", cong_dung: "Lý khí kiện tỳ, hóa đờm mạnh hơn trần bì tươi.", kieng_ky: "Ho khan âm hư." },
    { nhom: "Lý khí", ten: "Hạt bưởi", cong_dung: "Tiêu thực, hòa vị, tiêu phù thũng.", kieng_ky: "Dạ dày quá nhiều acid." },
    { nhom: "Lý khí", ten: "Lá chanh", cong_dung: "Hòa vị, chỉ khái, tiêu đờm, sát trùng.", kieng_ky: "Ho khan không đờm." },
    { nhom: "Lý khí", ten: "Vỏ cam khô", cong_dung: "Lý khí kiện tỳ, hóa đờm chỉ nôn.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Lý khí", ten: "Vỏ quất (Quả quất)", cong_dung: "Sơ can lý khí, giải uất, hóa đờm.", kieng_ky: "Âm hư nội nhiệt." },
    { nhom: "Lý khí", ten: "Vỏ vú sữa", cong_dung: "Lý khí sáp tràng, giảm đau dạ dày.", kieng_ky: "Táo bón." },
    { nhom: "Lý khí", ten: "Hoa chanh", cong_dung: "Sơ can lý khí, hòa vị giải uất.", kieng_ky: "Âm hư." },
    { nhom: "Lý khí", ten: "Hoa bưởi", cong_dung: "Sơ can lý khí, trừ phiền, giảm đau bụng.", kieng_ky: "Người khí hư." },
    { nhom: "Lý khí", ten: "Quả đại hồi (Bát giác)", cong_dung: "Ôn trung tán hàn, lý khí chỉ thống.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Lý khí", ten: "Củ sả (Rễ sả)", cong_dung: "Ôn trung giáng nghịch, kích thích tiêu hóa.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Lý khí", ten: "Lá lốt", cong_dung: "Ôn trung tán hàn, khu phong thấp, chỉ thống.", kieng_ky: "Nhiệt bộc, đau dạ dày thể nhiệt." },
    { nhom: "Lý khí", ten: "Cây riềng nếp", cong_dung: "Ôn trung tán hàn, tiêu thực chỉ nôn.", kieng_ky: "Dạ dày uất nhiệt." },
    { nhom: "Lý khí", ten: "Thảo quả", cong_dung: "Ôn trung tán hàn, táo thấp hóa đờm, trừ tiệt ngược.", kieng_ky: "Âm hư huyết hư." },
    { nhom: "Lý khí", ten: "Bạch đậu khấu", cong_dung: "Hành khí hóa thấp, ôn trung chỉ nôn, khai vị.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Lý khí", ten: "Hạt sẻ", cong_dung: "Ôn trung giáng nghịch, trừ tiêu chảy.", kieng_ky: "Thực nhiệt." },
    { nhom: "Lý khí", ten: "Củ ngải chống", cong_dung: "Hành khí, tiêu tích, ấm tỳ vị.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Lý khí", ten: "Rễ đinh hương", cong_dung: "Ôn tỳ vị, hạ khí chỉ nôn.", kieng_ky: "Âm hư." },
    { nhom: "Lý khí", ten: "Cây sa nhân đỏ", cong_dung: "Hành khí hóa thấp, ấm tỳ vị, an thai.", kieng_ky: "Âm hư nhiệt." },
    { nhom: "Lý khí", ten: "Sả hương", cong_dung: "Hành khí thông kinh, sát trùng, ấm bụng.", kieng_ky: "Thể âm hư." },

    // --- NHÓM TRỪ ĐÀM - AN THẦN - CÔNG HẠ - GIẢI BIỂU ---
    { nhom: "Trừ đàm", ten: "Cơ bạch bối", cong_dung: "Thanh nhiệt hóa đờm, nhuận phế chỉ khái.", kieng_ky: "Phong hàn ho." },
    { nhom: "Trừ đàm", ten: "Trúc nhự thán", cong_dung: "Chỉ huyết thanh nhiệt, hóa đờm chỉ nôn.", kieng_ky: "Hư hàn." },
    { nhom: "Trừ đàm", ten: "Trúc nhự tươi", cong_dung: "Thanh nhiệt hóa đờm, trừ phiền.", kieng_ky: "Vị hàn nôn mửa." },
    { nhom: "Trừ đàm", ten: "Củ ngải cứu", cong_dung: "Ôn kinh tán hàn, hóa đờm trệ.", kieng_ky: "Âm hư huyết nhiệt." },
    { nhom: "Trừ đàm", ten: "Bạch giới tử (Hạt cải trắng)", cong_dung: "Ôn phế hóa đờm, hành khí tán kết, giảm đau.", kieng_ky: "Phế hỏa ho khan, viêm loét dạ dày." },
    { nhom: "Trừ đàm", ten: "Giới tử (Hạt cải đắng)", cong_dung: "Ôn phế hóa đờm, lợi khí chỉ thống, tán kết.", kieng_ky: "Ho khan do âm hư hỏa vượng." },
    { nhom: "Trừ đàm", ten: "Thạch xông (Xương bồ núi)", cong_dung: "Hóa đờm khai khiếu, kiện tỳ trừ thấp.", kieng_ky: "Âm hư." },
    { nhom: "Trừ đàm", ten: "Hoa húng chanh (Tần dầy lá)", cong_dung: "Thanh phế hóa đờm, giải cảm, trị ho mất tiếng.", kieng_ky: "Người thể hư hàn." },
    { nhom: "Trừ đàm", ten: "Quả hồng bị (Quất hồng bì)", cong_dung: "Tiêu thực hóa đờm, lý khí ôn trung.", kieng_ky: "Âm hư ho khan." },
    { nhom: "Trừ đàm", ten: "Lá húng chanh", cong_dung: "Phát tán phong hàn, hóa đờm chỉ khái, giải độc.", kieng_ky: "Thể mồ hôi tự chảy nhiều." },
    { nhom: "Trừ đàm", ten: "Củ thiên nam tinh (Chế)", cong_dung: "Táo thấp hóa đờm, khu phong định kinh, tán kết.", kieng_ky: "Có độc lớn khi dùng sống; cấm dùng cho âm hư." },
    { nhom: "Trừ đàm", ten: "Trúc lịch (Nước tre thui)", cong_dung: "Thanh nhiệt hóa đờm, khai khiếu định kinh.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Trừ đàm", ten: "Côn bố (Tảo bẹ)", cong_dung: "Hóa đờm nhuyễn kiên, lợi thủy tiêu thũng.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Trừ đàm", ten: "Hải tảo (Rêu biển)", cong_dung: "Hóa đờm nhuyễn kiên, tiêu bướu cổ, lợi thủy.", kieng_ky: "Tỳ vị hư hàn, kỵ Cam thảo." },
    { nhom: "An thần", ten: "Chu sa (Thần sa)", cong_dung: "Trấn tâm an thần, thanh nhiệt giải độc.", kieng_ky: "Có độc (chứa thủy ngân), cấm dùng liều cao kéo dài." },
    { nhom: "An thần", ten: "Hổ phách", cong_dung: "Trấn kinh an thần, tán ứ chỉ huyết, lợi thủy.", kieng_ky: "Không có thực nhiệt hoặc ứ trệ." },
    { nhom: "An thần", ten: "Từ thạch (Magnetit)", cong_dung: "Trấn an thần, bình can tiềm dương, thông tai sáng mắt.", kieng_ky: "Tỳ vị hư nhược." },
    { nhom: "An thần", ten: "Trân châu (Ngọc trai)", cong_dung: "Trấn kinh an thần, thanh can minh mục, giải độc sinh cơ.", kieng_ky: "Người thể hư hàn." },
    { nhom: "An thần", ten: "Trân châu mẫu (Vỏ ngọc trai)", cong_dung: "Bình can tiềm dương, trấn kinh an thần, sáng mắt.", kieng_ky: "Thể hư hàn." },
    { nhom: "An thần", ten: "Củ khoai từ", cong_dung: "Kiện tỳ ích khí, an thần, giải độc.", kieng_ky: "Đầy trướng bụng." },
    { nhom: "An thần", ten: "Lá đinh lăng", cong_dung: "An thần, dưỡng não, tăng cường trí nhớ, chữa mất ngủ.", kieng_ky: "Dùng quá liều gây mệt mỏi." },
    { nhom: "An thần", ten: "Hoa tam thất", cong_dung: "Thanh nhiệt, bình can, an thần, hạ huyết áp, chữa mất ngủ.", kieng_ky: "Phụ nữ có thai, người huyết áp quá thấp." },
    { nhom: "Công hạ", ten: "Phan tả diệp", cong_dung: "Tả nhiệt thông tiện, tiêu tích trệ, nhuận tràng.", kieng_ky: "Phụ nữ có thai, người tỳ vị hư hàn tiêu chảy." },
    { nhom: "Công hạ", ten: "Thương lục", cong_dung: "Trục thủy tiêu thũng, thông lợi nhị tiện.", kieng_ky: "Có độc lớn, phụ nữ mang thai cấm dùng." },
    { nhom: "Công hạ", ten: "Ba đậu (Hạt ba đậu)", cong_dung: "Tả hạ phá tích cực mạnh, trục thủy tiêu thũng.", kieng_ky: "Độc tính rất cao, phụ nữ mang thai cấm dùng." },
    { nhom: "Công hạ", ten: "Túc hoa (Sui)", cong_dung: "Trục thủy tiêu thũng, sát trùng.", kieng_ky: "Độc tính cao, phụ nữ có thai cấm dùng." },
    { nhom: "Công hạ", ten: "Đại kích", cong_dung: "Trục thủy tiêu thũng, giải độc tán kết.", kieng_ky: "Phụ nữ có thai, thể hư, kỵ Cam thảo." },
    { nhom: "Giải biểu", ten: "Cây húng chanh", cong_dung: "Phát tán phong hàn, tuyên phế, chỉ khái.", kieng_ky: "Người bị mồ hôi tự chảy." },
    { nhom: "Giải biểu", ten: "Lá lốt tươi", cong_dung: "Tán phong hàn, thấp tý, ấm tỳ vị.", kieng_ky: "Nhiệt chứng." },
    { nhom: "Giải biểu", ten: "Lá tía tô rừng", cong_dung: "Phát tán phong hàn, lý khí, giải độc.", kieng_ky: "Biểu hư tự hãn." },
    { nhom: "Giải biểu", ten: "Vỏ quýt tươi (Sơ trần bì)", cong_dung: "Phát tán nhẹ, lý khí hóa đờm.", kieng_ky: "Âm hư ho khan." },
    { nhom: "Giải biểu", ten: "Hoa kinh giới", cong_dung: "Phát tán phong hàn, thấu chẩn mạnh hơn lá.", kieng_ky: "Mụn nhọt đã vỡ." },
    { nhom: "Giải biểu", ten: "Rễ cây cúc tần", cong_dung: "Khu phong trừ thấp, phát biểu tán hàn.", kieng_ky: "Người thể hư." },
    { nhom: "Giải biểu", ten: "Củ nén (Hành tăm)", cong_dung: "Giải biểu tán hàn, sát trùng, giải độc, trị cảm mạo.", kieng_ky: "Âm hư hỏa vượng." },

    // --- NHÓM KHU PHONG THẤP - BỔ THẬN ---
    { nhom: "Khu phong thấp", ten: "Tang ký sinh núi", cong_dung: "Bổ can thận, mạnh gân cốt, trừ phong thấp.", kieng_ky: "Thấp nhiệt thực tà." },
    { nhom: "Khu phong thấp", ten: "Kê huyết đằng núi", cong_dung: "Bổ huyết, hoạt huyết, thư cân thông lạc.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Khu phong thấp", ten: "Tơ hồng xanh", cong_dung: "Thanh nhiệt, lợi thấp, bổ can thận, hạ áp.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khu phong thấp", ten: "Rễ cây gắm", cong_dung: "Khu phong trừ thấp, giảm đau nhức xương khớp, hạ acid uric.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Khu phong thấp", ten: "Cây cối xay", cong_dung: "Thanh nhiệt giải độc, lợi tiểu, khu phong trừ thấp, trị ù tai.", kieng_ky: "Phụ nữ có thai, tỳ vị hư hàn." },
    { nhom: "Khu phong thấp", ten: "Rễ cây bưởi bung", cong_dung: "Khu phong thấp, hành khí, tiêu viêm, trị đau lưng.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Khu phong thấp", ten: "Dây đau xương dại", cong_dung: "Khu phong trừ thấp, thư cân hoạt lạc.", kieng_ky: "Thể trạng hư hàn." },
    { nhom: "Khu phong thấp", ten: "Rễ xương sông", cong_dung: "Khu phong trừ thấp, thông kinh chỉ thống.", kieng_ky: "Âm hư nội nhiệt." },
    { nhom: "Khu phong thấp", ten: "Cây ngải chống xương", cong_dung: "Khu phong thấp, ấm gân cốt, trị đau thắt lưng.", kieng_ky: "Thể nhiệt." },
    { nhom: "Khu phong thấp", ten: "Dây gắm đỏ", cong_dung: "Trừ phong thấp, thông kinh lạc, chữa gút.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Khu phong thấp", ten: "Cây cốt khí củ", cong_dung: "Khu phong trừ thấp, hoạt huyết thông kinh, thanh nhiệt.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Khu phong thấp", ten: "Vỏ thân cây gội", cong_dung: "Trừ phong thấp, tiêu sưng, trị đau khớp.", kieng_ky: "Người tỳ vị hư." },
    { nhom: "Khu phong thấp", ten: "Rễ gấc", cong_dung: "Khu phong trừ thấp, tiêu thũng giảm đau.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Khu phong thấp", ten: "Cây đai vàng", cong_dung: "Khu phong thấp, bổ thận, tráng dương.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khu phong thấp", ten: "Tang ký sinh cây gạo", cong_dung: "Bổ can thận, mạnh gân cốt, giảm đau nhức.", kieng_ky: "Thực nhiệt." },
    { nhom: "Khu phong thấp", ten: "Cây mấu quạ (Mỏ quạ)", cong_dung: "Trừ phong thấp, hoạt huyết, tiêu viêm.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Khu phong thấp", ten: "Cây chìa vôi lá tre", cong_dung: "Khu phong lợi thấp, tiêu thũng, trị thoát vị đĩa đệm.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Bổ thận", ten: "Lá nấm ngọc cẩu", cong_dung: "Ôn bổ thận dương, ích tinh huyết.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Bổ cốt chỉ sao muối", cong_dung: "Tăng khả năng dẫn thuốc vào thận, cố tinh sáp niệu.", kieng_ky: "Âm hư táo bón." },
    { nhom: "Bổ thận", ten: "Kim anh tử sao cháy", cong_dung: "Thu liễm cố sáp mạnh, chữa di tinh, đi tiểu đêm.", kieng_ky: "Tiểu buốt dắt." },
    { nhom: "Bổ thận", ten: "Thỏ ty tử sao muối", cong_dung: "Dẫn thuốc vào thận, ôn bổ thận tinh.", kieng_ky: "Táo bón, âm hư." },
    { nhom: "Bổ thận", ten: "Sâm cau đen", cong_dung: "Ôn thận tráng dương, tăng cường sinh lực, trừ phong thấp.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Lộc nhung thán (Nhung hươu sao)", cong_dung: "Bổ huyết chỉ huyết, tráng dương.", kieng_ky: "Thực nhiệt." },
    { nhom: "Bổ thận", ten: "Pín hổ (Hổ thận)", cong_dung: "Đại bổ thận dương, ích tinh tủy.", kieng_ky: "Âm hư hỏa vượng, sốt cao." },
    { nhom: "Bổ thận", ten: "Pín bò (Ngưu thận)", cong_dung: "Bổ thận tráng dương, cường gân cốt.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Thận dê (Dương thận)", cong_dung: "Ôn trung bổ thận, tráng dương ích tinh.", kieng_ky: "Thực nhiệt, âm hư." },
    { nhom: "Bổ thận", ten: "Thận lợn (Trư thận)", cong_dung: "Bổ thận khí, ích tinh tủy, giảm đau lưng.", kieng_ky: "Thấp nhiệt." },
    { nhom: "Bổ thận", ten: "Tụ tinh thảo", cong_dung: "Bổ thận cố tinh, minh mục.", kieng_ky: "Nhiệt chứng." },
    { nhom: "Bổ thận", ten: "Củ ba kích trắng", cong_dung: "Bổ thận dương, cường gân cốt, trừ phong thấp.", kieng_ky: "Âm hư hỏa vượng, tiểu buốt." },
    { nhom: "Bổ thận", ten: "Củ đỗ trọng nam (Vỏ cạn)", cong_dung: "Bổ can thận, mạnh gân cốt, hạ áp.", kieng_ky: "Âm hư." },
    { nhom: "Bổ thận", ten: "Thạch hộc tươi", cong_dung: "Tư âm thanh nhiệt mạnh, dưỡng vị sinh tân.", kieng_ky: "Hư hàn." },
    { nhom: "Bổ thận", ten: "Cây bổ béo", cong_dung: "Bổ thận, kích thích ăn ngon, tăng cân.", kieng_ky: "Người thể thực nhiệt." },
    { nhom: "Bổ thận", ten: "Rễ cây vú sữa", cong_dung: "Bổ thận, cường gân cốt, giảm đau lưng.", kieng_ky: "Âm hư." },
    { nhom: "Bổ thận", ten: "Thổ cao sơn", cong_dung: "Bổ thận khí, an thai, kiện tỳ.", kieng_ky: "Thực tà." },
    { nhom: "Bổ thận", ten: "Hạt hẹ (Cửu thái tử)", cong_dung: "Bổ thận tráng dương, cố tinh, ấm lưng gối.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Bổ thận", ten: "Rễ cây hẹ", cong_dung: "Ôn thận trợ dương, hành khí tán ứ.", kieng_ky: "Âm hư nội nhiệt." },
    { nhom: "Bổ thận", ten: "Lá hẹ", cong_dung: "Bổ thận, ấm tỳ vị, giải độc, cầm máu.", kieng_ky: "Âm hư hỏa vượng, đau mắt đỏ." },
    { nhom: "Bổ thận", ten: "Xích thạch chi (Đất sét đỏ)", cong_dung: "Cố sáp chỉ tả, thu liễm chỉ huyết, sinh cơ.", kieng_ky: "Thực nhiệt, táo bón." },
    { nhom: "Bổ thận", ten: "Vũ dư lương (Quặng sắt nâu)", cong_dung: "Thu liễm cố sáp, chỉ tả, chỉ đới.", kieng_ky: "Thấp nhiệt tích trệ." },
    { nhom: "Bổ thận", ten: "Phục long can (Đất lòng bếp)", cong_dung: "Ôn trung chỉ huyết, chỉ nôn chỉ tả.", kieng_ky: "Âm hư huyết nhiệt." },

    // --- NHÓM TRỪ THẤP - TIÊU THỰC - KHU TRÙNG - KHAI KHIẾU - NGOẠI DÙNG ---
    { nhom: "Trừ thấp", ten: "Đông qua bì (Vỏ bí đao)", cong_dung: "Thanh nhiệt lợi thủy, tiêu thũng.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Trừ thấp", ten: "Đông qua nhân (Hạt bí đao)", cong_dung: "Thanh nhiệt hóa đờm, trừ mủ, lợi thủy.", kieng_ky: "Tỳ hư tiêu chảy." },
    { nhom: "Trừ thấp", ten: "Hạt bí đỏ (Nam qua nhân)", cong_dung: "Sát trùng, tẩy giun sán, lợi tiểu.", kieng_ky: "Không có." },
    { nhom: "Trừ thấp", ten: "Khổ qua rừng (Toàn cây)", cong_dung: "Thanh nhiệt, lợi thấp, mát gan, hạ đường huyết.", kieng_ky: "Phụ nữ mang thai, tỳ vị hư hàn." },
    { nhom: "Trừ thấp", ten: "Củ dong riềng đỏ", cong_dung: "Thanh nhiệt, lợi niệu, thông huyết mạch, trị mạch vành.", kieng_ky: "Thể trạng hư hàn." },
    { nhom: "Trừ thấp", ten: "Rễ cỏ tranh sao vàng", cong_dung: "Lương huyết chỉ huyết, lợi tiểu bớt tính lạnh.", kieng_ky: "Hư hàn." },
    { nhom: "Trừ thấp", ten: "Cây cúc áo hoa vàng", cong_dung: "Thanh nhiệt lợi thấp, giảm đau răng, chữa phong thấp.", kieng_ky: "Phụ nữ có thai." },
    { nhom: "Trừ thấp", ten: "Lá tre ngà", cong_dung: "Thanh nhiệt trừ phiền, lợi tiểu, hạ sốt.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Trừ thấp", ten: "Trúc nhự tre ngà", cong_dung: "Thanh nhiệt hóa đờm, lợi tiểu.", kieng_ky: "Vị hàn tiêu chảy." },
    { nhom: "Trừ thấp", ten: "Cây kim tiền thảo", cong_dung: "Thanh nhiệt lợi niệu, thông lâm, bài sỏi mật và sỏi thận.", kieng_ky: "Phụ nữ mang thai, người bị tiêu chảy do hư hàn." },
    { nhom: "Trừ thấp", ten: "Rễ cây kim tiền thảo", cong_dung: "Lợi tiểu, bài sỏi, thanh nhiệt.", kieng_ky: "Tỳ vị hư hàn." },
    { nhom: "Trừ thấp", ten: "Cây chuối hột (Thân / Rễ)", cong_dung: "Lợi tiểu, bài sỏi thận, giải độc, trị đau lưng.", kieng_ky: "Người đang bị đau dạ dày nặng (nếu dùng hạt)." },
    { nhom: "Trừ thấp", ten: "Hạt chuối hột", cong_dung: "Khu phong trừ thấp, lợi tiểu, bài sỏi, giảm đau nhức.", kieng_ky: "Người bị loét dạ dày." },
    { nhom: "Trừ thấp", ten: "Vỏ quả dừa (Sơ dừa thán)", cong_dung: "Chỉ huyết, lợi tiểu, thông kinh.", kieng_ky: "Không có." },
    { nhom: "Trừ thấp", ten: "Nước dừa tươi", cong_dung: "Thanh nhiệt giải thử, sinh tân chỉ khát, lợi tiểu.", kieng_ky: "Người thể trạng hư hàn, mới đi nắng về." },
    { nhom: "Tiêu thực", ten: "Hạt đu đủ", cong_dung: "Sát trùng, tẩy giun, tiêu thực.", kieng_ky: "Phụ nữ mang thai." },
    { nhom: "Tiêu thực", ten: "Quả me (Thịt me)", cong_dung: "Thanh nhiệt, giải thử, tiêu thực, sinh tân.", kieng_ky: "Dạ dày thừa acid, tỳ vị hư hàn." },
    { nhom: "Tiêu thực", ten: "Quả khế chua sao", cong_dung: "Tiêu thực, thanh nhiệt, lợi tiểu.", kieng_ky: "Sỏi thận, bệnh thận mạn." },
    { nhom: "Tiêu thực", ten: "Lá khế", cong_dung: "Thanh nhiệt giải độc, trị mẩn ngứa, mụn nhọt.", kieng_ky: "Người hư hàn." },
    { nhom: "Tiêu thực", ten: "Rễ cây me", cong_dung: "Sáp tràng chỉ tả, tiêu thực.", kieng_ky: "Táo bón." },
    { nhom: "Khu trùng", ten: "Rễ cây dừa", cong_dung: "Sát trùng, sáp tràng, cầm tiêu chảy.", kieng_ky: "Táo bón." },
    { nhom: "Khu trùng", ten: "Vỏ rễ cây lựu", cong_dung: "Sát trùng, tẩy giun sán, sáp tràng chỉ tả.", kieng_ky: "Có độc nhẹ, phụ nữ mang thai và trẻ nhỏ cẩn trọng." },
    { nhom: "Khu trùng", ten: "Vỏ quả lựu (Thạch lựu bì)", cong_dung: "Sáp tràng chỉ tả, sáp tinh, cầm máu, diệt giun.", kieng_ky: "Thực nhiệt, lỵ mới phát." },
    { nhom: "Khai khiếu", ten: "Xạ hương", cong_dung: "Khai khiếu tỉnh thần, thông kinh lạc, tán kết tiêu thũng.", kieng_ky: "Phụ nữ có thai cấm tuyệt đối (gây sảy thai)." },
    { nhom: "Khai khiếu", ten: "An túc hương (Nhựa An túc)", cong_dung: "Khai khiếu tỉnh thần, hành khí chỉ thống.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Khai khiếu", ten: "Cây băng phiến (Long não)", cong_dung: "Sát trùng, thông khiếu, giảm đau, khu phong.", kieng_ky: "Phụ nữ mang thai, trẻ sơ sinh." },
    { nhom: "Ngoại dùng", ten: "Lưu hoàng (Lưu huỳnh)", cong_dung: "Sát trùng diệt nấm ngoài da, bổ hỏa tráng dương (chế).", kieng_ky: "Âm hư hỏa vượng, độc tính cao." },
    { nhom: "Ngoại dùng", ten: "Phèn phi (Mình phán phi)", cong_dung: "Tháo thấp, sát trùng, chỉ huyết, làm khô vết thương.", kieng_ky: "Âm hư tân dịch khô." },
    { nhom: "Ngoại dùng", ten: "Xà sàng tử", cong_dung: "Ôn thận tráng dương, khu phong mẫn ngứa, sát trùng trùng roi.", kieng_ky: "Âm hư hỏa vượng." },
    { nhom: "Ngoại dùng", ten: "Mã tiền ngâm rượu (Ngoại dùng)", cong_dung: "Thông kinh hoạt lạc, xoa bóp giảm đau nhức xương khớp dữ dội.", kieng_ky: "Cấm uống trực tiếp rượu ngâm, không bôi lên vết thương hở." },
    { nhom: "An thần", ten: "Hoa nhài", cong_dung: "Giải uất an thần, thanh nhiệt, giúp giấc ngủ sâu và thư thái.", kieng_ky: "Người tỳ vị hư hàn, hay tiêu chảy." },
    { nhom: "An thần", ten: "Lá sen (Liên diệp)", cong_dung: "Thanh tâm hỏa, bình gan, hạ áp nhẹ, an thần, giúp ngủ ngon.", kieng_ky: "Người thể trạng hư hàn, huyết áp quá thấp." },
    { nhom: "Thanh nhiệt", ten: "Diếp cá (Ngư tinh thảo)", cong_dung: "Thanh nhiệt giải độc, tiêu viêm, lợi tiểu, trị mụn nhọt, trĩ.", kieng_ky: "Người tỳ vị hư hàn, hay bị lạnh bụng tiêu chảy." },
    { nhom: "Trừ thấp", ten: "Thương truật", cong_dung: "Táo thấp kiện tỳ, trừ phong thấp, minh mục.", kieng_ky: "Âm hư hỏa vượng, nhiều mồ hôi, tân dịch khô." },
    { nhom: "Trừ đàm", ten: "Qua lâu (Qua lâu nhân)", cong_dung: "Thanh phế nhuận táo, hóa đàm, nhuận tràng thông tiện.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy, kỵ Ô đầu." },
    { nhom: "Giải biểu", ten: "Hành hoa (Hành ta / Thông bạch)", cong_dung: "Phát hãn giải biểu, ôn trung tán hàn, thông dương.", kieng_ky: "Âm hư hỏa vượng, người ra nhiều mồ hôi." },
    { nhom: "Công hạ", ten: "Úc lý nhân", cong_dung: "Nhuận táo thông tiện, lợi thủy tiêu thũng.", kieng_ky: "Phụ nữ có thai, người đại tiện lỏng nhão." },
    { nhom: "Bổ huyết", ten: "Nữ trinh tử", cong_dung: "Bổ can thận, dưỡng âm minh mục, làm đen râu tóc.", kieng_ky: "Tỳ vị hư hàn, tiêu chảy." },
    { nhom: "Bổ khí", ten: "Mật ong (Phong mật)", cong_dung: "Bổ trung ích khí, nhuận phế chỉ khái, nhuận tràng, hòa hoãn dược tính.", kieng_ky: "Trẻ em dưới 1 tuổi, người đang tiêu chảy, đàm thấp nặng." }
];
    window.duocLieuData = [...duocLieuData1, ...duocLieuBoSung];
