// === ĐỢT 1: KINH PHẾ, ĐẠI TRƯỜNG, VỊ, TỲ, TÂM, TIỂU TRƯỜNG (STT 1 - 124) ===
window.huyetViDataBatch1 = [
    // --- KINH THỦ THÁI ÂM PHẾ (11 huyệt) ---
    { stt: 1, ma_who: "LU1", kinh: "Kinh Phế", ten: "Trung Phủ", vi_tri: "Khoang liên sườn 1, cách đường giữa ngực 6 thốn, dưới bờ ngoài xương đòn 1 thốn", chu_tri: "Ho, hen suyễn, đau tức ngực, đau vùng vai gáy và chi trên" },
    { stt: 2, ma_who: "LU2", kinh: "Kinh Phế", ten: "Vân Môn", vi_tri: "Chỗ lõm dưới xương đòn, cách đường giữa ngực 6 thốn, phía trên huyệt Trung Phủ", chu_tri: "Ho, hen suyễn, đau ngực sườn, đau khớp vai và cẳng tay" },
    { stt: 3, ma_who: "LU3", kinh: "Kinh Phế", ten: "Thiên Phủ", vi_tri: "Mặt trước ngoài cánh tay, bờ ngoài cơ nhị đầu, dưới nếp gấp nách trước 3 thốn", chu_tri: "Ho, hen suyễn, chảy máu cam, đau mặt trong cánh tay" },
    { stt: 4, ma_who: "LU4", kinh: "Kinh Phế", ten: "Hiệp Bạch", vi_tri: "Mặt trước ngoài cánh tay, bờ ngoài cơ nhị đầu, dưới huyệt Thiên Phủ 1 thốn", chu_tri: "Ho suyễn, đau vùng tim ngực, nôn mửa, đau xóc sườn, đau cẳng tay" },
    { stt: 5, ma_who: "LU5", kinh: "Kinh Phế", ten: "Xích Trạch", vi_tri: "Trên nếp gấp khuỷu tay, chỗ lõm bờ ngoài gân cơ nhị đầu cánh tay", chu_tri: "Ho ra máu, sốt cao, viêm họng, đau khớp khuỷu và cẳng tay" },
    { stt: 6, ma_who: "LU6", kinh: "Kinh Phế", ten: "Khổng Tối", vi_tri: "Mặt trước cẳng tay, trên đường nối Thái Uyên - Xích Trạch, từ nếp cổ tay đo lên 7 thốn", chu_tri: "Ho ra máu, sưng đau hầu họng, sốt không ra mồ hôi, đau khuỷu tay" },
    { stt: 7, ma_who: "LU7", kinh: "Kinh Phế", ten: "Liệt Khuyết", vi_tri: "Mặt ngoài cẳng tay, trên mỏm trâm quay, trên nếp cổ tay 1.5 thốn", chu_tri: "Đau đầu, đau gáy, ho, liệt mặt, đau nhức cổ tay" },
    { stt: 8, ma_who: "LU8", kinh: "Kinh Phế", ten: "Kinh Cừ", vi_tri: "Mặt trước cẳng tay, trên nếp cổ tay 1 thốn, chỗ lõm giữa mỏm trâm quay và động mạch quay", chu_tri: "Ho suyễn, sốt không mồ hôi, sưng đau họng, đau khớp cổ tay" },
    { stt: 9, ma_who: "LU9", kinh: "Kinh Phế", ten: "Thái Uyên", vi_tri: "Tại nếp gấp cổ tay, chỗ lõm phía ngoài động mạch quay", chu_tri: "Ho, hen suyễn, đau ngực, viêm khớp cổ tay, vô mạch" },
    { stt: 10, ma_who: "LU10", kinh: "Kinh Phế", ten: "Ngư Tế", vi_tri: "Điểm giữa xương đốt ngón tay cái thứ nhất, ranh giới da mu - lòng bàn tay", chu_tri: "Ho ra máu, sốt, khô họng, mất tiếng cấp tính, đau ngón cái" },
    { stt: 11, ma_who: "LU11", kinh: "Kinh Phế", ten: "Thiếu Thương", vi_tri: "Bờ ngoài ngón tay cái, cách gốc móng tay 0.1 thốn về phía xương quay", chu_tri: "Sốt cao, đau sưng hầu họng, hôn mê, trúng phong cấp cứu" },

// --- KINH THỦ DƯƠNG MINH ĐẠI TRƯỜNG (20 huyệt) ---
{ stt: 12, ma_who: "LI1", kinh: "Kinh Đại Trường", ten: "Thương Dương", vi_tri: "Bờ ngoài ngón tay trỏ, cách gốc móng 0.1 thốn về phía xương quay", chu_tri: "Sốt cao, đau họng, đau răng hàm dưới, tê dại ngón tay" },
{ stt: 13, ma_who: "LI2", kinh: "Kinh Đại Trường", ten: "Nhị Gian", vi_tri: "Chỗ lõm phía trước khớp bàn - ngón tay trỏ, bờ ngoài phía xương quay", chu_tri: "Đau răng, đau họng, sốt, lệch miệng, đau mắt" },
{ stt: 14, ma_who: "LI3", kinh: "Kinh Đại Trường", ten: "Tam Gian", vi_tri: "Chỗ lõm phía sau khớp bàn - ngón tay trỏ, bờ ngoài phía xương quay", chu_tri: "Đau mắt đỏ, đau răng, sưng họng, trướng bụng, đau mu bàn tay" },
{ stt: 15, ma_who: "LI4", kinh: "Kinh Đại Trường", ten: "Hợp Cốc", vi_tri: "Mu bàn tay, điểm giữa bờ ngoài xương đốt bàn ngón tay thứ hai", chu_tri: "Đau đầu, đau răng, sốt, liệt mặt, bế kinh, đau chi trên" },
{ stt: 16, ma_who: "LI5", kinh: "Kinh Đại Trường", ten: "Dương Khê", vi_tri: "Tại cổ tay, chỗ lõm giữa gân cơ duỗi ngắn và duỗi dài ngón cái (hõm nách giải phẫu)", chu_tri: "Đau đầu, đau răng, mắt đỏ sưng đau, đau khớp cổ tay" },
{ stt: 17, ma_who: "LI6", kinh: "Kinh Đại Trường", ten: "Thiên Lịch", vi_tri: "Mặt sau cẳng tay, trên đường nối Dương Khê - Khúc Trì, cách Dương Khê 3 thốn", chu_tri: "Chảy máu cam, ù tai, điếc tai, phù thũng, đau cẳng tay" },
{ stt: 18, ma_who: "LI7", kinh: "Kinh Đại Trường", ten: "Ôn Lưu", vi_tri: "Mặt sau cẳng tay, trên đường nối Dương Khê - Khúc Trì, cách Dương Khê 5 thốn", chu_tri: "Đau bụng quặn, sưng họng, đau vai cẳng tay, động kinh" },
{ stt: 19, ma_who: "LI8", kinh: "Kinh Đại Trường", ten: "Hạ Liêm", vi_tri: "Mặt sau cẳng tay, trên đường nối Dương Khê - Khúc Trì, dưới Khúc Trì 4 thốn", chu_tri: "Đau bụng trướng, đau khuỷu tay và cẳng tay, sưng vú" },
{ stt: 20, ma_who: "LI9", kinh: "Kinh Đại Trường", ten: "Thượng Liêm", vi_tri: "Mặt sau cẳng tay, trên đường nối Dương Khê - Khúc Trì, dưới Khúc Trì 3 thốn", chu_tri: "Đau cẳng tay, tê tay, đau bụng quanh rốn, tiêu chảy" },
{ stt: 21, ma_who: "LI10", kinh: "Kinh Đại Trường", ten: "Thủ Tam Lý", vi_tri: "Mặt sau cẳng tay, trên đường nối Dương Khê - Khúc Trì, dưới Khúc Trì 2 thốn", chu_tri: "Đau bụng, tiêu chảy, liệt chi trên, đau vai và khuỷu tay" },
{ stt: 22, ma_who: "LI11", kinh: "Kinh Đại Trường", ten: "Khúc Trì", vi_tri: "Chỗ lõm nếp gấp khuỷu tay khi co tay vuông góc, tận cùng bờ ngoài nếp gấp khuỷu", chu_tri: "Sốt cao, tăng huyết áp, dị ứng ngoài da, đau liệt chi trên" },
{ stt: 23, ma_who: "LI12", kinh: "Kinh Đại Trường", ten: "Trử Liêu", vi_tri: "Phía trên lồi cầu ngoài xương cánh tay, bờ ngoài cơ tam đầu cánh tay, trên Khúc Trì 1 thốn", chu_tri: "Đau khuỷu tay, tê dại cánh tay, co rút khớp khuỷu" },
{ stt: 24, ma_who: "LI13", kinh: "Kinh Đại Trường", ten: "Thủ Ngũ Lý", vi_tri: "Mặt ngoài cánh tay, trên đường nối Khúc Trì - Kiên Ngung, trên Khúc Trì 3 thốn", chu_tri: "Đau co rút cánh tay, lao hạch cổ, trướng bụng, ho" },
{ stt: 25, ma_who: "LI14", kinh: "Kinh Đại Trường", ten: "Tý Nhu", vi_tri: "Mặt ngoài cánh tay, đầu dưới cơ delta, trên đường nối Khúc Trì - Kiên Ngung", chu_tri: "Đau vai cẳng tay, cổ cứng gáy, đau mắt, giảm thị lực" },
{ stt: 26, ma_who: "LI15", kinh: "Kinh Đại Trường", ten: "Kiên Ngung", vi_tri: "Chỗ lõm phía trước dưới mỏm cùng vai khi dang cánh tay ngang", chu_tri: "Đau viêm khớp vai, liệt chi trên, đau vùng cổ gáy" },
{ stt: 27, ma_who: "LI16", kinh: "Kinh Đại Trường", ten: "Cự Cốt", vi_tri: "Mặt trên vai, chỗ lõm giữa đầu ngoài xương đòn và gai xương bả vai", chu_tri: "Đau vai gáy, hạn chế vận động khớp vai, lao hạch cổ" },
{ stt: 28, ma_who: "LI17", kinh: "Kinh Đại Trường", ten: "Thiên Đỉnh", vi_tri: "Vùng cổ, bờ sau cơ ức đòn chũm, ngang mức bờ dưới sụn nhẫn", chu_tri: "Đau họng, khàn tiếng, nuốt vướng, lao hạch cổ" },
{ stt: 29, ma_who: "LI18", kinh: "Kinh Đại Trường", ten: "Phù Đột", vi_tri: "Vùng cổ, ngang bờ trên sụn giáp, giữa hai đầu cơ ức đòn chũm", chu_tri: "Ho suyễn, đau hầu họng, nuốt vướng, khàn tiếng" },
{ stt: 30, ma_who: "LI19", kinh: "Kinh Đại Trường", ten: "Hòa Liêu", vi_tri: "Vùng mặt, dưới mép ngoài lỗ mũi, ngang hàng với huyệt Nhân Trung (GV26)", chu_tri: "Nghẹt mũi, chảy máu cam, liệt mặt, méo miệng" },
{ stt: 31, ma_who: "LI20", kinh: "Kinh Đại Trường", ten: "Nghinh Hương", vi_tri: "Rãnh mũi - má, ngang bờ ngoài chân cánh mũi", chu_tri: "Nghẹt mũi, viêm mũi dị ứng, liệt mặt, chảy máu cam" },

    // --- KINH TÚC DƯƠNG MINH VỊ (45 huyệt) ---
    { stt: 32, ma_who: "ST1", kinh: "Kinh Vị", ten: "Thừa Khấp", vi_tri: "Vùng mặt, giữa mi mắt dưới thẳng xuống, sát bờ dưới hốc mắt", chu_tri: "Viêm kết mạc, liệt mặt, cận thị, giật cơ mi mắt" },
    { stt: 32, ma_who: "ST2", kinh: "Kinh Vị", ten: "Tứ Bạch", vi_tri: "Vùng mặt, dưới hốc mắt thẳng xuống 0.7 thốn, tại lỗ dưới hốc mắt", chu_tri: "Đau mắt đỏ, giật mi mắt, liệt mặt, đau dây thần kinh V" },
    { stt: 33, ma_who: "ST3", kinh: "Kinh Vị", ten: "Cự Liêu", vi_tri: "Vùng mặt, thẳng từ đồng tử mắt xuống, ngang chân cánh mũi", chu_tri: "Liệt mặt, giật mi mắt, đau răng hàm trên, sưng má" },
    { stt: 34, ma_who: "ST4", kinh: "Kinh Vị", ten: "Địa Thương", vi_tri: "Vùng mặt, cách khóe miệng 0.4 thốn về phía ngoài", chu_tri: "Liệt mặt, méo miệng, đau dây thần kinh V, chảy dãi" },
    { stt: 35, ma_who: "ST5", kinh: "Kinh Vị", ten: "Đại Nghênh", vi_tri: "Trước góc hàm 1.3 thốn, chỗ lõm bờ trước cơ cắn khi cắn chặt răng", chu_tri: "Cứng hàm, đau răng, sưng má, méo miệng" },
    { stt: 36, ma_who: "ST6", kinh: "Kinh Vị", ten: "Giáp Xa", vi_tri: "Phía trên trước góc hàm, chỗ cơ cắn nổi lên cao nhất khi cắn chặt răng", chu_tri: "Liệt mặt, đau răng hàm dưới, quai bị, trơ cứng hàm" },
    { stt: 37, ma_who: "ST7", kinh: "Kinh Vị", ten: "Hạ Quan", vi_tri: "Chỗ lõm phía dưới xương gò má, phía trước khuyết tai", chu_tri: "Đau tai, đau răng, viêm khớp thái dương hàm, liệt mặt" },
    { stt: 38, ma_who: "ST8", kinh: "Kinh Vị", ten: "Đầu Duy", vi_tri: "Góc tóc trán, cách mép tóc trán 0.5 thốn, trên đường nối Đầu Duy - Thần Đình", chu_tri: "Đau đầu, đau nửa đầu, đau nhức mắt, chóng mặt" },
    { stt: 39, ma_who: "ST9", kinh: "Kinh Vị", ten: "Nhân Nghênh", vi_tri: "Bên cổ, ngang bờ trên sụn giáp, bờ trước cơ ức đòn chũm (sát động mạch cảnh)", chu_tri: "Tăng huyết áp, hen suyễn, đau hầu họng, mất tiếng" },
    { stt: 40, ma_who: "ST10", kinh: "Kinh Vị", ten: "Thủy Đột", vi_tri: "Bên cổ, bờ trước cơ ức đòn chũm, giữa Phù Đột (LI17) và Khí Xá (ST11)", chu_tri: "Đau họng, ho suyễn, bướu cổ đơn thuần" },
    { stt: 41, ma_who: "ST11", kinh: "Kinh Vị", ten: "Khí Xá", vi_tri: "Bờ trên xương đòn, giữa đầu chũm và đầu ức của cơ ức đòn chũm", chu_tri: "Đau họng, nuốt vướng, ho suyễn, vẹo cổ" },
    { stt: 42, ma_who: "ST12", kinh: "Kinh Vị", ten: "Khuyết Bồn", vi_tri: "Chỗ lõm bờ trên xương đòn, thẳng hàng núm vú, cách đường giữa 4 thốn", chu_tri: "Ho, hen suyễn, đau tức ngực sườn, sưng hạch cổ" },
    { stt: 43, ma_who: "ST13", kinh: "Kinh Vị", ten: "Khí Hộ", vi_tri: "Thành ngực trước, dưới xương đòn, cách đường giữa ngực 4 thốn", chu_tri: "Ho, hen suyễn, đau ngực sườn, nấc cục" },
    { stt: 44, ma_who: "ST14", kinh: "Kinh Vị", ten: "Khố Phòng", vi_tri: "Khoang liên sườn 1, cách đường giữa ngực 4 thốn", chu_tri: "Ho suyễn, đau tức ngực, khạc ra đờm mủ" },
    { stt: 45, ma_who: "ST15", kinh: "Kinh Vị", ten: "Ốc Ế", vi_tri: "Khoang liên sườn 2, cách đường giữa ngực 4 thốn", chu_tri: "Ho suyễn, đau tức ngực, viêm tuyến vú" },
    { stt: 46, ma_who: "ST16", kinh: "Kinh Vị", ten: "Ưng Cụ", vi_tri: "Khoang liên sườn 3, cách đường giữa ngực 4 thốn", chu_tri: "Đau ngực sườn, ho suyễn, sưng đau vú" },
    { stt: 47, ma_who: "ST17", kinh: "Kinh Vị", ten: "Nhũ Trung", vi_tri: "Chính giữa núm vú (Dùng làm mốc đo giải phẫu, cấm châm cứu)", chu_tri: "Dùng làm mốc định vị giải phẫu vùng ngực" },
    { stt: 48, ma_who: "ST18", kinh: "Kinh Vị", ten: "Nhũ Căn", vi_tri: "Khoang liên sườn 5, thẳng dưới núm vú, cách đường giữa ngực 4 thốn", chu_tri: "Viêm tuyến vú, tắc sữa, đau tức ngực, ho suyễn" },
    { stt: 49, ma_who: "ST19", kinh: "Kinh Vị", ten: "Bất Dung", vi_tri: "Trên rốn 6 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau thượng vị, nôn mửa, chán ăn, trướng bụng" },
    { stt: 50, ma_who: "ST20", kinh: "Kinh Vị", ten: "Thừa Mãn", vi_tri: "Trên rốn 5 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau dạ dày, ợ chua, trướng bụng, nôn mửa" },
    { stt: 51, ma_who: "ST21", kinh: "Kinh Vị", ten: "Lương Môn", vi_tri: "Trên rốn 4 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau dạ dày, nôn mửa, tiêu chảy, chán ăn" },
    { stt: 52, ma_who: "ST22", kinh: "Kinh Vị", ten: "Quan Môn", vi_tri: "Trên rốn 3 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Bụng trướng đau, đau dạ dày, tiêu chảy" },
    { stt: 53, ma_who: "ST23", kinh: "Kinh Vị", ten: "Thái Ất", vi_tri: "Trên rốn 2 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau dạ dày, an thần, cuồng điên, trướng bụng" },
    { stt: 54, ma_who: "ST24", kinh: "Kinh Vị", ten: "Hoạt Nhục Môn", vi_tri: "Trên rốn 1 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau dạ dày, nôn mửa, lưỡi cứng, cuồng điên" },
    { stt: 55, ma_who: "ST25", kinh: "Kinh Vị", ten: "Thiên Khu", vi_tri: "Ngang hàng với rốn, cách rốn 2 thốn về hai bên", chu_tri: "Đau bụng, táo bón, tiêu chảy, kiết lỵ, rối loạn tiêu hóa" },
    { stt: 56, ma_who: "ST26", kinh: "Kinh Vị", ten: "Ngoại Lăng", vi_tri: "Dưới rốn 1 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau bụng dưới, thoát vị bẹn, đau kinh nguyệt" },
    { stt: 57, ma_who: "ST27", kinh: "Kinh Vị", ten: "Đại Cự", vi_tri: "Dưới rốn 2 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Bí tiểu, đau bụng dưới, di tinh, liệt dương" },
    { stt: 58, ma_who: "ST28", kinh: "Kinh Vị", ten: "Thủy Đạo", vi_tri: "Dưới rốn 3 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Phù thũng, bí tiểu, đau bụng dưới, viêm tinh hoàn" },
    { stt: 59, ma_who: "ST29", kinh: "Kinh Vị", ten: "Quy Lai", vi_tri: "Dưới rốn 4 thốn, cách đường giữa bụng 2 thốn", chu_tri: "Đau bụng kinh, sa tử cung, thoát vị bẹn, di tinh" },
    { stt: 60, ma_who: "ST30", kinh: "Kinh Vị", ten: "Khí Xung", vi_tri: "Dưới rốn 5 thốn (bờ trên xương mu), cách đường giữa bụng 2 thốn", chu_tri: "Đau sưng cơ quan sinh dục, kinh nguyệt không đều, thoát vị bẹn" },
    { stt: 61, ma_who: "ST31", kinh: "Kinh Vị", ten: "Bễ Quan", vi_tri: "Mặt trước đùi, chỗ lõm giao điểm đường ngang nếp bẹn và đường dọc qua gai chậu trước trên", chu_tri: "Liệt chi dưới, đau khớp háng, đau gối" },
    { stt: 62, ma_who: "ST32", kinh: "Kinh Vị", ten: "Phục Thỏ", vi_tri: "Mặt trước đùi, trên đường nối gai chậu trước trên với bờ ngoài xương bánh chè, trên bờ trên xương bánh chè 6 thốn", chu_tri: "Liệt chi dưới, đau đùi, đau gối, thoát vị" },
    { stt: 63, ma_who: "ST33", kinh: "Kinh Vị", ten: "Âm Thị", vi_tri: "Mặt trước đùi, trên đường nối gai chậu trước trên với bờ ngoài xương bánh chè, trên bờ trên ngoài xương bánh chè 3 thốn", chu_tri: "Liệt chân, đau gối, lạnh gối, hạn chế vận động đùi" },
    { stt: 64, ma_who: "ST34", kinh: "Kinh Vị", ten: "Lương Khâu", vi_tri: "Mặt trước ngoài đùi, trên bờ trên ngoài xương bánh chè 2 thốn", chu_tri: "Đau dạ dày cấp tính, viêm tuyến vú, đau sưng khớp gối" },
    { stt: 65, ma_who: "ST35", kinh: "Kinh Vị", ten: "Độc Tỵ", vi_tri: "Chỗ lõm bờ dưới ngoài xương bánh chè (mắt gối ngoài)", chu_tri: "Đau sưng khớp gối, hạn chế vận động chi dưới" },
    { stt: 66, ma_who: "ST36", kinh: "Kinh Vị", ten: "Túc Tam Lý", vi_tri: "Dưới Độc Tỵ (ST35) 3 thốn, cách mào trước xương chày 1 khoát ngón tay", chu_tri: "Đau dạ dày, tiêu hóa kém, suy nhược cơ thể, tăng cường miễn dịch" },
    { stt: 67, ma_who: "ST37", kinh: "Kinh Vị", ten: "Thượng Cự Hư", vi_tri: "Dưới Túc Tam Lý (ST36) 3 thốn, cách mào trước xương chày 1 khoát ngón tay", chu_tri: "Đau bụng trướng, tiêu chảy, viêm ruột thừa, liệt chi dưới" },
    { stt: 68, ma_who: "ST38", kinh: "Kinh Vị", ten: "Điều Khẩu", vi_tri: "Dưới Túc Tam Lý (ST36) 5 thốn, cách mào trước xương chày 1 khoát ngón tay", chu_tri: "Liệt chi dưới, đau cổ chân, đau cứng vai (kiên ngung)" },
    { stt: 69, ma_who: "ST39", kinh: "Kinh Vị", ten: "Hạ Cự Hư", vi_tri: "Dưới Thượng Cự Hư (ST37) 3 thốn, cách mào trước xương chày 1 khoát ngón tay", chu_tri: "Đau bụng dưới, tiêu chảy, đau ngực vú, liệt chân" },
    { stt: 70, ma_who: "ST40", kinh: "Kinh Vị", ten: "Phong Long", vi_tri: "Mặt ngoài cẳng chân, đỉnh mắt cá ngoài đo lên 8 thốn, cách bờ trước xương chày 2 khoát ngón tay", chu_tri: "Hóa đờm trị ho, đau đầu, chóng mặt, liệt chi dưới" },
    { stt: 71, ma_who: "ST41", kinh: "Kinh Vị", ten: "Giải Khê", vi_tri: "Chính giữa nếp gấp cổ chân, chỗ lõm giữa gân cơ duỗi dài ngón chân và duỗi dài ngón cái", chu_tri: "Đau khớp cổ chân, đau đầu, trướng bụng, đại tiện khó" },
    { stt: 72, ma_who: "ST42", kinh: "Kinh Vị", ten: "Xung Dương", vi_tri: "Mu bàn chân, chỗ cao nhất mu chân, sát động mạch mu chân đập", chu_tri: "Đau mu bàn chân, liệt mặt, đau răng, đau dạ dày" },
    { stt: 73, ma_who: "ST43", kinh: "Kinh Vị", ten: "Hãm Cốc", vi_tri: "Mu bàn chân, chỗ lõm giữa xương bàn ngón chân 2 và 3, phía sau khớp bàn - ngón", chu_tri: "Phù mặt, đau bụng, sốt không ra mồ hôi, đau sưng mu chân" },
    { stt: 74, ma_who: "ST44", kinh: "Kinh Vị", ten: "Nội Đình", vi_tri: "Mu bàn chân, kẽ giữa ngón chân 2 và 3 đo lên 0.5 thốn", chu_tri: "Đau răng, đau sưng họng, sốt, chảy máu cam, đau dạ dày" },
    { stt: 75, ma_who: "ST45", kinh: "Kinh Vị", ten: "Lệ Đoài", vi_tri: "Bờ ngoài ngón chân thứ 2, cách gốc móng chân 0.1 thốn", chu_tri: "Sốt cao, đau răng, mất ngủ, hay mơ, cuồng điên" },

    // --- KINH TÚC THÁI ÂM TỲ (21 huyệt) ---
    { stt: 76, ma_who: "SP1", kinh: "Kinh Tỳ", ten: "Ẩn Bạch", vi_tri: "Bờ trong ngón chân cái, cách góc móng chân 0.1 thốn", chu_tri: "Băng lậu, rong kinh, đau bụng trướng, cuồng điên" },
    { stt: 77, ma_who: "SP2", kinh: "Kinh Tỳ", ten: "Đại Đô", vi_tri: "Bờ trong bàn chân, chỗ lõm phía trước khớp bàn - ngón chân cái, ranh giới da mu - lòng bàn chân", chu_tri: "Trướng bụng, đau dạ dày, sốt không ra mồ hôi, nôn mửa" },
    { stt: 78, ma_who: "SP3", kinh: "Kinh Tỳ", ten: "Thái Bạch", vi_tri: "Bờ trong bàn chân, chỗ lõm phía sau đầu xương đốt bàn ngón chân 1", chu_tri: "Đau dạ dày, trướng bụng, tiêu chảy, nôn mửa" },
    { stt: 79, ma_who: "SP4", kinh: "Kinh Tỳ", ten: "Công Tôn", vi_tri: "Bờ trong bàn chân, chỗ lõm sau đầu gần xương đốt bàn ngón chân 1", chu_tri: "Đau bụng cấp, nôn mửa, viêm dạ dày ruột, đau vùng tim" },
    { stt: 80, ma_who: "SP5", kinh: "Kinh Tỳ", ten: "Thương Khâu", vi_tri: "Chỗ lõm phía trước dưới mắt cá trong chân", chu_tri: "Trướng bụng, tiêu chảy, đau cổ chân, lưỡi cứng đau" },
    { stt: 81, ma_who: "SP6", kinh: "Kinh Tỳ", ten: "Tam Âm Giao", vi_tri: "Từ đỉnh mắt cá trong đo lên 3 thốn, sát bờ sau xương chày", chu_tri: "Mất ngủ, kinh nguyệt không đều, di tinh, bí tiểu, tiêu chảy" },
    { stt: 82, ma_who: "SP7", kinh: "Kinh Tỳ", ten: "Lậu Cốc", vi_tri: "Từ đỉnh mắt cá trong đo lên 6 thốn, sát bờ sau xương chày", chu_tri: "Trướng bụng, phù thũng, tiểu khó, lạnh chi dưới" },
    { stt: 83, ma_who: "SP8", kinh: "Kinh Tỳ", ten: "Địa Cơ", vi_tri: "Dưới Âm Lăng Tuyền (SP9) 3 thốn, sát bờ sau xương chày", chu_tri: "Đau bụng kinh, kinh nguyệt không đều, di tinh, tiêu chảy" },
    { stt: 84, ma_who: "SP9", kinh: "Kinh Tỳ", ten: "Âm Lăng Tuyền", vi_tri: "Chỗ lõm dưới lồi cầu trong xương chày, mặt trong bắp chân", chu_tri: "Phù thũng, bí tiểu, đau sưng khớp gối, di tinh" },
    { stt: 85, ma_who: "SP10", kinh: "Kinh Tỳ", ten: "Huyết Hải", vi_tri: "Mặt trước trong đùi, từ góc trên trong xương bánh chè đo lên 2 thốn", chu_tri: "Kinh nguyệt không đều, mề đay, mẩn ngứa, thiếu máu, ngứa da" },
    { stt: 86, ma_who: "SP11", kinh: "Kinh Tỳ", ten: "Cơ Môn", vi_tri: "Mặt trong đùi, trên đường nối Huyết Hải - Xung Môn, trên Huyết Hải 6 thốn", chu_tri: "Bí tiểu, đái dầm, sưng đau vùng bẹn" },
    { stt: 87, ma_who: "SP12", kinh: "Kinh Tỳ", ten: "Xung Môn", vi_tri: "Chính giữa nếp gấp bẹn, phía ngoài động mạch đùi", chu_tri: "Đau bụng dưới, thoát vị bẹn, bí tiểu, khí hư" },
    { stt: 88, ma_who: "SP13", kinh: "Kinh Tỳ", ten: "Phủ Xá", vi_tri: "Dưới bụng, trên Xung Môn (SP12) 0.7 thốn, cách đường giữa bụng 4 thốn", chu_tri: "Đau bụng quặn, thoát vị bẹn, đau trĩ" },
    { stt: 89, ma_who: "SP14", kinh: "Kinh Tỳ", ten: "Phúc Kết", vi_tri: "Dưới Đại Hoành (SP15) 1.3 thốn, cách đường giữa bụng 4 thốn", chu_tri: "Đau bụng quanh rốn, tiêu chảy, thoát vị" },
    { stt: 90, ma_who: "SP15", kinh: "Kinh Tỳ", ten: "Đại Hoành", vi_tri: "Ngang hàng với rốn, cách rốn 4 thốn về phía ngoài", chu_tri: "Táo bón lâu ngày, tiêu chảy, đau bụng dưới" },
    { stt: 91, ma_who: "SP16", kinh: "Kinh Tỳ", ten: "Phúc Ai", vi_tri: "Trên Đại Hoành (SP15) 3 thốn, cách đường giữa bụng 4 thốn", chu_tri: "Đau bụng, tiêu chảy, táo bón, ăn không tiêu" },
    { stt: 92, ma_who: "SP17", kinh: "Kinh Tỳ", ten: "Thực Đậu", vi_tri: "Khoang liên sườn 5, cách đường giữa ngực 6 thốn", chu_tri: "Đau trướng ngực sườn, ợ chua, nôn mửa" },
    { stt: 93, ma_who: "SP18", kinh: "Kinh Tỳ", ten: "Thiên Khê", vi_tri: "Khoang liên sườn 4, cách đường giữa ngực 6 thốn", chu_tri: "Ho suyễn, đau ngực sườn, thiếu sữa, viêm tuyến vú" },
    { stt: 94, ma_who: "SP19", kinh: "Kinh Tỳ", ten: "Hung Hương", vi_tri: "Khoang liên sườn 3, cách đường giữa ngực 6 thốn", chu_tri: "Đau ngực sườn, ho suyễn, không xoay người được" },
    { stt: 95, ma_who: "SP20", kinh: "Kinh Tỳ", ten: "Chu Vinh", vi_tri: "Khoang liên sườn 2, cách đường giữa ngực 6 thốn", chu_tri: "Ho suyễn, đau tức ngực, nuốt vướng" },
    { stt: 96, ma_who: "SP21", kinh: "Kinh Tỳ", ten: "Đại Bao", vi_tri: "Khoang liên sườn 6, trên đường nách giữa", chu_tri: "Đau tức ngực sườn, suy nhược toàn thân, hen suyễn" },

    // --- KINH THỦ THÁI ÂM TÂM (9 huyệt) ---
    { stt: 97, ma_who: "HT1", kinh: "Kinh Tâm", ten: "Cực Tuyền", vi_tri: "Chính giữa hố nách, sát bờ trong động mạch nách", chu_tri: "Đau vùng tim, hồi hộp, đau thắt ngực, liệt chi trên" },
    { stt: 98, ma_who: "HT2", kinh: "Kinh Tâm", ten: "Thanh Linh", vi_tri: "Mặt trong cánh tay, trên đường nối Cực Tuyền - Thiếu Hải, trên Thiếu Hải 3 thốn", chu_tri: "Đau tim, đau cánh tay, mắt vàng, đau ngực sườn" },
    { stt: 99, ma_who: "HT3", kinh: "Kinh Tâm", ten: "Thiếu Hải", vi_tri: "Co khuỷu tay, chỗ lõm giữa đầu trong nếp gấp khuỷu và lồi cầu trong xương cánh tay", chu_tri: "Đau vùng tim, tê tay, run tay, lao hạch cổ" },
    { stt: 100, ma_who: "HT4", kinh: "Kinh Tâm", ten: "Linh Đạo", vi_tri: "Mặt trước cẳng tay, trên nếp cổ tay 1.5 thốn, sát bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Đau vùng tim, mất tiếng đột ngột, co rút cẳng tay" },
    { stt: 101, ma_who: "HT5", kinh: "Kinh Tâm", ten: "Thông Lý", vi_tri: "Mặt trước cẳng tay, trên nếp cổ tay 1 thốn, sát bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Hồi hộp, mất tiếng, lưỡi cứng khó nói, đau cổ tay" },
    { stt: 102, ma_who: "HT6", kinh: "Kinh Tâm", ten: "Âm Khích", vi_tri: "Mặt trước cẳng tay, trên nếp cổ tay 0.5 thốn, sát bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Đau tim, ra mồ hôi trộm, nôn ra máu, chảy máu cam" },
    { stt: 103, ma_who: "HT7", kinh: "Kinh Tâm", ten: "Thần Môn", vi_tri: "Tại nếp cổ tay, chỗ lõm bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Mất ngủ, hồi hộp, suy giảm trí nhớ, cuồng điên, đau tim" },
    { stt: 104, ma_who: "HT8", kinh: "Kinh Tâm", ten: "Thiếu Phủ", vi_tri: "Lòng bàn tay, giữa xương bàn ngón tay 4 và 5 (nơi đầu ngón út chạm vào khi nắm tay)", chu_tri: "Hồi hộp, đau tim, tiểu khó, ngứa bộ phận sinh dục" },
    { stt: 105, ma_who: "HT9", kinh: "Kinh Tâm", ten: "Thiếu Xung", vi_tri: "Bờ ngoài ngón tay út, cách gốc móng tay 0.1 thốn về phía xương quay", chu_tri: "Trúng phong hôn mê, sốt cao, hồi hộp, đau ngực" },

    // --- KINH THỦ THÁI DƯƠNG TIỂU TRƯỜNG (19 huyệt) ---
    { stt: 106, ma_who: "SI1", kinh: "Kinh Tiểu Trường", ten: "Thiếu Trạch", vi_tri: "Bờ ngoài ngón tay út, cách gốc móng tay 0.1 thốn về phía xương trụ", chu_tri: "Sốt cao, tắc sữa, đau đầu, đau mắt đỏ" },
    { stt: 107, ma_who: "SI2", kinh: "Kinh Tiểu Trường", ten: "Tiền Cốc", vi_tri: "Chỗ lõm phía trước khớp bàn - ngón tay thứ 5, bờ ngoài phía xương trụ", chu_tri: "Sốt không ra mồ hôi, tắc sữa, đau đầu, ù tai" },
    { stt: 108, ma_who: "SI3", kinh: "Kinh Tiểu Trường", ten: "Hậu Khê", vi_tri: "Chỗ lõm phía sau khớp bàn - ngón tay thứ 5 khi nắm nhẹ tay", chu_tri: "Đau cổ gáy, ù tai, động kinh, ra mồ hôi trộm, đau lưng" },
    { stt: 109, ma_who: "SI4", kinh: "Kinh Tiểu Trường", ten: "Uyển Cốt", vi_tri: "Bờ ngoài mu bàn tay, chỗ lõm giữa xương bàn ngón 5 và xương tháp", chu_tri: "Đau khớp cổ tay, vàng da, sốt không ra mồ hôi" },
    { stt: 110, ma_who: "SI5", kinh: "Kinh Tiểu Trường", ten: "Dương Cốc", vi_tri: "Chỗ lõm sát bờ ngoài cổ tay, giữa mỏm trâm xương trụ và xương tháp", chu_tri: "Đau cổ tay, sưng họng, ù tai, sốt cao" },
    { stt: 111, ma_who: "SI6", kinh: "Kinh Tiểu Trường", ten: "Dưỡng Lão", vi_tri: "Chỗ lõm phía trên mỏm trâm xương trụ khi xoay sấp cẳng tay", chu_tri: "Suy giảm thị lực, đau vai cẳng tay, đau thắt lưng" },
    { stt: 112, ma_who: "SI7", kinh: "Kinh Tiểu Trường", ten: "Chi Chánh", vi_tri: "Mặt sau cẳng tay, trên đường nối Dương Cốc - Tiểu Hải, cách Dương Cốc 5 thốn", chu_tri: "Cổ cứng gáy, đau khuỷu tay, cuồng điên, mụn nhọt ngoài da" },
    { stt: 113, ma_who: "SI8", kinh: "Kinh Tiểu Trường", ten: "Tiểu Hải", vi_tri: "Mặt sau khuỷu tay, chỗ lõm giữa mỏm khuỷu xương trụ và mỏm trên lồi cầu trong xương cánh tay", chu_tri: "Đau khớp khuỷu, đau vai gáy, điên cuồng, sưng má" },
    { stt: 114, ma_who: "SI9", kinh: "Kinh Tiểu Trường", ten: "Kiên Trinh", vi_tri: "Mặt sau khớp vai, thẳng từ nếp gấp nách sau lên 1 thốn khi khép tay", chu_tri: "Đau khớp vai, liệt chi trên, đau vùng bả vai" },
    { stt: 115, ma_who: "SI10", kinh: "Kinh Tiểu Trường", ten: "Nhu Du", vi_tri: "Mặt sau vai, thẳng nếp nách sau lên, dưới bờ dưới gai xương bả vai", chu_tri: "Đau bả vai, yếu lực cẳng tay, sưng đau cổ" },
    { stt: 116, ma_who: "SI11", kinh: "Kinh Tiểu Trường", ten: "Thiên Tông", vi_tri: "Chính giữa hố dưới gai xương bả vai (điểm tạo với huyệt Kiên Trinh và Nhu Du thành tam giác đều)", chu_tri: "Đau bả vai, đau cánh tay, viêm tuyến vú, tắc sữa" },
    { stt: 117, ma_who: "SI12", kinh: "Kinh Tiểu Trường", ten: "Bỉnh Phong", vi_tri: "Mặt sau vai, chính giữa hố trên gai xương bả vai", chu_tri: "Đau bả vai, tê dại vai cẳng tay, hạn chế giơ tay" },
    { stt: 118, ma_who: "SI13", kinh: "Kinh Tiểu Trường", ten: "Khúc Viên", vi_tri: "Mặt sau vai, chỗ lõm bờ trên trong hố trên gai xương bả vai", chu_tri: "Đau nhức bả vai, cứng đau cổ gáy" },
    { stt: 119, ma_who: "SI14", kinh: "Kinh Tiểu Trường", ten: "Kiên Ngoại Du", vi_tri: "Vùng lưng trên, dưới gai đốt sống ngực 1 (T1) đo ngang ra 3 thốn", chu_tri: "Đau vai gáy, cứng cổ, liệt chi trên" },
    { stt: 120, ma_who: "SI15", kinh: "Kinh Tiểu Trường", ten: "Kiên Trung Du", vi_tri: "Vùng gáy dưới, dưới gai đốt sống cổ 7 (C7 - Đại Chùy) đo ngang ra 2 thốn", chu_tri: "Đau vai gáy, ho suyễn, giảm thị lực" },
    { stt: 121, ma_who: "SI16", kinh: "Kinh Tiểu Trường", ten: "Thiên Song", vi_tri: "Vùng cổ, bờ sau cơ ức đòn chũm, ngang mức sụn giáp", chu_tri: "Ù tai, điếc tai, sưng hầu họng, cổ cứng đau" },
    { stt: 122, ma_who: "SI17", kinh: "Kinh Tiểu Trường", ten: "Thiên Dung", vi_tri: "Vùng cổ, phía sau góc hàm dưới, bờ trước cơ ức đòn chũm", chu_tri: "Sưng đau hầu họng, ù tai, sưng cổ, nghẹn cổ" },
    { stt: 123, ma_who: "SI18", kinh: "Kinh Tiểu Trường", ten: "Quyền Liêu", vi_tri: "Vùng mặt, thẳng dưới khóe mắt ngoài, chỗ lõm bờ dưới xương gò má", chu_tri: "Liệt mặt, đau răng, giật cơ mi mắt, mắt vàng" },
    { stt: 124, ma_who: "SI19", kinh: "Kinh Tiểu Trường", ten: "Thính Cung", vi_tri: "Vùng mặt, chỗ lõm giữa bình tai và khớp thái dương hàm (khi há miệng)", chu_tri: "Ù tai, điếc tai, đau tai, viêm tai giữa" }
];
// === ĐỢT 2: KINH BÀNG QUANG, THẬN, TÂM BÀO, TAM TIÊU (STT 125 - 249) ===
window.huyetViDataBatch2 = [
    // --- KINH TÚC THÁI DƯƠNG BÀNG QUANG (67 huyệt) ---
    { stt: 125, ma_who: "BL1", kinh: "Kinh Bàng Quang", ten: "Tình Minh", vi_tri: "Cách khóe mắt trong 0.1 thốn về phía mũi", chu_tri: "Cận thị, chảy nước mắt khi ra gió, viêm màng tiếp hợp" },
    { stt: 126, ma_who: "BL2", kinh: "Kinh Bàng Quang", ten: "Toản Trúc", vi_tri: "Chỗ lõm đầu trong chân mày thẳng lên", chu_tri: "Đau đầu, đau mắt, giật cơ mắt, liệt mặt" },
    { stt: 127, ma_who: "BL3", kinh: "Kinh Bàng Quang", ten: "Mông Xung", vi_tri: "Sau Thần Đình 0.5 thốn, cách đường giữa đầu 0.5 thốn", chu_tri: "Đau đầu, nghẹt mũi, co giật, mờ mắt" },
    { stt: 128, ma_who: "BL4", kinh: "Kinh Bàng Quang", ten: "Khúc Sai", vi_tri: "Trên mép tóc trán 0.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, nghẹt mũi, chảy máu cam, giảm thị lực" },
    { stt: 129, ma_who: "BL5", kinh: "Kinh Bàng Quang", ten: "Ngũ Xứ", vi_tri: "Sau Khúc Sai 0.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đỉnh đầu, chóng mặt, động kinh, mờ mắt" },
    { stt: 130, ma_who: "BL6", kinh: "Kinh Bàng Quang", ten: "Thừa Quang", vi_tri: "Sau Ngũ Xứ 1.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, nghẹt mũi, mờ mắt" },
    { stt: 131, ma_who: "BL7", kinh: "Kinh Bàng Quang", ten: "Thông Thiên", vi_tri: "Sau Thừa Quang 1.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, nghẹt mũi, chảy máu cam" },
    { stt: 132, ma_who: "BL8", kinh: "Kinh Bàng Quang", ten: "Lạc Khước", vi_tri: "Sau Thông Thiên 1.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, điên cuồng, ù tai" },
    { stt: 133, ma_who: "BL9", kinh: "Kinh Bàng Quang", ten: "Ngọc Chẩm", vi_tri: "Ngang bờ trên u chẩm ngoài, cách đường giữa đầu 1.3 thốn", chu_tri: "Đau sau đầu, nghẹt mũi, đau mắt, chóng mặt" },
    { stt: 134, ma_who: "BL10", kinh: "Kinh Bàng Quang", ten: "Thiên Trụ", vi_tri: "Vùng tóc gáy, dưới u chẩm, ngoài mạch Đốc 1.3 thốn", chu_tri: "Đau đầu, đau vai gáy, nghẹt mũi, vẹo cổ" },
    { stt: 135, ma_who: "BL11", kinh: "Kinh Bàng Quang", ten: "Đại Trữ", vi_tri: "Dưới gai đốt sống ngực 1 đo ngang ra 1.5 thốn", chu_tri: "Ho, sốt, đau vai gáy, đau nhức xương khớp" },
    { stt: 136, ma_who: "BL12", kinh: "Kinh Bàng Quang", ten: "Phong Môn", vi_tri: "Dưới gai đốt sống ngực 2 đo ngang ra 1.5 thốn", chu_tri: "Cảm mạo, ho suyễn, sốt, đau vai gáy" },
    { stt: 137, ma_who: "BL13", kinh: "Kinh Bàng Quang", ten: "Phế Du", vi_tri: "Dưới gai đốt sống ngực 3 đo ngang ra 1.5 thốn", chu_tri: "Ho, hen suyễn, sốt, ho ra máu, mồ hôi trộm" },
    { stt: 138, ma_who: "BL14", kinh: "Kinh Bàng Quang", ten: "Quyết Âm Du", vi_tri: "Dưới gai đốt sống ngực 4 đo ngang ra 1.5 thốn", chu_tri: "Đau tim, hồi hộp, ho suyễn, tức ngực" },
    { stt: 139, ma_who: "BL15", kinh: "Kinh Bàng Quang", ten: "Tâm Du", vi_tri: "Dưới gai đốt sống ngực 5 đo ngang ra 1.5 thốn", chu_tri: "Hồi hộp, mất ngủ, hay quên, đau tim, động kinh" },
    { stt: 140, ma_who: "BL16", kinh: "Kinh Bàng Quang", ten: "Đốc Du", vi_tri: "Dưới gai đốt sống ngực 6 đo ngang ra 1.5 thốn", chu_tri: "Đau tim, đau bụng, ho suyễn, rụng tóc" },
    { stt: 141, ma_who: "BL17", kinh: "Kinh Bàng Quang", ten: "Cách Du", vi_tri: "Dưới gai đốt sống ngực 7 đo ngang ra 1.5 thốn", chu_tri: "Nấc cục, nôn mửa, thiếu máu, xuất huyết, ho ra máu" },
    { stt: 142, ma_who: "BL18", kinh: "Kinh Bàng Quang", ten: "Can Du", vi_tri: "Dưới gai đốt sống ngực 9 đo ngang ra 1.5 thốn", chu_tri: "Đau hông sườn, vàng da, đỏ mắt, chóng mặt" },
    { stt: 143, ma_who: "BL19", kinh: "Kinh Bàng Quang", ten: "Đảm Du", vi_tri: "Dưới gai đốt sống ngực 10 đo ngang ra 1.5 thốn", chu_tri: "Đắng miệng, vàng da, đau hông sườn, sốt rét" },
    { stt: 144, ma_who: "BL20", kinh: "Kinh Bàng Quang", ten: "Tỳ Du", vi_tri: "Dưới gai đốt sống ngực 11 đo ngang ra 1.5 thốn", chu_tri: "Đầy bụng, tiêu chảy, nôn mửa, phù thũng" },
    { stt: 145, ma_who: "BL21", kinh: "Kinh Bàng Quang", ten: "Vị Du", vi_tri: "Dưới gai đốt sống ngực 12 đo ngang ra 1.5 thốn", chu_tri: "Đau dạ dày, chướng bụng, nôn mửa, tiêu hóa kém" },
    { stt: 146, ma_who: "BL22", kinh: "Kinh Bàng Quang", ten: "Tam Tiêu Du", vi_tri: "Dưới gai đốt sống thắt lưng 1 đo ngang ra 1.5 thốn", chu_tri: "Trướng bụng, tiêu chảy, phù thũng, đau lưng" },
    { stt: 147, ma_who: "BL23", kinh: "Kinh Bàng Quang", ten: "Thận Du", vi_tri: "Dưới gai đốt sống thắt lưng 2 đo ngang ra 1.5 thốn", chu_tri: "Đau lưng, ù tai, di tinh, liệt dương, hen suyễn kinh niên" },
    { stt: 148, ma_who: "BL24", kinh: "Kinh Bàng Quang", ten: "Khí Hải Du", vi_tri: "Dưới gai đốt sống thắt lưng 3 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, trướng bụng, kinh nguyệt không đều, trĩ" },
    { stt: 149, ma_who: "BL25", kinh: "Kinh Bàng Quang", ten: "Đại Trường Du", vi_tri: "Dưới gai đốt sống thắt lưng 4 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, táo bón, tiêu chảy, liệt chi dưới" },
    { stt: 150, ma_who: "BL26", kinh: "Kinh Bàng Quang", ten: "Quan Nguyên Du", vi_tri: "Dưới gai đốt sống thắt lưng 5 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, tiêu chảy mạn, tiểu khó" },
    { stt: 151, ma_who: "BL27", kinh: "Kinh Bàng Quang", ten: "Tiểu Trường Du", vi_tri: "Dưới gai đốt sống cùng 1 đo ngang ra 1.5 thốn", chu_tri: "Đau bụng dưới, đái dắt, tiêu chảy, trĩ" },
    { stt: 152, ma_who: "BL28", kinh: "Kinh Bàng Quang", ten: "Bàng Quang Du", vi_tri: "Dưới gai đốt sống cùng 2 đo ngang ra 1.5 thốn", chu_tri: "Bí tiểu, đái dầm, tiêu chảy, đau thắt lưng" },
    { stt: 153, ma_who: "BL29", kinh: "Kinh Bàng Quang", ten: "Trung Lữ Du", vi_tri: "Dưới gai đốt sống cùng 3 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, tiêu chảy, đau trĩ, đái dắt" },
    { stt: 154, ma_who: "BL30", kinh: "Kinh Bàng Quang", ten: "Bạch Hoàn Du", vi_tri: "Dưới gai đốt sống cùng 4 đo ngang ra 1.5 thốn", chu_tri: "Di tinh, di niệu, khí hư, đau thắt lưng" },
    { stt: 155, ma_who: "BL31", kinh: "Kinh Bàng Quang", ten: "Thượng Liêu", vi_tri: "Chính lỗ xương cùng thứ nhất", chu_tri: "Đau thắt lưng, di tinh, khí hư, khó đẻ" },
    { stt: 156, ma_who: "BL32", kinh: "Kinh Bàng Quang", ten: "Thứ Liêu", vi_tri: "Chính lỗ xương cùng thứ hai", chu_tri: "Đau thắt lưng, kinh nguyệt không đều, liệt chi dưới" },
    { stt: 157, ma_who: "BL33", kinh: "Kinh Bàng Quang", ten: "Trung Liêu", vi_tri: "Chính lỗ xương cùng thứ 3", chu_tri: "Đau thắt lưng, đái dắt, khí hư, táo bón" },
    { stt: 158, ma_who: "BL34", kinh: "Kinh Bàng Quang", ten: "Hạ Liêu", vi_tri: "Chính lỗ xương cùng thứ 4", chu_tri: "Đau thắt lưng, đau bụng dưới, tiểu khó, khí hư" },
    { stt: 159, ma_who: "BL35", kinh: "Kinh Bàng Quang", ten: "Hội Dương", vi_tri: "Hai bên chóp xương cụt, đo ngang ra 0.5 thốn", chu_tri: "Trĩ, lỵ, tiêu chảy, khí hư, đau xương cụt" },
    { stt: 160, ma_who: "BL36", kinh: "Kinh Bàng Quang", ten: "Thừa Phù", vi_tri: "Chính giữa nếp gấp mông", chu_tri: "Đau thần kinh tọa, trĩ, tiểu khó, liệt chi dưới" },
    { stt: 161, ma_who: "BL37", kinh: "Kinh Bàng Quang", ten: "Ân Môn", vi_tri: "Dưới huyệt Thừa Phù 6 thốn, trên đường nối Thừa Phù - Ủy Trung", chu_tri: "Đau thắt lưng, đau thần kinh tọa, liệt chi dưới" },
    { stt: 162, ma_who: "BL38", kinh: "Kinh Bàng Quang", ten: "Phù Khích", vi_tri: "Trên huyệt Ủy Dương 1 thốn, sát bờ trong gân cơ nhị đầu đùi", chu_tri: "Đau khoeo chân, co rút đùi, táo bón" },
    { stt: 163, ma_who: "BL39", kinh: "Kinh Bàng Quang", ten: "Ủy Dương", vi_tri: "Mặt sau khoeo chân, bờ ngoài nếp gấp khoeo, sát gân cơ nhị đầu đùi", chu_tri: "Co rút đùi gối, trướng bụng, tiểu khó" },
    { stt: 164, ma_who: "BL40", kinh: "Kinh Bàng Quang", ten: "Ủy Trung", vi_tri: "Chính giữa lằn chỉ nếp gấp khoeo chân", chu_tri: "Đau lưng cấp, đau thần kinh tọa, liệt chân, sốt cao" },
    { stt: 165, ma_who: "BL41", kinh: "Kinh Bàng Quang", ten: "Phụ Phân", vi_tri: "Dưới gai đốt sống ngực 2 đo ngang ra 3 thốn", chu_tri: "Đau vai gáy, cứng cổ, tê cánh tay" },
    { stt: 166, ma_who: "BL42", kinh: "Kinh Bàng Quang", ten: "Phách Hộ", vi_tri: "Dưới gai đốt sống ngực 3 đo ngang ra 3 thốn", chu_tri: "Ho suyễn, đau lưng gáy, lao phổi" },
    { stt: 167, ma_who: "BL43", kinh: "Kinh Bàng Quang", ten: "Cao Hoang", vi_tri: "Dưới gai đốt sống ngực 4 đo ngang ra 3 thốn", chu_tri: "Suy nhược cơ thể, ho lao, ho suyễn, di tinh" },
    { stt: 168, ma_who: "BL44", kinh: "Kinh Bàng Quang", ten: "Thần Đường", vi_tri: "Dưới gai đốt sống ngực 5 đo ngang ra 3 thốn", chu_tri: "Ho, hen suyễn, tức ngực, đau vai gáy" },
    { stt: 169, ma_who: "BL45", kinh: "Kinh Bàng Quang", ten: "Y Hỷ", vi_tri: "Dưới gai đốt sống ngực 6 đo ngang ra 3 thốn", chu_tri: "Đau ngực sườn, ho suyễn, ợ chua" },
    { stt: 170, ma_who: "BL46", kinh: "Kinh Bàng Quang", ten: "Cách Quan", vi_tri: "Dưới gai đốt sống ngực 7 đo ngang ra 3 thốn", chu_tri: "Đau lưng, nấc cục, nuốt vướng, ợ hơi" },
    { stt: 171, ma_who: "BL47", kinh: "Kinh Bàng Quang", ten: "Hồn Môn", vi_tri: "Dưới gai đốt sống ngực 9 đo ngang ra 3 thốn", chu_tri: "Đau hông sườn, nôn mửa, tiêu chảy, đau lưng" },
    { stt: 172, ma_who: "BL48", kinh: "Kinh Bàng Quang", ten: "Dương Cương", vi_tri: "Dưới gai đốt sống ngực 10 đo ngang ra 3 thốn", chu_tri: "Vàng da, đau hông sườn, tiêu chảy, nôn mửa" },
    { stt: 173, ma_who: "BL49", kinh: "Kinh Bàng Quang", ten: "Ý Xá", vi_tri: "Dưới gai đốt sống ngực 11 đo ngang ra 3 thốn", chu_tri: "Trướng bụng, nôn mửa, tiêu chảy, nuốt vướng" },
    { stt: 174, ma_who: "BL50", kinh: "Kinh Bàng Quang", ten: "Vị Thương", vi_tri: "Dưới gai đốt sống ngực 12 đo ngang ra 3 thốn", chu_tri: "Đau dạ dày, trướng bụng, ăn không tiêu" },
    { stt: 175, ma_who: "BL51", kinh: "Kinh Bàng Quang", ten: "Hoang Môn", vi_tri: "Dưới gai đốt sống thắt lưng 1 đo ngang ra 3 thốn", chu_tri: "Đau bụng dưới, táo bón, đau thắt lưng, nổi mụn vú" },
    { stt: 176, ma_who: "BL52", kinh: "Kinh Bàng Quang", ten: "Chí Thất", vi_tri: "Dưới gai đốt sống thắt lưng 2 đo ngang ra 3 thốn", chu_tri: "Di tinh, liệt dương, tiểu dắt, đau thắt lưng, sưng sinh dục" },
    { stt: 177, ma_who: "BL53", kinh: "Kinh Bàng Quang", ten: "Bào Hoang", vi_tri: "Dưới gai đốt sống cùng 2 đo ngang ra 3 thốn", chu_tri: "Trướng bụng, bí tiểu, đau thần kinh tọa, đau lưng" },
    { stt: 178, ma_who: "BL54", kinh: "Kinh Bàng Quang", ten: "Trật Biên", vi_tri: "Dưới gai đốt sống cùng 4 đo ngang ra 3 thốn", chu_tri: "Đau thắt lưng, đau thần kinh tọa, trĩ, liệt chi dưới" },
    { stt: 179, ma_who: "BL55", kinh: "Kinh Bàng Quang", ten: "Hợp Dương", vi_tri: "Dưới huyệt Ủy Trung 2 thốn, giữa hai bắp cơ sinh đôi", chu_tri: "Đau lưng, đau thần kinh tọa, băng lậu, thoát vị" },
    { stt: 180, ma_who: "BL56", kinh: "Kinh Bàng Quang", ten: "Thừa Cân", vi_tri: "Giữa bắp chân, trên đường nối Hợp Dương - Thừa Sơn", chu_tri: "Chuột rút bắp chân, đau thắt lưng, trĩ, đau cẳng chân" },
    { stt: 181, ma_who: "BL57", kinh: "Kinh Bàng Quang", ten: "Thừa Sơn", vi_tri: "Chỗ lõm giữa bắp chân, nơi hai bắp cơ sinh đôi tách ra", chu_tri: "Chuột rút bắp chân, trĩ, táo bón, liệt chi dưới" },
    { stt: 182, ma_who: "BL58", kinh: "Kinh Bàng Quang", ten: "Phi Dương", vi_tri: "Từ huyệt Côn Lôn đo thẳng lên 7 thốn", chu_tri: "Đau đầu, nghẹt mũi, đau lưng, trị trĩ" },
    { stt: 183, ma_who: "BL59", kinh: "Kinh Bàng Quang", ten: "Phụ Dương", vi_tri: "Từ đỉnh mắt cá ngoài đo lên 3 thốn, sát bờ ngoài gân gót", chu_tri: "Đau thắt lưng, đau cổ chân, liệt chi dưới, đau gáy" },
    { stt: 184, ma_who: "BL60", kinh: "Kinh Bàng Quang", ten: "Côn Lôn", vi_tri: "Chỗ lõm giữa đỉnh mắt cá ngoài và gân gót chân", chu_tri: "Đau đầu, cứng cổ gáy, đau thắt lưng, khó đẻ" },
    { stt: 185, ma_who: "BL61", kinh: "Kinh Bàng Quang", ten: "Bộc Tham", vi_tri: "Chỗ lõm mặt ngoài xương gót, dưới Thần Mạch 0.5 thốn", chu_tri: "Đau gót chân, đau cổ chân, động kinh" },
    { stt: 186, ma_who: "BL62", kinh: "Kinh Bàng Quang", ten: "Thần Mạch", vi_tri: "Chỗ lõm ngay dưới đỉnh mắt cá ngoài 0.5 thốn", chu_tri: "Đau đầu, mất ngủ, chóng mặt, động kinh, đau cổ chân" },
    { stt: 187, ma_who: "BL63", kinh: "Kinh Bàng Quang", ten: "Kim Môn", vi_tri: "Phía dưới trước mắt cá ngoài, chỗ lõm xương hộp", chu_tri: "Đau đầu, động kinh, đau cổ chân, co giật trẻ em" },
    { stt: 188, ma_who: "BL64", kinh: "Kinh Bàng Quang", ten: "Kinh Cốt", vi_tri: "Chỗ lõm phía dưới ngoài mấu củ xương bàn chân thứ 5", chu_tri: "Đau đầu, cứng cổ gáy, đau thắt lưng, động kinh" },
    { stt: 189, ma_who: "BL65", kinh: "Kinh Bàng Quang", ten: "Thúc Cốt", vi_tri: "Chỗ lõm phía sau khớp ngón-bàn chân thứ 5, bờ ngoài", chu_tri: "Đau đầu, cứng gáy, đau lưng, đau mông đùi" },
    { stt: 190, ma_who: "BL66", kinh: "Kinh Bàng Quang", ten: "Thông Cốc", vi_tri: "Chỗ lõm phía trước khớp ngón-bàn chân thứ 5, bờ ngoài", chu_tri: "Đau đầu, cứng cổ gáy, chảy máu cam, chóng mặt" },
    { stt: 191, ma_who: "BL67", kinh: "Kinh Bàng Quang", ten: "Chí Âm", vi_tri: "Bờ ngoài ngón chân út cách gốc móng 0.1 thốn", chu_tri: "Ngôi thai ngược (cứu), đau đầu, nghẹt mũi" },

    // --- KINH TÚC THIẾU ÂM THẬN (27 huyệt) ---
    { stt: 192, ma_who: "KI1", kinh: "Kinh Thận", ten: "Dũng Tuyền", vi_tri: "Chỗ lõm gan bàn chân, tại 1/3 trước đường nối ngón 2 và gót", chu_tri: "Mất ngủ, nhức đầu, ho khan, đỉnh đầu đau, hạ huyết áp" },
    { stt: 193, ma_who: "KI2", kinh: "Kinh Thận", ten: "Nhiên Cốc", vi_tri: "Chỗ lõm trước dưới củ xương thuyền bàn chân", chu_tri: "Kinh nguyệt không đều, di tinh, đau họng, tiểu buốt, đái dầm" },
    { stt: 194, ma_who: "KI3", kinh: "Kinh Thận", ten: "Thái Khê", vi_tri: "Chỗ lõm giữa đỉnh mắt cá trong và gân gót chân", chu_tri: "Đau lưng, ù tai, hen suyễn, mất ngủ, di tinh" },
    { stt: 195, ma_who: "KI4", kinh: "Kinh Thận", ten: "Đại Chung", vi_tri: "Dưới sau mắt cá trong, sát bờ trong gân gót", chu_tri: "Ho ra máu, suyễn, bí tiểu, đau gót chân" },
    { stt: 196, ma_who: "KI5", kinh: "Kinh Thận", ten: "Thủy Tuyền", vi_tri: "Dưới huyệt Thái Khê 1 thốn, chỗ lõm bờ ngoài xương gót", chu_tri: "Đau bụng kinh, bế kinh, sa tử cung, tiểu khó" },
    { stt: 197, ma_who: "KI6", kinh: "Kinh Thận", ten: "Chiếu Hải", vi_tri: "Chỗ lõm dưới đỉnh mắt cá trong 1 thốn", chu_tri: "Kinh nguyệt không đều, hầu họng khô đau, mất ngủ" },
    { stt: 198, ma_who: "KI7", kinh: "Kinh Thận", ten: "Phục Lưu", vi_tri: "Từ Thái Khê đo thẳng lên 2 thốn, sát bờ trước gân gót", chu_tri: "Phù thũng, tiêu chảy, ra mồ hôi trộm hoặc không ra mồ hôi" },
    { stt: 199, ma_who: "KI8", kinh: "Kinh Thận", ten: "Giao Tín", vi_tri: "Trên huyệt Thái Khê 2 thốn, trước Phục Lưu 0.5 thốn", chu_tri: "Băng lậu, sa tử cung, đau cẳng chân, tiêu chảy" },
    { stt: 200, ma_who: "KI9", kinh: "Kinh Thận", ten: "Trúc Tân", vi_tri: "Từ Thái Khê đo lên 5 thốn, chỗ lõm bờ dưới cơ bụng chân", chu_tri: "Điên cuồng, đau bắp chân, sưng đau hernia" },
    { stt: 201, ma_who: "KI10", kinh: "Kinh Thận", ten: "Âm Cốc", vi_tri: "Mặt trong khoeo chân, giữa 2 gân cơ bán gân và bán màng", chu_tri: "Liệt dương, băng lậu, đau bụng dưới, tiểu buốt" },
    { stt: 202, ma_who: "KI11", kinh: "Kinh Thận", ten: "Hoành Cốt", vi_tri: "Bờ trên xương mu, cách đường giữa bụng 0.5 thốn", chu_tri: "Bí tiểu, đau thoát vị, di tinh, liệt dương" },
    { stt: 203, ma_who: "KI12", kinh: "Kinh Thận", ten: "Đại Hách", vi_tri: "Dưới rốn 4 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Di tinh, liệt dương, khí hư, đau bụng dưới" },
    { stt: 204, ma_who: "KI13", kinh: "Kinh Thận", ten: "Khí Huyệt", vi_tri: "Dưới rốn 3 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Kinh nguyệt không đều, tiêu chảy, bí tiểu" },
    { stt: 205, ma_who: "KI14", kinh: "Kinh Thận", ten: "Tứ Mãn", vi_tri: "Dưới rốn 2 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Trướng bụng, đau bụng kinh, phù thũng, tiêu chảy" },
    { stt: 206, ma_who: "KI15", kinh: "Kinh Thận", ten: "Trung Chú", vi_tri: "Dưới rốn 1 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau bụng quanh rốn, táo bón, kinh nguyệt không đều" },
    { stt: 207, ma_who: "KI16", kinh: "Kinh Thận", ten: "Hoang Du", vi_tri: "Ngang rốn, cách rốn 0.5 thốn về phía trong", chu_tri: "Đau bụng quanh rốn, trướng bụng, táo bón, nôn mửa" },
    { stt: 208, ma_who: "KI17", kinh: "Kinh Thận", ten: "Thương Khúc", vi_tri: "Trên rốn 2 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, đau bụng, ăn không tiêu" },
    { stt: 209, ma_who: "KI18", kinh: "Kinh Thận", ten: "Thạch Quan", vi_tri: "Trên rốn 3 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, nôn mửa, táo bón, đau bụng" },
    { stt: 210, ma_who: "KI19", kinh: "Kinh Thận", ten: "Âm Đô", vi_tri: "Trên rốn 4 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, đầy trướng ngực sườn, ợ hơi" },
    { stt: 211, ma_who: "KI20", kinh: "Kinh Thận", ten: "Thông Cốc (Thận)", vi_tri: "Trên rốn 5 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, nôn mửa, ho suyễn, trướng bụng" },
    { stt: 212, ma_who: "KI21", kinh: "Kinh Thận", ten: "U Môn", vi_tri: "Trên rốn 6 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, nôn mửa, ợ chua, đau hông sườn" },
    { stt: 213, ma_who: "KI22", kinh: "Kinh Thận", ten: "Bộ Lang", vi_tri: "Khoang liên sườn 5, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực sườn, nôn mửa" },
    { stt: 214, ma_who: "KI23", kinh: "Kinh Thận", ten: "Thần Phong", vi_tri: "Khoang liên sườn 4, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau tức ngực, viêm tuyến vú" },
    { stt: 215, ma_who: "KI24", kinh: "Kinh Thận", ten: "Linh Khư", vi_tri: "Khoang liên sườn 3, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực sườn, nôn mửa, mất vị giác" },
    { stt: 216, ma_who: "KI25", kinh: "Kinh Thận", ten: "Thần Tàng", vi_tri: "Khoang liên sườn 2, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực, nôn mửa" },
    { stt: 217, ma_who: "KI26", kinh: "Kinh Thận", ten: "Hoắc Trung", vi_tri: "Khoang liên sườn 1, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau tức ngực, nghẹn cổ" },
    { stt: 218, ma_who: "KI27", kinh: "Kinh Thận", ten: "Du Phủ", vi_tri: "Chỗ lõm bờ dưới xương đòn, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực, hen phế quản, nuốt vướng" },

    // --- KINH THỦ QUYẾT ÂM TÂM BÀO (9 huyệt) ---
    { stt: 219, ma_who: "PC1", kinh: "Kinh Tâm Bào", ten: "Thiên Trì", vi_tri: "Khoang liên sườn 4, ngoài núm vú 1 thốn", chu_tri: "Đau ngực, ho, sưng hạch nách, đau hông sườn" },
    { stt: 220, ma_who: "PC2", kinh: "Kinh Tâm Bào", ten: "Thiên Tuyền", vi_tri: "Dưới nếp gấp nách trước 2 thốn, giữa hai đầu cơ nhị đầu cánh tay", chu_tri: "Đau ngực, ho, đau vai cẳng tay, hồi hộp" },
    { stt: 221, ma_who: "PC3", kinh: "Kinh Tâm Bào", ten: "Khúc Trạch", vi_tri: "Trên nếp gấp khuỷu tay, bờ trong gân cơ nhị đầu", chu_tri: "Đau tim, hồi hộp, nôn mửa, sốt cao, run tay" },
    { stt: 222, ma_who: "PC4", kinh: "Kinh Tâm Bào", ten: "Tích Môn", vi_tri: "Từ lằn chỉ cổ tay đo lên 5 thốn, giữa hai gân cơ", chu_tri: "Đau vùng tim, hồi hộp, ho ra máu, nôn ra máu" },
    { stt: 223, ma_who: "PC5", kinh: "Kinh Tâm Bào", ten: "Gian Sử", vi_tri: "Từ lằn chỉ cổ tay đo thẳng lên 3 thốn, giữa hai gân cơ", chu_tri: "Đau vùng tim, sốt rét, điên cuồng, nôn mửa" },
    { stt: 224, ma_who: "PC6", kinh: "Kinh Tâm Bào", ten: "Nội Quan", vi_tri: "Từ lằn chỉ cổ tay đo thẳng lên 2 thốn, giữa hai gân cơ", chu_tri: "Đau thắt ngực, mất ngủ, nôn mửa, say tàu xe, hồi hộp" },
    { stt: 225, ma_who: "PC7", kinh: "Kinh Tâm Bào", ten: "Đại Lăng", vi_tri: "Chính giữa lằn chỉ cổ tay, giữa hai gân cơ", chu_tri: "Đau vùng tim, loét miệng, đau đầu, đỏ mắt" },
    { stt: 226, ma_who: "PC8", kinh: "Kinh Tâm Bào", ten: "Lao Cung", vi_tri: "Trong lòng bàn tay, giữa xương đốt ngón 2-3 (khi nắm tay, đầu ngón giữa chạm vào)", chu_tri: "Loét miệng, hôi miệng, tim hồi hộp, động kinh" },
    { stt: 227, ma_who: "PC9", kinh: "Kinh Tâm Bào", ten: "Trung Xung", vi_tri: "Chính giữa đầu ngón tay giữa cách móng 0.1 thốn", chu_tri: "Sốt cao, trúng phong hôn mê, đau tim, say nắng" },

    // --- KINH THỦ THIẾU DƯƠNG TAM TIÊU (22 huyệt) ---
    { stt: 228, ma_who: "TE1", kinh: "Kinh Tam Tiêu", ten: "Quan Xung", vi_tri: "Bờ ngoài ngón áp út, cách gốc móng 0.1 thốn", chu_tri: "Sốt cao, đau đầu, ù tai, đau họng" },
    { stt: 229, ma_who: "TE2", kinh: "Kinh Tam Tiêu", ten: "Dịch Môn", vi_tri: "Mu bàn tay, chỗ kẽ giữa ngón 4 và 5 đo lên 0.5 thốn", chu_tri: "Sốt, đau đầu, sưng họng, ù tai, đau cẳng tay" },
    { stt: 230, ma_who: "TE3", kinh: "Kinh Tam Tiêu", ten: "Trung Chử", vi_tri: "Mu bàn tay, chỗ lõm giữa xương đốt ngón tay 4 và 5", chu_tri: "Ù tai, điếc tai, đau đầu, đau mắt đỏ, co rút ngón tay" },
    { stt: 231, ma_who: "TE4", kinh: "Kinh Tam Tiêu", ten: "Dương Trì", vi_tri: "Chính giữa nếp gấp sau cổ tay, bờ ngoài gân cơ duỗi chung các ngón", chu_tri: "Đau cổ tay, đau họng, sốt rét, tiêu hóa kém" },
    { stt: 232, ma_who: "TE5", kinh: "Kinh Tam Tiêu", ten: "Ngoại Quan", vi_tri: "Từ lằn chỉ cổ tay mặt sau đo lên 2 thốn, đối diện Nội Quan", chu_tri: "Cảm mạo sốt, đau đầu, đau khớp vai gáy, ù tai" },
    { stt: 233, ma_who: "TE6", kinh: "Kinh Tam Tiêu", ten: "Chi Câu", vi_tri: "Từ lằn chỉ cổ tay mặt sau đo lên 3 thốn", chu_tri: "Táo bón, đau hông sườn, sốt không ra mồ hôi" },
    { stt: 234, ma_who: "TE7", kinh: "Kinh Tam Tiêu", ten: "Hội Tông", vi_tri: "Trên lằn cổ tay sau 3 thốn, phía ngoài Ngoại Quan 1 khoát ngón tay", chu_tri: "Ù tai, điếc tai, đau cánh tay, động kinh" },
    { stt: 235, ma_who: "TE8", kinh: "Kinh Tam Tiêu", ten: "Tam Dương Lạc", vi_tri: "Trên lằn cổ tay sau 4 thốn, giữa xương quay và trụ", chu_tri: "Điếc tai, mất tiếng đột ngột, đau cẳng tay" },
    { stt: 236, ma_who: "TE9", kinh: "Kinh Tam Tiêu", ten: "Tứ Độc", vi_tri: "Dưới mỏm khuỷu tay 5 thốn, giữa xương quay và trụ", chu_tri: "Điếc tai, sưng họng, đau cẳng tay, mất tiếng" },
     { stt: 237, ma_who: "TE10", kinh: "Kinh Tam Tiêu", ten: "Thiên Tỉnh", vi_tri: "Chỗ lõm phía trên mỏm khuỷu tay 1 thốn khi co khuỷu tay", chu_tri: "Đau khớp khuỷu, đau vai gáy, ho suyễn, lao hạch cổ, động kinh" },
    { stt: 238, ma_who: "TE11", kinh: "Kinh Tam Tiêu", ten: "Thanh Lãnh Uyên", vi_tri: "Trên mỏm khuỷu tay 2 thốn khi co khuỷu (trên Thiên Tỉnh 1 thốn)", chu_tri: "Đau khớp khuỷu, đau vai gáy, nhức đầu" },
    { stt: 239, ma_who: "TE12", kinh: "Kinh Tam Tiêu", ten: "Tiêu Lạc", vi_tri: "Mặt sau cánh tay, giữa Thanh Lãnh Uyên và Nhu Hội", chu_tri: "Đau gáy cổ, đau cánh tay, đau đầu" },
    { stt: 240, ma_who: "TE13", kinh: "Kinh Tam Tiêu", ten: "Nhu Hội", vi_tri: "Bờ sau cơ delta, dưới Kiên Liêu 3 thốn", chu_tri: "Đau vai cẳng tay, bướu cổ, cứng gáy" },
    { stt: 241, ma_who: "TE14", kinh: "Kinh Tam Tiêu", ten: "Kiên Liêu", vi_tri: "Chỗ lõm phía sau dưới mỏm cùng vai khi dang tay", chu_tri: "Đau khớp vai, liệt cánh tay, không giơ tay được" },
    { stt: 242, ma_who: "TE15", kinh: "Kinh Tam Tiêu", ten: "Thiên Liêu", vi_tri: "Chính giữa đoạn nối Kiên Tỉnh và góc trên xương bả vai", chu_tri: "Đau vai gáy, đau cổ gáy, bả vai co rút" },
    { stt: 243, ma_who: "TE16", kinh: "Kinh Tam Tiêu", ten: "Thiên Dũ", vi_tri: "Bờ sau cơ ức đòn chũm, dưới Phong Trì, ngang góc hàm", chu_tri: "Đau đầu, điếc tai, cổ cứng đau, mắt sưng" },
    { stt: 244, ma_who: "TE17", kinh: "Kinh Tam Tiêu", ten: "Ế Phong", vi_tri: "Chỗ lõm phía sau dái tai, sát bờ trước xương chũm", chu_tri: "Ù tai, điếc tai, liệt mặt, đau răng, quai bị" },    
    { stt: 244, ma_who: "TE18", kinh: "Kinh Tam Tiêu", ten: "Kế Mạch", vi_tri: "Sau tai, tại điểm nối 1/3 dưới đường Giác Tôn - Ế Phong", chu_tri: "Đau đầu, ù tai, co giật trẻ em, điếc tai" },
    { stt: 245, ma_who: "TE19", kinh: "Kinh Tam Tiêu", ten: "Lô Tức", vi_tri: "Sau vành tai, đường nối Giác Tôn - Ế Phong (1/3 trên)", chu_tri: "Đau đầu, ù tai, nôn mửa, sưng đau tai" },
    { stt: 246, ma_who: "TE20", kinh: "Kinh Tam Tiêu", ten: "Giác Tôn", vi_tri: "Chính giữa đường chân tóc trên vành tai khi gấp vành tai về trước", chu_tri: "Đau đầu, sưng tai, mờ mắt, đau răng" },
    { stt: 247, ma_who: "TE21", kinh: "Kinh Tam Tiêu", ten: "Nhĩ Môn", vi_tri: "Chỗ lõm phía trên khuyết trước vành tai, khi há miệng có chỗ lõm", chu_tri: "Ù tai, điếc tai, viêm tai giữa, đau răng" },
    { stt: 248, ma_who: "TE22", kinh: "Kinh Tam Tiêu", ten: "Hòa Liêu (Tam Tiêu)", vi_tri: "Chỗ lõm phía trước trên chân vành tai, sát động mạch thái dương nông", chu_tri: "Đau đầu, ù tai, cứng hàm, méo miệng" },
    { stt: 249, ma_who: "TE23", kinh: "Kinh Tam Tiêu", ten: "Ty Trúc Không", vi_tri: "Chỗ lõm sát đầu ngoài chân mày", chu_tri: "Đau đầu, đau mắt, giật cơ mi mắt, liệt mặt" }
];
// === ĐỢT 3: KINH ĐỞM, CAN, NHÂM, ĐỐC VÀ KỲ HUYỆT (STT 250 - 392) ===
window.huyetViDataBatch3 = [
    // --- KINH TÚC THIẾU DƯƠNG ĐỞM (44 huyệt) ---
    { stt: 250, ma_who: "GB1", kinh: "Kinh Đởm", ten: "Đồng Tử Liêu", vi_tri: "Cách khóe mắt ngoài 0.1 thốn, chỗ lõm bờ ngoài hốc mắt", chu_tri: "Đau đầu, đau mắt đỏ, cận thị, liệt mặt" },
    { stt: 251, ma_who: "GB2", kinh: "Kinh Đởm", ten: "Thính Hội", vi_tri: "Phía trước rãnh bình tai, bờ dưới mỏm trang thái dương (há miệng có chỗ lõm)", chu_tri: "Ù tai, điếc tai, viêm tai giữa, liệt mặt" },
    { stt: 252, ma_who: "GB3", kinh: "Kinh Đởm", ten: "Thượng Quan", vi_tri: "Chỗ lõm bờ trên cung tiếp gò má, ngay phía trên huyệt Hạ Quan (ST7)", chu_tri: "Đau đầu, ù tai, điếc tai, đau răng, méo miệng" },
    { stt: 253, ma_who: "GB4", kinh: "Kinh Đởm", ten: "Hàm Yến", vi_tri: "Trong mép tóc thái dương, 1/4 trên đường nối Đầu Duy (ST8) - Khúc Tần (GB7)", chu_tri: "Đau nửa đầu, chóng mặt, giật cơ mi mắt, đau răng" },
    { stt: 254, ma_who: "GB5", kinh: "Kinh Đởm", ten: "Huyền Lô", vi_tri: "Trong mép tóc thái dương, điểm giữa đường nối Đầu Duy (ST8) - Khúc Tần (GB7)", chu_tri: "Đau nửa đầu, sưng mặt, đau răng hàm" },
    { stt: 255, ma_who: "GB6", kinh: "Kinh Đởm", ten: "Huyền Ly", vi_tri: "Trong mép tóc thái dương, 3/4 dưới đường nối Đầu Duy (ST8) - Khúc Tần (GB7)", chu_tri: "Đau nửa đầu, đau mắt đỏ, đau sưng mặt" },
    { stt: 256, ma_who: "GB7", kinh: "Kinh Đởm", ten: "Khúc Tần", vi_tri: "Giao điểm đường chân tóc ngang trước tai và đường dọc qua bờ trước chân vành tai", chu_tri: "Đau nửa đầu, đau sưng vùng má, cứng hàm" },
    { stt: 257, ma_who: "GB8", kinh: "Kinh Đởm", ten: "Suất Cốc", vi_tri: "Vùng thái dương, thẳng từ đỉnh vành tai lên vào trong chân tóc 1.5 thốn", chu_tri: "Đau nửa đầu, chóng mặt, nôn mửa do say rượu" },
    { stt: 258, ma_who: "GB9", kinh: "Kinh Đởm", ten: "Thiên Xung", vi_tri: "Phía sau tai, thẳng trên bờ sau vành tai 2 thốn, sau Suất Cốc (GB8) 0.5 thốn", chu_tri: "Đau đầu, động kinh, sưng đau chân răng" },
    { stt: 259, ma_who: "GB10", kinh: "Kinh Đởm", ten: "Phù Bạch", vi_tri: "Sau đỉnh tai, điểm nối 1/3 trên đường nối Thiên Xung (GB9) - Hoàn Cốt (GB12)", chu_tri: "Đau đầu, ù tai, điếc tai, sưng đau hầu họng" },
    { stt: 260, ma_who: "GB11", kinh: "Kinh Đởm", ten: "Đầu Khiếu Âm", vi_tri: "Sau vành tai, điểm nối 2/3 dưới đường nối Thiên Xung (GB9) - Hoàn Cốt (GB12)", chu_tri: "Đau đầu, ù tai, đau cổ gáy, đắng miệng" },
    { stt: 261, ma_who: "GB12", kinh: "Kinh Đởm", ten: "Hoàn Cốt", vi_tri: "Chỗ lõm phía sau dưới mỏm chũm xương thái dương", chu_tri: "Đau đầu, đau răng, méo miệng, ù tai, cứng cổ" },
    { stt: 262, ma_who: "GB13", kinh: "Kinh Đởm", ten: "Bản Thần", vi_tri: "Vùng trán, trên đường chân tóc 0.5 thốn, thẳng trên khóe mắt ngoài", chu_tri: "Đau đầu, động kinh, co giật trẻ em, gáy cứng" },
    { stt: 263, ma_who: "GB14", kinh: "Kinh Đởm", ten: "Dương Bạch", vi_tri: "Vùng trán, thẳng trên đồng tử mắt, trên lông mày 1 thốn", chu_tri: "Đau trán, sụp mi mắt, giật cơ mi, ngứa mắt, liệt mặt" },
    { stt: 264, ma_who: "GB15", kinh: "Kinh Đởm", ten: "Đầu Lâm Khấp", vi_tri: "Vùng trán, thẳng trên đồng tử mắt, vào trong đường chân tóc 0.5 thốn", chu_tri: "Đau đầu, nghẹt mũi, chảy nước mắt, mờ mắt" },
    { stt: 265, ma_who: "GB16", kinh: "Kinh Đởm", ten: "Mục Song", vi_tri: "Vùng đầu, sau Đầu Lâm Khấp (GB15) 1 thốn, trên đường thẳng dọc qua mắt", chu_tri: "Đau đầu, mờ mắt, đau mắt đỏ, chảy nước mắt" },
    { stt: 266, ma_who: "GB17", kinh: "Kinh Đởm", ten: "Chính Dinh", vi_tri: "Vùng đầu, sau Mục Song (GB16) 1 thốn, trên đường thẳng dọc qua mắt", chu_tri: "Đau đầu, chóng mặt, đau răng hàm" },
    { stt: 267, ma_who: "GB18", kinh: "Kinh Đởm", ten: "Thừa Linh", vi_tri: "Vùng đầu, sau Chính Dinh (GB17) 1.5 thốn, trên đường thẳng dọc qua mắt", chu_tri: "Đau đầu, chảy máu cam, nghẹt mũi, ho suyễn" },
    { stt: 268, ma_who: "GB19", kinh: "Kinh Đởm", ten: "Não Không", vi_tri: "Vùng chẩm, sau Thừa Linh (GB18) 1.5 thốn, ngang bờ trên u chẩm ngoài", chu_tri: "Đau gáy cổ, đau đầu, ho hen, mờ mắt" },
    { stt: 269, ma_who: "GB20", kinh: "Kinh Đởm", ten: "Phong Trì", vi_tri: "Chỗ lõm bờ ngoài cơ thang, bờ sau cơ ức đòn chũm dưới xương chẩm", chu_tri: "Đau đầu, chóng mặt, cảm mạo, đau vai gáy, tăng huyết áp" },
    { stt: 270, ma_who: "GB21", kinh: "Kinh Đởm", ten: "Kiên Tỉnh", vi_tri: "Điểm giữa đường nối mỏm gai đốt sống cổ 7 (C7) và mỏm cùng vai", chu_tri: "Đau vai gáy, liệt chi trên, tắc sữa, viêm tuyến vú" },
    { stt: 271, ma_who: "GB22", kinh: "Kinh Đởm", ten: "Uyên Dịch", vi_tri: "Thành ngực bên, khoang liên sườn 4, trên đường nách giữa, dưới nách 3 thốn", chu_tri: "Đau ngực sườn, sưng hạch nách, đau cánh tay" },
    { stt: 272, ma_who: "GB23", kinh: "Kinh Đởm", ten: "Triếp Cân", vi_tri: "Thành ngực bên, khoang liên sườn 4, trước huyệt Uyên Dịch (GB22) 1 thốn", chu_tri: "Ho suyễn, đau ngực sườn, ợ chua, nôn mửa" },
    { stt: 273, ma_who: "GB24", kinh: "Kinh Đởm", ten: "Nhật Nguyệt", vi_tri: "Thành ngực trước, khoang liên sườn 7, thẳng dưới núm vú", chu_tri: "Đau hông sườn, nôn mửa, nấc cục, vàng da" },
    { stt: 274, ma_who: "GB25", kinh: "Kinh Đởm", ten: "Kinh Môn", vi_tri: "Thành bụng bên, bờ dưới đầu tự do xương sườn thứ 12", chu_tri: "Đau hông sườn, trướng bụng, tiêu chảy, đau thắt lưng" },
    { stt: 275, ma_who: "GB26", kinh: "Kinh Đởm", ten: "Đới Mạch", vi_tri: "Vùng hông, thẳng dưới đầu xương sườn thứ 11, ngang hàng với rốn", chu_tri: "Kinh nguyệt không đều, khí hư, đau bụng dưới" },
    { stt: 276, ma_who: "GB27", kinh: "Kinh Đởm", ten: "Ngũ Khu", vi_tri: "Vùng hông, phía trước dưới gai chậu trước trên, ngang dưới rốn 3 thốn", chu_tri: "Đau bụng dưới, thoát vị bẹn, khí hư" },
    { stt: 277, ma_who: "GB28", kinh: "Kinh Đởm", ten: "Duy Đạo", vi_tri: "Vùng hông, phía trước dưới huyệt Ngũ Khu (GB27) 0.5 thốn", chu_tri: "Đau bụng dưới, sa tử cung, táo bón" },
    { stt: 278, ma_who: "GB29", kinh: "Kinh Đởm", ten: "Cư Liêu", vi_tri: "Vùng hông khớp háng, điểm giữa đường nối gai chậu trước trên và mấu chuyển lớn xương đùi", chu_tri: "Đau thắt lưng, đau khớp háng, liệt chi dưới" },
    { stt: 279, ma_who: "GB30", kinh: "Kinh Đởm", ten: "Hoàn Khiêu", vi_tri: "Vùng mông, giao điểm 1/3 ngoài và 2/3 trong đường nối mấu chuyển lớn xương đùi và mỏm gai xương cùng", chu_tri: "Đau thần kinh tọa, liệt chi dưới, đau khớp háng" },
    { stt: 280, ma_who: "GB31", kinh: "Kinh Đởm", ten: "Phong Thị", vi_tri: "Mặt ngoài đùi, trên nếp khoeo 7 thốn (đầu ngón tay giữa chạm vào khi đứng thẳng áp tay)", chu_tri: "Liệt chi dưới, ngứa toàn thân, đau đùi" },
    { stt: 281, ma_who: "GB32", kinh: "Kinh Đởm", ten: "Trung Độc", vi_tri: "Mặt ngoài đùi, dưới huyệt Phong Thị (GB31) 2 thốn", chu_tri: "Liệt chi dưới, đau thần kinh tọa, đau đùi" },
    { stt: 282, ma_who: "GB33", kinh: "Kinh Đởm", ten: "Tất Dương Quan", vi_tri: "Mặt ngoài gối, chỗ lõm phía trên lồi cầu ngoài xương đùi", chu_tri: "Đau khớp gối, co rút gân khoeo, tê cẳng chân" },
    { stt: 283, ma_who: "GB34", kinh: "Kinh Đởm", ten: "Dương Lăng Tuyền", vi_tri: "Chỗ lõm phía dưới trước chỏm xương mác", chu_tri: "Co rút cơ gân, đau thần kinh tọa, đau hông sườn, viêm gan" },
    { stt: 284, ma_who: "GB35", kinh: "Kinh Đởm", ten: "Dương Giao", vi_tri: "Mặt ngoài cẳng chân, trên đỉnh mắt cá ngoài 7 thốn, bờ sau xương mác", chu_tri: "Đau ngực sườn, trướng bụng, đau cẳng chân" },
    { stt: 285, ma_who: "GB36", kinh: "Kinh Đởm", ten: "Ngoại Khâu", vi_tri: "Mặt ngoài cẳng chân, trên đỉnh mắt cá ngoài 7 thốn, bờ trước xương mác", chu_tri: "Đau ngực sườn, đau cẳng chân, động kinh" },
    { stt: 286, ma_who: "GB37", kinh: "Kinh Đởm", ten: "Quang Minh", vi_tri: "Mặt ngoài cẳng chân, từ đỉnh mắt cá ngoài đo thẳng lên 5 thốn, bờ trước xương mác", chu_tri: "Đau mắt, giảm thị lực, đau cẳng chân" },
    { stt: 287, ma_who: "GB38", kinh: "Kinh Đởm", ten: "Dương Phụ", vi_tri: "Mặt ngoài cẳng chân, từ đỉnh mắt cá ngoài đo lên 4 thốn, bờ trước xương mác", chu_tri: "Đau nửa đầu, đau họng, đau ngực sườn, đau cổ chân" },
    { stt: 288, ma_who: "GB39", kinh: "Kinh Đởm", ten: "Huyền Chung", vi_tri: "Mặt ngoài cẳng chân, từ đỉnh mắt cá ngoài đo thẳng lên 3 thốn, giữa bờ sau xương mác và gân cơ bám", chu_tri: "Liệt chi dưới, cứng cổ gáy, đau thần kinh tọa" },
    { stt: 289, ma_who: "GB40", kinh: "Kinh Đởm", ten: "Khâu Khư", vi_tri: "Chỗ lõm phía dưới trước mắt cá ngoài chân", chu_tri: "Đau khớp cổ chân, đau hông sườn, sưng đỏ mắt" },
    { stt: 290, ma_who: "GB41", kinh: "Kinh Đởm", ten: "Túc Lâm Khấp", vi_tri: "Mu bàn chân, chỗ lõm phía sau khớp bàn - ngón chân thứ 4 và 5", chu_tri: "Đau đầu, đau hông sườn, kinh nguyệt không đều, tắc sữa" },
    { stt: 291, ma_who: "GB42", kinh: "Kinh Đởm", ten: "Địa Ngũ Hội", vi_tri: "Mu bàn chân, chỗ lõm giữa xương bàn chân 4 và 5, trước Túc Lâm Khấp 0.5 thốn", chu_tri: "Sưng đau mu bàn chân, viêm tuyến vú, đau mắt" },
    { stt: 292, ma_who: "GB43", kinh: "Kinh Đởm", ten: "Hiệp Khê", vi_tri: "Mu bàn chân, kẽ giữa ngón chân 4 và 5 đo lên 0.5 thốn", chu_tri: "Đau đầu, chóng mặt, ù tai, sưng họng, đau ngực sườn" },
    { stt: 293, ma_who: "GB44", kinh: "Kinh Đởm", ten: "Túc Khiếu Âm", vi_tri: "Bờ ngoài ngón chân thứ 4, cách góc móng chân 0.1 thốn", chu_tri: "Đau đầu, đau hông sườn, sưng họng, sốt cao" },

    // --- KINH TÚC QUYẾT ÂM CAN (14 huyệt) ---
    { stt: 294, ma_who: "LR1", kinh: "Kinh Can", ten: "Đại Đôn", vi_tri: "Bờ ngoài ngón chân cái, cách góc móng chân 0.1 thốn", chu_tri: "Sa tử cung, thoát vị bẹn, băng lậu, tiểu dắt" },
    { stt: 295, ma_who: "LR2", kinh: "Kinh Can", ten: "Hành Gian", vi_tri: "Mu bàn chân, chỗ kẽ giữa ngón chân 1 và 2 đo lên 0.5 thốn", chu_tri: "Đau đầu, mắt đỏ sưng, kinh nguyệt nhiều, mất ngủ" },
    { stt: 296, ma_who: "LR3", kinh: "Kinh Can", ten: "Thái Xung", vi_tri: "Mu bàn chân, từ kẽ ngón chân 1-2 đo lên 1.5 thốn, chỗ lõm giữa hai xương bàn ngón 1 và 2", chu_tri: "Tăng huyết áp, nhức đầu, cáu gắt, đau hông sườn, đột quỵ" },
    { stt: 297, ma_who: "LR4", kinh: "Kinh Can", ten: "Trung Phong", vi_tri: "Cổ chân, chỗ lõm phía trước mắt cá trong chân 1 thốn, sát gân cơ cẳng chân trước", chu_tri: "Đau sưng cơ quan sinh dục, đái dắt, di tinh, đau cổ chân" },
    { stt: 298, ma_who: "LR5", kinh: "Kinh Can", ten: "Lãi Câu", vi_tri: "Mặt trong cẳng chân, từ đỉnh mắt cá trong đo lên 5 thốn, sát bờ sau xương chày", chu_tri: "Ngứa bộ phận sinh dục, khí hư, tiểu khó" },
    { stt: 299, ma_who: "LR6", kinh: "Kinh Can", ten: "Trung Đô", vi_tri: "Mặt trong cẳng chân, từ đỉnh mắt cá trong đo lên 7 thốn, sát bờ sau xương chày", chu_tri: "Đau bụng dưới, tiêu chảy, băng lậu, đau cẳng chân" },
    { stt: 300, ma_who: "LR7", kinh: "Kinh Can", ten: "Tất Quan", vi_tri: "Mặt trong cẳng chân, dưới lồi cầu trong xương chày (Âm Lăng Tuyền) sau 1 thốn", chu_tri: "Đau sưng khớp gối, hạn chế vận động chân" },
    { stt: 301, ma_who: "LR8", kinh: "Kinh Can", ten: "Khúc Tuyền", vi_tri: "Mặt trong gối, chỗ lõm đầu trong nếp gấp khoeo chân khi co gối", chu_tri: "Đau khớp gối, đau cơ quan sinh dục, di tinh, tiểu khó" },
    { stt: 302, ma_who: "LR9", kinh: "Kinh Can", ten: "Âm Bao", vi_tri: "Mặt trong đùi, trên lồi cầu trong xương đùi 4 thốn, giữa cơ may và cơ khép dài", chu_tri: "Đau bụng dưới, kinh nguyệt không đều, bí tiểu" },
    { stt: 303, ma_who: "LR10", kinh: "Kinh Can", ten: "Ngũ Lý (Can)", vi_tri: "Mặt trong đùi, dưới nếp gấp bẹn 3 thốn, sát bờ trong cơ lược", chu_tri: "Bí tiểu, đái dầm, sưng đau bẹn" },
    { stt: 304, ma_who: "LR11", kinh: "Kinh Can", ten: "Âm Liêm", vi_tri: "Mặt trong đùi, dưới nếp gấp bẹn 2 thốn, sát bờ trong cơ lược", chu_tri: "Kinh nguyệt không đều, khí hư, đau đùi bẹn" },
    { stt: 305, ma_who: "LR12", kinh: "Kinh Can", ten: "Cấp Mạch", vi_tri: "Vùng bẹn, bờ dưới xương mu, cách đường giữa bụng 2.5 thốn", chu_tri: "Đau bộ phận sinh dục, sa tử cung, thoát vị bẹn" },
    { stt: 306, ma_who: "LR13", kinh: "Kinh Can", ten: "Chương Môn", vi_tri: "Thành bụng bên, bờ dưới đầu tự do xương sườn thứ 11", chu_tri: "Đau bụng, đầy trướng, tiêu chảy, đau hông sườn" },
    { stt: 307, ma_who: "LR14", kinh: "Kinh Can", ten: "Kỳ Môn", vi_tri: "Thành ngực trước, khoang liên sườn 6, thẳng dưới núm vú", chu_tri: "Đau tức ngực sườn, viêm gan, nôn mửa, nấc cục" },

    // --- MẠCH NHÂM (24 huyệt) ---
    { stt: 308, ma_who: "CV1", kinh: "Mạch Nhâm", ten: "Hội Âm", vi_tri: "Chính giữa vùng tầng sinh môn (giữa hậu môn và cơ quan sinh dục)", chu_tri: "Cấp cứu đuối nước, di tinh, đái dắt, ngứa âm hộ, trĩ" },
    { stt: 309, ma_who: "CV2", kinh: "Mạch Nhâm", ten: "Khúc Cốt", vi_tri: "Chính giữa bờ trên xương mu", chu_tri: "Di tinh, liệt dương, tiểu dắt, khí hư" },
    { stt: 310, ma_who: "CV3", kinh: "Mạch Nhâm", ten: "Trung Cực", vi_tri: "Dưới rốn thẳng xuống 4 thốn, trên bờ trên xương mu 1 thốn", chu_tri: "Đái dầm, bí tiểu, di tinh, liệt dương, đau bụng kinh" },
    { stt: 311, ma_who: "CV4", kinh: "Mạch Nhâm", ten: "Quan Nguyên", vi_tri: "Dưới rốn thẳng xuống 3 thốn (trên đường giữa bụng)", chu_tri: "Suy nhược cơ thể, liệt dương, di tinh, kinh nguyệt không đều, tiêu chảy mạn" },
    { stt: 312, ma_who: "CV5", kinh: "Mạch Nhâm", ten: "Thạch Môn", vi_tri: "Dưới rốn thẳng xuống 2 thốn (trên đường giữa bụng)", chu_tri: "Trướng bụng, tiêu chảy, bí tiểu, băng lậu" },
    { stt: 313, ma_who: "CV6", kinh: "Mạch Nhâm", ten: "Khí Hải", vi_tri: "Dưới rốn thẳng xuống 1.5 thốn (trên đường giữa bụng)", chu_tri: "Đau bụng, đái dắt, suy nhược toàn thân, kinh nguyệt không đều" },
    { stt: 314, ma_who: "CV7", kinh: "Mạch Nhâm", ten: "Âm Giao", vi_tri: "Dưới rốn thẳng xuống 1 thốn (trên đường giữa bụng)", chu_tri: "Trướng bụng, đau bụng quanh rốn, khí hư, băng lậu" },
    { stt: 315, ma_who: "CV8", kinh: "Mạch Nhâm", ten: "Thần Khuyết", vi_tri: "Chính giữa rốn (Cấm châm, chỉ dùng phương pháp cứu)", chu_tri: "Đau bụng cấp, tiêu chảy mạn, choáng ngất, chân tay lạnh" },
    { stt: 316, ma_who: "CV9", kinh: "Mạch Nhâm", ten: "Thủy Phân", vi_tri: "Trên rốn thẳng lên 1 thốn (trên đường giữa bụng)", chu_tri: "Phù thũng, trướng bụng, tiêu chảy, nôn mửa" },
    { stt: 317, ma_who: "CV10", kinh: "Mạch Nhâm", ten: "Hạ Quản", vi_tri: "Trên rốn thẳng lên 2 thốn (trên đường giữa bụng)", chu_tri: "Đau dạ dày, trướng bụng, tiêu chảy, nôn mửa" },
    { stt: 318, ma_who: "CV11", kinh: "Mạch Nhâm", ten: "Kiến Lý", vi_tri: "Trên rốn thẳng lên 3 thốn (trên đường giữa bụng)", chu_tri: "Đau dạ dày, nôn mửa, trướng bụng, chán ăn" },
    { stt: 319, ma_who: "CV12", kinh: "Mạch Nhâm", ten: "Trung Quản", vi_tri: "Trên rốn thẳng lên 4 thốn (trên đường giữa bụng)", chu_tri: "Đau dạ dày, nôn mửa, đầy bụng, nấc cục, tiêu hóa kém" },
    { stt: 320, ma_who: "CV13", kinh: "Mạch Nhâm", ten: "Thượng Quản", vi_tri: "Trên rốn thẳng lên 5 thốn (trên đường giữa bụng)", chu_tri: "Đau dạ dày, nôn mửa, ợ chua, nấc cục, động kinh" },
    { stt: 321, ma_who: "CV14", kinh: "Mạch Nhâm", ten: "Cự Khuyết", vi_tri: "Trên rốn thẳng lên 6 thốn (trên đường giữa bụng)", chu_tri: "Đau vùng tim, hồi hộp, ợ chua, nôn mửa, cuồng điên" },
    { stt: 322, ma_who: "CV15", kinh: "Mạch Nhâm", ten: "Cửu Vĩ", vi_tri: "Dưới mũi ức 0.5 thốn, trên rốn 7 thốn (trên đường giữa bụng)", chu_tri: "Đau vùng tim, ho suyễn, động kinh, cuồng điên" },
    { stt: 323, ma_who: "CV16", kinh: "Mạch Nhâm", ten: "Trung Đình", vi_tri: "Ngang khoang liên sườn 5, giao điểm sụn khớp xiphoid và thân xương ức", chu_tri: "Đau ngực, nôn mửa, nghẹn cổ, nuốt khó" },
    { stt: 324, ma_who: "CV17", kinh: "Mạch Nhâm", ten: "Đản Trung", vi_tri: "Ngang khoang liên sườn 4, chính giữa xương ức (điểm nối giữa 2 núm vú ở nam)", chu_tri: "Ho, hen suyễn, đau ngực, tắc sữa, tim đập nhanh" },
    { stt: 325, ma_who: "CV18", kinh: "Mạch Nhâm", ten: "Ngọc Đường", vi_tri: "Ngang khoang liên sườn 3, trên đường giữa xương ức", chu_tri: "Ho suyễn, đau ngực, sưng họng, nuốt khó" },
    { stt: 326, ma_who: "CV19", kinh: "Mạch Nhâm", ten: "Tử Cung (Nhâm)", vi_tri: "Ngang khoang liên sườn 2, trên đường giữa xương ức", chu_tri: "Ho suyễn, đau ngực, nuốt vướng, nghẹn cổ" },
    { stt: 327, ma_who: "CV20", kinh: "Mạch Nhâm", ten: "Hoa Cái", vi_tri: "Ngang khoang liên sườn 1, trên đường giữa xương ức", chu_tri: "Ho suyễn, đau ngực, sưng đau hầu họng" },
    { stt: 328, ma_who: "CV21", kinh: "Mạch Nhâm", ten: "Toàn Cơ", vi_tri: "Giữa xương cán ức, dưới Thiên Đột (CV22) 1 thốn", chu_tri: "Ho suyễn, đau ngực, nuốt vướng nghẹn" },
    { stt: 329, ma_who: "CV22", kinh: "Mạch Nhâm", ten: "Thiên Đột", vi_tri: "Chính giữa chỗ lõm bờ trên xương ức", chu_tri: "Ho suyễn, đau họng, mất tiếng, nuốt vướng nghẹn" },
    { stt: 330, ma_who: "CV23", kinh: "Mạch Nhâm", ten: "Liêm Tuyền", vi_tri: "Vùng cổ trước, chính giữa bờ trên sụn giáp, chỗ lõm trên xương móng", chu_tri: "Mất tiếng, sưng đau họng, lưỡi dầy cứng, nuốt khó" },
    { stt: 331, ma_who: "CV24", kinh: "Mạch Nhâm", ten: "Thừa Tương", vi_tri: "Vùng mặt, chính giữa chỗ lõm rãnh môi - cằm", chu_tri: "Liệt mặt, đau răng hàm dưới, chảy dãi, sưng lợi" },

    // --- MẠCH ĐỐC (28 huyệt) ---
    { stt: 332, ma_who: "GV1", kinh: "Mạch Đốc", ten: "Trường Cường", vi_tri: "Đầu chóp xương cụt thẳng xuống 0.5 thốn", chu_tri: "Trĩ, lòi dom, táo bón, đau cột sống thắt lưng" },
    { stt: 333, ma_who: "GV2", kinh: "Mạch Đốc", ten: "Yêu Du", vi_tri: "Chính giữa chỗ lõm mỏm gai xương cùng 4", chu_tri: "Đau thắt lưng xương cùng, trĩ, đái dắt, kinh nguyệt không đều" },
    { stt: 334, ma_who: "GV3", kinh: "Mạch Đốc", ten: "Yêu Dương Quan", vi_tri: "Dưới gai đốt sống thắt lưng 4 (L4), ngang đường nối hai đỉnh mào chậu", chu_tri: "Đau thắt lưng, di tinh, liệt dương, đau thần kinh tọa" },
    { stt: 335, ma_who: "GV4", kinh: "Mạch Đốc", ten: "Mệnh Môn", vi_tri: "Dưới gai đốt sống thắt lưng 2 (L2), đối diện rốn qua cột sống", chu_tri: "Đau thắt lưng, liệt dương, di tinh, chân tay lạnh, tiểu đêm" },
    { stt: 336, ma_who: "GV5", kinh: "Mạch Đốc", ten: "Huyền Khu", vi_tri: "Dưới gai đốt sống thắt lưng 1 (L1)", chu_tri: "Đau thắt lưng, tiêu chảy, trướng bụng" },
    { stt: 337, ma_who: "GV6", kinh: "Mạch Đốc", ten: "Tích Trung", vi_tri: "Dưới gai đốt sống ngực 11 (T11)", chu_tri: "Đau cột sống thắt lưng, trướng bụng, vàng da" },
    { stt: 338, ma_who: "GV7", kinh: "Mạch Đốc", ten: "Trung Khu", vi_tri: "Dưới gai đốt sống ngực 10 (T10)", chu_tri: "Đau lưng, đau dạ dày, chán ăn" },
    { stt: 339, ma_who: "GV8", kinh: "Mạch Đốc", ten: "Cân Súc", vi_tri: "Dưới gai đốt sống ngực 9 (T9)", chu_tri: "Đau lưng, đau dạ dày, co giật, nôn mửa" },
    { stt: 340, ma_who: "GV9", kinh: "Mạch Đốc", ten: "Chí Dương", vi_tri: "Dưới gai đốt sống ngực 7 (T7), ngang mức góc dưới hai xương bả vai", chu_tri: "Đau ngực sườn, ho suyễn, vàng da, đau cột sống" },
    { stt: 341, ma_who: "GV10", kinh: "Mạch Đốc", ten: "Linh Đài", vi_tri: "Dưới gai đốt sống ngực 6 (T6)", chu_tri: "Ho suyễn, đau cột sống lưng, mụn nhọt độc" },
    { stt: 342, ma_who: "GV11", kinh: "Mạch Đốc", ten: "Thần Đạo", vi_tri: "Dưới gai đốt sống ngực 5 (T5)", chu_tri: "Đau tim, hồi hộp, mất ngủ, ho suyễn, động kinh" },
    { stt: 343, ma_who: "GV12", kinh: "Mạch Đốc", ten: "Thân Trụ", vi_tri: "Dưới gai đốt sống ngực 3 (T3)", chu_tri: "Ho suyễn, động kinh trẻ em, sốt cao co giật, đau lưng" },
    { stt: 344, ma_who: "GV13", kinh: "Mạch Đốc", ten: "Đào Đạo", vi_tri: "Dưới gai đốt sống ngực 1 (T1)", chu_tri: "Cảm mạo, sốt cao, ho suyễn, cứng cột sống gáy" },
    { stt: 345, ma_who: "GV14", kinh: "Mạch Đốc", ten: "Đại Chùy", vi_tri: "Chỗ lõm dưới mỏm gai đốt sống cổ 7 (C7) và trên đốt sống ngực 1", chu_tri: "Sốt cao, sốt rét, cảm cúm, ho suyễn, cứng cổ gáy" },
    { stt: 346, ma_who: "GV15", kinh: "Mạch Đốc", ten: "Á Môn", vi_tri: "Chính giữa gáy, dưới u chẩm đo xuống 0.5 thốn", chu_tri: "Mất tiếng, nói ngọng, cứng lưỡi, liệt nửa người" },
    { stt: 347, ma_who: "GV16", kinh: "Mạch Đốc", ten: "Phong Phủ", vi_tri: "Chính giữa gáy, trên Á Môn (GV15) 0.5 thốn, ngay chỗ lõm dưới u chẩm ngoài", chu_tri: "Đau đầu, cứng cổ gáy, trúng phong, liệt nửa người" },
    { stt: 348, ma_who: "GV17", kinh: "Mạch Đốc", ten: "Não Hộ", vi_tri: "Thẳng trên Phong Phủ (GV16) 1.5 thốn, ngay bờ trên u chẩm ngoài", chu_tri: "Đau đầu, cứng gáy, chóng mặt, động kinh" },
    { stt: 349, ma_who: "GV18", kinh: "Mạch Đốc", ten: "Cường Gian", vi_tri: "Thẳng trên Não Hộ (GV17) 1.5 thốn", chu_tri: "Đau đầu, cứng gáy, điên cuồng, động kinh" },
    { stt: 350, ma_who: "GV19", kinh: "Mạch Đốc", ten: "Hậu Đỉnh", vi_tri: "Thẳng trên Cường Gian (GV18) 1.5 thốn, sau Bách Hội (GV20) 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, cuồng điên, động kinh" },
    { stt: 351, ma_who: "GV20", kinh: "Mạch Đốc", ten: "Bách Hội", vi_tri: "Giao điểm của đường dọc chính giữa đầu và đường nối hai đỉnh vành tai", chu_tri: "Sa tử cung, sa trực tràng, trúng phong, nhức đầu, mất ngủ, chóng mặt" },
    { stt: 352, ma_who: "GV21", kinh: "Mạch Đốc", ten: "Tiền Đỉnh", vi_tri: "Trước Bách Hội (GV20) 1.5 thốn, trên đường giữa đầu", chu_tri: "Đau đầu, chóng mặt, sưng đỉnh đầu, co giật trẻ em" },
    { stt: 353, ma_who: "GV22", kinh: "Mạch Đốc", ten: "Tín Hội", vi_tri: "Trước Bách Hội (GV20) 3 thốn, nơi thóp trước trẻ em", chu_tri: "Đau đầu, chóng mặt, nghẹt mũi, động kinh" },
    { stt: 354, ma_who: "GV23", kinh: "Mạch Đốc", ten: "Thượng Tinh", vi_tri: "Trên chân tóc trán 1 thốn, chính giữa đường dọc đầu", chu_tri: "Đau trán, chảy máu cam, nghẹt mũi, đau mắt" },
    { stt: 355, ma_who: "GV24", kinh: "Mạch Đốc", ten: "Thần Đình", vi_tri: "Trên chân tóc trán 0.5 thốn, chính giữa đường dọc đầu", chu_tri: "Đau đầu, chóng mặt, chảy nước mũi, mất ngủ" },
    { stt: 356, ma_who: "GV25", kinh: "Mạch Đốc", ten: "Tố Liêu", vi_tri: "Chính giữa đầu chóp mũi", chu_tri: "Nghẹt mũi, chảy máu cam, cấp cứu ngất, hạ huyết áp" },
    { stt: 357, ma_who: "GV26", kinh: "Mạch Đốc", ten: "Nhân Trung", vi_tri: "Điểm nối 1/3 trên và 2/3 dưới của rãnh nhân trung", chu_tri: "Cấp cứu ngất, hôn mê, co giật, động kinh, méo miệng" },
    { stt: 358, ma_who: "GV27", kinh: "Mạch Đốc", ten: "Đoài Đoan", vi_tri: "Chính giữa bờ đỉnh môi trên", chu_tri: "Đau răng môi, chảy máu cam, điên cuồng" },
    { stt: 359, ma_who: "GV28", kinh: "Mạch Đốc", ten: "Ngân Giao", vi_tri: "Chính giữa nếp hãm môi trên, trong nướu răng", chu_tri: "Sưng đau nướu răng, đau mũi, ngứa mắt" },

    // --- KỲ HUYỆT (Huyệt Ngoài Kinh - 33 huyệt) ---
    { stt: 360, ma_who: "EX-HN1", kinh: "Kỳ Huyệt", ten: "Tứ Thần Thông", vi_tri: "Bốn huyệt xung quanh Bách Hội (GV20), cách Bách Hội 1 thốn (Tiền, Hậu, Tả, Hữu)", chu_tri: "Đau đầu, chóng mặt, mất ngủ, giảm trí nhớ, động kinh" },
    { stt: 361, ma_who: "EX-HN3", kinh: "Kỳ Huyệt", ten: "Ấn Đường", vi_tri: "Điểm chính giữa đường nối hai đầu trong lông mày", chu_tri: "Đau đầu vùng trán, nghẹt mũi, chảy máu cam, mất ngủ, giải căng thẳng" },
    { stt: 362, ma_who: "EX-HN5", kinh: "Kỳ Huyệt", ten: "Thái Dương", vi_tri: "Chỗ lõm phía sau điểm giữa đường nối đuôi lông mày và khóe mắt ngoài 1 thốn", chu_tri: "Đau nửa đầu, đau mắt đỏ, cảm mạo, liệt mặt" },
    { stt: 363, ma_who: "EX-HN4", kinh: "Kỳ Huyệt", ten: "Ngư Yêu", vi_tri: "Chính giữa lông mày, thẳng trên đồng tử mắt", chu_tri: "Giật mi mắt, sụp mi, đau mắt đỏ, đau trán" },
    { stt: 364, ma_who: "EX-HN7", kinh: "Kỳ Huyệt", ten: "Cầu Hậu", vi_tri: "Bờ dưới hốc mắt, điểm nối 1/4 ngoài và 3/4 trong", chu_tri: "Cận thị, teo thần kinh thị giác, viễn thị, đục thủy tinh thể" },
    { stt: 365, ma_who: "EX-HN8", kinh: "Kỳ Huyệt", ten: "Tỵ Thông", vi_tri: "Chỗ lõm đầu trên rãnh mũi - má (phía trên huyệt Nghinh Hương)", chu_tri: "Viêm mũi dị ứng, nghẹt mũi, polip mũi" },
    { stt: 366, ma_who: "EX-HN12", kinh: "Kỳ Huyệt", ten: "Kim Tân", vi_tri: "Dưới lưỡi, bên trái tĩnh mạch hãm lưỡi", chu_tri: "Loét miệng, lưỡi sưng cứng, nôn mửa, tiêu khát" },
    { stt: 367, ma_who: "EX-HN13", kinh: "Kỳ Huyệt", ten: "Ngọc Dịch", vi_tri: "Dưới lưỡi, bên phải tĩnh mạch hãm lưỡi", chu_tri: "Loét miệng, mất tiếng, tiêu khát, nôn mửa" },
    { stt: 368, ma_who: "EX-HN16", kinh: "Kỳ Huyệt", ten: "An Miên", vi_tri: "Điểm giữa huyệt Ế Phong (TE17) và Phong Trì (GB20)", chu_tri: "Mất ngủ, chóng mặt, đau đầu, tâm thần cuồng" },
    { stt: 369, ma_who: "EX-HN15", kinh: "Kỳ Huyệt", ten: "Bách Lao", vi_tri: "Từ Đại Chùy (GV14) đo thẳng lên 2 thốn, đo ngang ra 1 thốn", chu_tri: "Ho lao, vẹo cổ, mồ hôi trộm, đau cổ gáy" },
    { stt: 370, ma_who: "EX-B1", kinh: "Kỳ Huyệt", ten: "Định Suyễn", vi_tri: "Dưới gai đốt sống cổ 7 (Đại Chùy) đo ngang ra 0.5 thốn", chu_tri: "Hen suyễn, ho, đau vai gáy, gập cứng cổ" },
    { stt: 371, ma_who: "EX-B2", kinh: "Kỳ Huyệt", ten: "Hoa Đà Giáp Tích", vi_tri: "28 cặp huyệt hai bên cột sống từ C1 đến S4, cách đường giữa 0.5 thốn", chu_tri: "Điều trị bệnh lý tạng phủ tương ứng, đau cột sống" },
    { stt: 372, ma_who: "EX-B3", kinh: "Kỳ Huyệt", ten: "Vị Quản Hạ Du", vi_tri: "Dưới gai đốt sống ngực 8 đo ngang ra 1.5 thốn (Tụy Du)", chu_tri: "Đái tháo đường (tiêu khát), đau dạ dày, đau ngực sườn" },
    { stt: 373, ma_who: "EX-B7", kinh: "Kỳ Huyệt", ten: "Yêu Nhãn", vi_tri: "Dưới gai đốt sống thắt lưng 4 đo ngang ra 3.5 thốn, chỗ lõm thắt lưng", chu_tri: "Đau thắt lưng mạn tính, tiểu nhiều, lao thắt lưng" },
    { stt: 374, ma_who: "EX-UE11", kinh: "Kỳ Huyệt", ten: "Thập Tuyên", vi_tri: "Chính giữa đầu 10 ngón tay, cách bờ tự do móng tay 0.1 thốn", chu_tri: "Cấp cứu sốt cao co giật, trúng phong hôn mê, tê đầu ngón tay" },
    { stt: 375, ma_who: "EX-UE9", kinh: "Kỳ Huyệt", ten: "Bát Tà", vi_tri: "Kẽ 5 ngón tay mặt mu tay, nơi tiếp giáp da mu - lòng bàn tay (8 huyệt)", chu_tri: "Tê đau ngón tay, sưng bàn tay, liệt ngón tay" },
    { stt: 376, ma_who: "EX-UE10", kinh: "Kỳ Huyệt", ten: "Tứ Phùng", vi_tri: "Mặt lòng các ngón tay 2, 3, 4, 5 tại nếp gấp khớp ngón gần", chu_tri: "Cam tích trẻ em, suy dinh dưỡng, ho suyễn" },
    { stt: 377, ma_who: "EX-LE10", kinh: "Kỳ Huyệt", ten: "Bát Phong", vi_tri: "Kẽ các ngón chân mặt mu chân (8 huyệt)", chu_tri: "Tê đau ngón chân, sưng mu bàn chân, bệnh gút" },
    { stt: 378, ma_who: "EX-CA2", kinh: "Kỳ Huyệt", ten: "Khí Hải Đan", vi_tri: "Dưới rốn 1.5 thốn (Khí Hải), đo ngang ra 3 thốn", chu_tri: "Đau bụng dưới, thoát vị bẹn, ruột thừa viêm mạn" },
    { stt: 379, ma_who: "EX-CA1", kinh: "Kỳ Huyệt", ten: "Tử Cung (Kỳ Huyệt)", vi_tri: "Dưới rốn 4 thốn (Trung Cực), đo ngang ra 3 thốn", chu_tri: "Sa tử cung, bế kinh, vô sinh nữ, đau bụng kinh" },
    { stt: 380, ma_who: "EX-UE8", kinh: "Kỳ Huyệt", ten: "Lạc Chẩm", vi_tri: "Mu bàn tay, giữa kẽ xương bàn ngón 2 và 3, đo lên 0.5 thốn", chu_tri: "Vẹo cổ cấp, đau vai gáy, đau tay" },
    { stt: 381, ma_who: "EX-UE4", kinh: "Kỳ Huyệt", ten: "Trung Khôi", vi_tri: "Chính giữa nếp gấp khớp ngón gần của ngón tay giữa", chu_tri: "Nấc cục, nôn mửa, chán ăn, ợ chua" },
    { stt: 382, ma_who: "EX-HN2", kinh: "Kỳ Huyệt", ten: "Đương Dương", vi_tri: "Thẳng trên đồng tử, vào trong chân tóc trán 1 thốn", chu_tri: "Đau đầu, cảm mạo, chóng mặt, đau mắt" },
    { stt: 383, ma_who: "EX-HN17", kinh: "Kỳ Huyệt", ten: "Cảnh Tý", vi_tri: "Bờ sau cơ ức đòn chũm, trên xương đòn 1 thốn", chu_tri: "Tê đau chi trên, liệt chi trên, đau vai gáy" },
    { stt: 384, ma_who: "EX-B4", kinh: "Kỳ Huyệt", ten: "Bĩ Căn", vi_tri: "Dưới gai đốt sống thắt lưng 1 đo ngang ra 3.5 thốn", chu_tri: "Đau thắt lưng, khối bĩ, tiêu hóa kém" },
    { stt: 385, ma_who: "EX-LE2", kinh: "Kỳ Huyệt", ten: "Bách Trùng Oa", vi_tri: "mặt trong đùi, trên huyệt Huyết Hải (SP10) 1 thốn, tức là trên bờ trên trong xương bánh chè 3 thốn.", chu_tri: "Liệt chi dưới, đau khớp gối, phong thấp" },
    { stt: 386, ma_who: "EX-CA3", kinh: "Kỳ Huyệt", ten: "Khí Môn", vi_tri: "Dưới rốn 3 thốn (Quan Nguyên), đo ngang ra 3 thốn", chu_tri: "Đau bụng kinh, bế kinh, sa tử cung, băng lậu" },
    { stt: 387, ma_who: "EX-HN18", kinh: "Kỳ Huyệt", ten: "Nhĩ Trung", vi_tri: "Chính giữa cơ hoành vành tai (ngay trên lỗ tai)", chu_tri: "Nấc cục, dạ dày co thắt, ngứa da, vàng da" },
    { stt: 388, ma_who: "EX-HN19", kinh: "Kỳ Huyệt", ten: "Thừa Mệnh", vi_tri: "Phía sau dái tai 0.5 thốn", chu_tri: "Liệt mặt, ù tai, đau răng" },
    { stt: 389, ma_who: "EX-LE7", kinh: "Kỳ Huyệt", ten: "Nội Hoài Tiêm", vi_tri: "Chỗ lõm đỉnh mắt cá trong chân", chu_tri: "Đau cổ chân, sưng bàn chân" },
    { stt: 390, ma_who: "EX-LE8", kinh: "Kỳ Huyệt",ten: "Ngoại Hoài Tiêm", vi_tri: "Chỗ lõm đỉnh mắt cá ngoài chân", chu_tri: "Đau cổ chân, vẹo cổ chân" },
    { stt: 391, ma_who: "EX-UE12", kinh: "Kỳ Huyệt", ten: "Tam Thương", vi_tri: "Ba huyệt ở bờ ngoài gốc móng ngón tay cái", chu_tri: "Sưng đau họng, sốt cao, chảy máu cam" },
    { stt: 392, ma_who: "EX-LE11", kinh: "Kỳ Huyệt", ten: "Cân Cốt Phụ", vi_tri: "Điểm giữa nếp gấp khoeo chân kéo sang hai bên 1 thốn", chu_tri: "Co rút khoeo chân, đau khớp gối" },
    { stt: 393, ma_who: "EX-LE5", kinh: "Kỳ Huyệt", ten: "Lan Vĩ", vi_tri: "Dưới Túc Tam Lý (ST36) khoảng 1.5 - 2 thốn, sát bờ ngoài xương chày (chỗ có điểm ấn đau khi viêm ruột thừa)", chu_tri: "Viêm ruột thừa cấp/mạn, trướng bụng, tiêu hóa kém, liệt chi dưới" },
    { stt: 394, ma_who: "EX-LE6", kinh: "Kỳ Huyệt", ten: "Đảm Nang", vi_tri: "Dưới Dương Lăng Tuyền (GB34) khoảng 1 - 2 thốn (chỗ có điểm ấn đau trong bệnh lý túi mật)", chu_tri: "Viêm túi mật, sỏi mật, đau hông sườn, giun chui ống mật, liệt chi dưới" },
    { stt: 395, ma_who: "EX-LE3", kinh: "Kỳ Huyệt", ten: "Nội Tất Nhãn", vi_tri: "Mặt trước gối, chỗ lõm bờ dưới trong xương bánh chè (đối diện Độc Tỵ ST35)", chu_tri: "Đau sưng khớp gối, yếu liệt chân, hạn chế co duỗi gối" },

];

// --- HÀM HỢP NHẤT DỮ LIỆU TẤT CẢ 3 ĐỢT ---
window.huyetViData = [
    ...(window.huyetViDataBatch1 || []),
    ...(window.huyetViDataBatch2 || []),
    ...(window.huyetViDataBatch3 || [])
];
console.log(`Đã hoàn tất hợp nhất toàn bộ ${window.huyetViData.length} huyệt vị chuẩn hóa WHO!`);


