window.huyetViData = [
    // --- KINH PHẾ (11 huyệt) ---
    { kinh: "Kinh Phế", ten: "Trung Phủ", vi_tri: "Khoang liên sườn 1, dưới xương đòn 1 thốn", chu_tri: "Ho, hen suyễn, đau ngực, đau vai gáy" },
    { kinh: "Kinh Phế", ten: "Vân Môn", vi_tri: "Chỗ lõm dưới xương đòn, cách đường giữa ngực 6 thốn", chu_tri: "Ho, hen suyễn, đau ngực, đau vai cẳng tay" },
    { kinh: "Kinh Phế", ten: "Thiên Phủ", vi_tri: "Mặt trong cánh tay, dưới nếp gấp nách 3 thốn", chu_tri: "Ho, hen suyễn, chảy máu cam, đau mặt trong cánh tay" },
    { kinh: "Kinh Phế", ten: "Hiệp Bạch", vi_tri: "Mặt trong cánh tay, dưới huyệt Thiên Phủ 1 thốn", chu_tri: "Ho, đau ngực, nôn mửa, đau xóc sườn" },
    { kinh: "Kinh Phế", ten: "Xích Trạch", vi_tri: "Trên nếp gấp khuỷu tay, sát bờ ngoài gân cơ nhị đầu", chu_tri: "Ho ra máu, sốt, viêm họng, đau khuỷu tay" },
    { kinh: "Kinh Phế", ten: "Khổng Tối", vi_tri: "Mặt trước cẳng tay, từ lằn chỉ cổ tay đo lên 7 thốn", chu_tri: "Ho ra máu, sưng họng, sốt không ra mồ hôi, đau khuỷu tay" },
    { kinh: "Kinh Phế", ten: "Liệt Khuyết", vi_tri: "Trên lằn chỉ cổ tay 1.5 thốn, xương quay", chu_tri: "Đau đầu, đau cổ gáy, ho, liệt mặt" },
    { kinh: "Kinh Phế", ten: "Kinh Cừ", vi_tri: "Trên lằn chỉ cổ tay 1 thốn, phía ngoài động mạch quay", chu_tri: "Ho, sốt không mồ hôi, sưng đau họng, đau cổ tay" },
    { kinh: "Kinh Phế", ten: "Thái Uyên", vi_tri: "Trên lằn chỉ cổ tay, chỗ lõm động mạch quay", chu_tri: "Ho, hen suyễn, đau ngực, viêm mạch máu" },
    { kinh: "Kinh Phế", ten: "Ngư Tế", vi_tri: "Giữa xương đốt ngón tay cái 1, ranh giới da mu-lòng bàn tay", chu_tri: "Ho ra máu, sốt, khô họng, mất tiếng, đau ngón tay cái" },
    { kinh: "Kinh Phế", ten: "Thiếu Thương", vi_tri: "Bờ ngoài ngón tay cái cách gốc móng 0.1 thốn", chu_tri: "Sốt cao, đau họng, hôn mê, trúng phong" },

    // --- KINH ĐẠI TRƯỜNG (20 huyệt) ---
    { kinh: "Kinh Đại Trường", ten: "Thương Dương", vi_tri: "Bờ ngoài ngón tay trỏ, cách gốc móng 0.1 thốn", chu_tri: "Đau họng, sốt cao, đau răng, ngón tay tê" },
    { kinh: "Kinh Đại Trường", ten: "Nhị Gian", vi_tri: "Chỗ lõm phía trước khớp ngón-bàn ngón trỏ, bờ ngoài", chu_tri: "Đau răng, đau họng, sốt, lệch miệng" },
    { kinh: "Kinh Đại Trường", ten: "Tam Gian", vi_tri: "Chỗ lõm phía sau khớp ngón-bàn ngón trỏ, bờ ngoài", chu_tri: "Đau mắt, đau răng, sưng họng, đầy bụng" },
    { kinh: "Kinh Đại Trường", ten: "Hợp Cốc", vi_tri: "Chỗ lõm giữa xương đốt ngón tay 1 và 2 (Huyệt chủ vùng mặt)", chu_tri: "Đau đầu, đau răng, sốt, liệt mặt, bế kinh" },
    { kinh: "Kinh Đại Trường", ten: "Dương Khê", vi_tri: "Chỗ lõm giữa gân cơ duỗi ngắn và duỗi dài ngón cái (hõm nách giải phẫu)", chu_tri: "Đau đầu, đau răng, mắt đỏ, đau cổ tay" },
    { kinh: "Kinh Đại Trường", ten: "Thiên Lịch", vi_tri: "Trên lằn chỉ cổ tay sau 3 thốn, trên đường nối Dương Khê - Khúc Trì", chu_tri: "Chảy máu cam, ù tai, phù thũng, đau cẳng tay" },
    { kinh: "Kinh Đại Trường", ten: "Ôn Lưu", vi_tri: "Trên lằn chỉ cổ tay sau 5 thốn, trên đường nối Dương Khê - Khúc Trì", chu_tri: "Đau ruột, sưng họng, đau vai cẳng tay, động kinh" },
    { kinh: "Kinh Đại Trường", ten: "Hạ Liêm", vi_tri: "Dưới huyệt Khúc Trì 4 thốn", chu_tri: "Đau bụng, đau khuỷu tay, vú sưng đau" },
    { kinh: "Kinh Đại Trường", ten: "Thượng Liêm", vi_tri: "Dưới huyệt Khúc Trì 3 thốn", chu_tri: "Đau cẳng tay, tê tay, đau bụng quanh rốn" },
    { kinh: "Kinh Đại Trường", ten: "Thủ Tam Lý", vi_tri: "Dưới khuỷu tay (Khúc Trì) xuống 2 thốn", chu_tri: "Đau bụng, tiêu chảy, liệt tay, đau vai" },
    { kinh: "Kinh Đại Trường", ten: "Khúc Trì", vi_tri: "Tận cùng nếp gấp khuỷu tay khi co cánh tay", chu_tri: "Sốt, tăng huyết áp, dị ứng, đau khớp khuỷu" },
    { kinh: "Kinh Đại Trường", ten: "Thủ Ngũ Lý", vi_tri: "Trên Khúc Trì 3 thốn, trên đường nối Khúc Trì - Kiên Ngung", chu_tri: "Đau cánh tay, lao hạch cổ, trướng bụng, ho" },
    { kinh: "Kinh Đại Trường", ten: "Tý Nhu", vi_tri: "Đầu dưới cơ delta, trên đường nối Khúc Trì - Kiên Ngung", chu_tri: "Đau vai cẳng tay, cổ cứng, đau mắt" },
    { kinh: "Kinh Đại Trường", ten: "Kiên Ngung", vi_tri: "Chỗ lõm phía trước dưới mỏm cùng vai", chu_tri: "Đau khớp vai, liệt chi trên, đau cổ gáy" },
    { kinh: "Kinh Đại Trường", ten: "Cự Cốt", vi_tri: "Chỗ lõm giữa đầu ngoài xương đòn và gai xương bả vai", chu_tri: "Đau vai gáy, không giơ tay lên được, lao hạch cổ" },
    { kinh: "Kinh Đại Trường", ten: "Thiên Đỉnh", vi_tri: "Bờ sau cơ ức đòn chũm, ngang mức sụn nhẫn, dưới Phù Đột 1 thốn", chu_tri: "Đau họng, mất tiếng, nuốt vướng, lao hạch cổ" },
    { kinh: "Kinh Đại Trường", ten: "Phù Đột", vi_tri: "Ngang bờ trên sụn giáp, giữa cơ ức đòn chũm", chu_tri: "Ho suyễn, đau họng, nuốt vướng, khàn tiếng" },
    { kinh: "Kinh Đại Trường", ten: "Hòa Liêu", vi_tri: "Dưới mép ngoài lỗ mũi, ngang huyệt Nhân Trung", chu_tri: "Nghẹt mũi, chảy máu cam, méo miệng, viêm mũi" },
    { kinh: "Kinh Đại Trường", ten: "Nghinh Hương", vi_tri: "Giao điểm đường ngang qua chân cánh mũi và rãnh mũi má", chu_tri: "Nghẹt mũi, viêm mũi, liệt mặt, chảy máu cam" },

    // --- KINH VỊ (43 huyệt) ---
    { kinh: "Kinh Vị", ten: "Thừa Khấp", vi_tri: "Giữa mi mắt dưới thẳng xuống, sát xương hốc mắt", chu_tri: "Viêm màng tiếp hợp, liệt mặt, cận thị" },
    { kinh: "Kinh Vị", ten: "Tứ Bạch", vi_tri: "Dưới hốc mắt thẳng xuống 0.7 thốn, tại lỗ dưới hốc mắt", chu_tri: "Đau mắt, giật mi mắt, liệt mặt, đau dây V" },
    { kinh: "Kinh Vị", ten: "Cự Liêu", vi_tri: "Thẳng từ đồng tử xuống, ngang chân cánh mũi", chu_tri: "Liệt mặt, giật mi mắt, đau răng hàm trên, sưng má" },
    { kinh: "Kinh Vị", ten: "Địa Thương", vi_tri: "Cách khóe miệng 0.4 thốn về phía ngoài", chu_tri: "Liệt mặt, đau dây thần kinh V, chảy dãi" },
    { kinh: "Kinh Vị", ten: "Đại Nghênh", vi_tri: "Trước góc hàm 1.3 thốn, chỗ lõm trước cơ cắn", chu_tri: "Cứng hàm, đau răng, sưng má, lệch miệng" },
    { kinh: "Kinh Vị", ten: "Giáp Xa", vi_tri: "Chỗ cơ cắn nổi lên cao nhất khi cắn chặt răng", chu_tri: "Liệt mặt, đau răng, quai bị, cứng hàm" },
    { kinh: "Kinh Vị", ten: "Hạ Quan", vi_tri: "Chỗ lõm dưới xương gò má, trước tai", chu_tri: "Đau tai, đau răng, viêm khớp thái dương hàm" },
    { kinh: "Kinh Vị", ten: "Đầu Duy", vi_tri: "Góc tóc trán, cách mép tóc 0.5 thốn", chu_tri: "Đau đầu, đau nửa đầu, đau mắt, chóng mặt" },
    { kinh: "Kinh Vị", ten: "Nhân Nghênh", vi_tri: "Bên bờ sụn giáp, sát động mạch cảnh (Tử huyệt)", chu_tri: "Tăng huyết áp, hen suyễn, đau họng, mất tiếng" },
    { kinh: "Kinh Vị", ten: "Thủy Đột", vi_tri: "Bờ trước cơ ức đòn chũm, giữa Phù Đột và Khí Xá", chu_tri: "Đau họng, ho suyễn, bướu cổ" },
    { kinh: "Kinh Vị", ten: "Khí Xá", vi_tri: "Bờ trên xương đòn, giữa hai đầu cơ ức đòn chũm", chu_tri: "Đau họng, cản trở nuốt, ho suyễn, vẹo cổ" },
    { kinh: "Kinh Vị", ten: "Khuyết Bồn", vi_tri: "Chỗ lõm bờ trên xương đòn, thẳng hàng núm vú", chu_tri: "Ho, hen suyễn, đau ngực, sưng hạch cổ" },
    { kinh: "Kinh Vị", ten: "Khí Hộ", vi_tri: "Dưới xương đòn, cách đường giữa ngực 4 thốn", chu_tri: "Ho, hen suyễn, đau ngực sườn, nấc cục" },
    { kinh: "Kinh Vị", ten: "Khố Phòng", vi_tri: "Khoang liên sườn 1, cách đường giữa ngực 4 thốn", chu_tri: "Ho suyễn, đau tức ngực, khạc ra đờm mủ" },
    { kinh: "Kinh Vị", ten: "Ốc Ế", vi_tri: "Khoang liên sườn 2, cách đường giữa ngực 4 thốn", chu_tri: "Ho suyễn, đau tức ngực, viêm tuyến vú" },
    { kinh: "Kinh Vị", ten: "Ưng Cụ", vi_tri: "Khoang liên sườn 3, cách đường giữa ngực 4 thốn", chu_tri: "Đau ngực sườn, ho suyễn, sưng vú" },
    { kinh: "Kinh Vị", ten: "Nhũ Trung", vi_tri: "Chính giữa núm vú (Chỉ dùng làm mốc giải phẫu, cấm châm cứu)", chu_tri: "Mốc đo kích thước vùng ngực" },
    { kinh: "Kinh Vị", ten: "Nhũ Căn", vi_tri: "Khoang liên sườn 5, thẳng dưới núm vú", chu_tri: "Viêm tuyến vú, thiếu sữa, đau ngực, ho suyễn" },
    { kinh: "Kinh Vị", ten: "Bất Dung", vi_tri: "Trên rốn 6 thốn, đo ngang ra 2 thốn", chu_tri: "Đau dạ dày, nôn mửa, chán ăn, trướng bụng" },
    { kinh: "Kinh Vị", ten: "Thừa Mãn", vi_tri: "Trên rốn 5 thốn, đo ngang ra 2 thốn", chu_tri: "Đau dạ dày, ợ chua, trướng bụng, nôn mửa" },
    { kinh: "Kinh Vị", ten: "Lương Môn", vi_tri: "Trên rốn 4 thốn, đo ngang ra 2 thốn", chu_tri: "Đau dạ dày, nôn mửa, tiêu chảy, chán ăn" },
    { kinh: "Kinh Vị", ten: "Quan Môn", vi_tri: "Trên rốn 3 thốn, đo ngang ra 2 thốn", chu_tri: "Bụng trướng, đau dạ dày, tiêu chảy" },
    { kinh: "Kinh Vị", ten: "Thái Ất", vi_tri: "Trên rốn 2 thốn, đo ngang ra 2 thốn", chu_tri: "Đau dạ dày, an thần, cuồng điên, trướng bụng" },
    { kinh: "Kinh Vị", ten: "Hoạt Nhục Môn", vi_tri: "Trên rốn 1 thốn, đo ngang ra 2 thốn", chu_tri: "Đau dạ dày, nôn mửa, lưỡi cứng, điên cuồng" },
    { kinh: "Kinh Vị", ten: "Thiên Khu", vi_tri: "Từ rốn đo ngang ra 2 thốn về hai bên", chu_tri: "Đau bụng, táo bón, tiêu chảy, kiết lỵ" },
    { kinh: "Kinh Vị", ten: "Ngoại Lăng", vi_tri: "Dưới rốn 1 thốn, đo ngang ra 2 thốn", chu_tri: "Đau bụng dưới, thoát vị bẹn, đau kinh" },
    { kinh: "Kinh Vị", ten: "Đại Cự", vi_tri: "Dưới rốn 2 thốn, đo ngang ra 2 thốn", chu_tri: "Bí tiểu, đau bụng dưới, di tinh, liệt dương" },
    { kinh: "Kinh Vị", ten: "Thủy Đạo", vi_tri: "Dưới rốn 3 thốn, đo ngang ra 2 thốn", chu_tri: "Phù thũng, bí tiểu, đau bụng dưới, viêm tinh hoàn" },
    { kinh: "Kinh Vị", ten: "Quy Lai", vi_tri: "Dưới rốn 4 thốn, đo ngang ra 2 thốn", chu_tri: "Đau bụng kinh, sa tử cung, thoát vị bẹn, di tinh" },
    { kinh: "Kinh Vị", ten: "Khí Xung", vi_tri: "Bờ trên xương mu, đo ngang ra 2 thốn", chu_tri: "Đau sưng sinh dục, kinh nguyệt không đều, thoát vị" },
    { kinh: "Kinh Vị", ten: "Bễ Quan", vi_tri: "Chỗ lõm phía dưới buộc dây lưng, thẳng nếp bẹn xuống", chu_tri: "Liệt chi dưới, đau háng, đau gối" },
    { kinh: "Kinh Vị", ten: "Phục Thỏ", vi_tri: "Từ bờ trên ngoài xương bánh chè đo thẳng lên 6 thốn", chu_tri: "Liệt chi dưới, đau đùi, đau gối, thoát vị" },
    { kinh: "Kinh Vị", ten: "Âm Thị", vi_tri: "Từ bờ trên ngoài xương bánh chè đo thẳng lên 3 thốn", chu_tri: "Liệt chân, đau gối, liệt đùi, lạnh gối" },
    { kinh: "Kinh Vị", ten: "Lương Khâu", vi_tri: "Từ bờ trên ngoài xương bánh chè đo thẳng lên 2 thốn", chu_tri: "Đau dạ dày cấp, viêm tuyến vú, đau khớp gối" },
    { kinh: "Kinh Vị", ten: "Độc Tỵ", vi_tri: "Chỗ lõm phía dưới ngoài xương bánh chè", chu_tri: "Đau khớp gối, sưng gối, hạn chế vận động chân" },
    { kinh: "Kinh Vị", ten: "Túc Tam Lý", vi_tri: "Dưới mắt gối ngoài 3 thốn, cách mào xương chày 1 khoát ngón tay", chu_tri: "Đau dạ dày, tiêu hóa kém, suy nhược cơ thể, tăng miễn dịch" },
    { kinh: "Kinh Vị", ten: "Thượng Cự Hư", vi_tri: "Dưới Túc Tam Lý 3 thốn, cách mào xương chày 1 khoát ngón tay", chu_tri: "Đau bụng, tiêu chảy, ruột thừa viêm, liệt chi dưới" },
    { kinh: "Kinh Vị", ten: "Điều Khẩu", vi_tri: "Dưới Túc Tam Lý 2 thốn, cách mào xương chày 1 khoát ngón tay", chu_tri: "Liệt chi dưới, đau gối cổ chân, đau vai" },
    { kinh: "Kinh Vị", ten: "Hạ Cự Hư", vi_tri: "Dưới Túc Tam Lý 6 thốn, dưới Thượng Cự Hư 3 thốn", chu_tri: "Đau bụng dưới, tiêu chảy, đau ngực vú, liệt chân" },
    { kinh: "Kinh Vị", ten: "Phong Long", vi_tri: "Từ mắt cá ngoài đo lên 8 thốn, giữa bắp chân", chu_tri: "Hóa đờm trị ho, đau đầu, chóng mặt, liệt chi dưới" },
    { kinh: "Kinh Vị", ten: "Giải Khê", vi_tri: "Chỗ lõm giữa nếp gấp cổ chân, giữa 2 gân cơ", chu_tri: "Đau cổ chân, đau đầu, đầy bụng, đại tiện khó" },
    { kinh: "Kinh Vị", ten: "Xung Dương", vi_tri: "Chỗ lõm cao nhất trên mu bàn chân, chỗ động mạch mu chân đập", chu_tri: "Đau mu bàn chân, liệt mặt, đau răng, đau dạ dày" },
    { kinh: "Kinh Vị", ten: "Hãm Cốc", vi_tri: "Chỗ lõm giữa xương đốt ngón chân 2 và 3, phía sau khớp ngón-bàn", chu_tri: "Phù mặt, đau bụng, sốt không mồ hôi, đau mu chân" },
    { kinh: "Kinh Vị", ten: "Nội Đình", vi_tri: "Kẽ ngón chân 2 và 3 đo lên 0.5 thốn", chu_tri: "Đau răng, đau họng, sốt, chảy máu cam, đau dạ dày" },
    { kinh: "Kinh Vị", ten: "Lệ Đoài", vi_tri: "Bờ ngoài góc móng chân thứ 2 cách 0.1 thốn", chu_tri: "Sốt cao, đau răng, mất ngủ, mơ nhiều, điên cuồng" },

    // --- KINH TỲ (21 huyệt) ---
    { kinh: "Kinh Tỳ", ten: "Ẩn Bạch", vi_tri: "Bờ trong góc móng chân cái cách gốc móng 0.1 thốn", chu_tri: "Băng lậu, rong kinh, đau bụng, điên cuồng" },
    { kinh: "Kinh Tỳ", ten: "Đại Đô", vi_tri: "Chỗ lõm phía trước khớp ngón-bàn ngón chân cái, ranh giới da", chu_tri: "Đầy bụng, đau dạ dày, sốt không ra mồ hôi, nôn mửa" },
    { kinh: "Kinh Tỳ", ten: "Thái Bạch", vi_tri: "Chỗ lõm phía sau dưới đầu xương đốt ngón chân 1", chu_tri: "Đau dạ dày, đầy bụng, tiêu chảy, nôn mửa" },
    { kinh: "Kinh Tỳ", ten: "Công Tôn", vi_tri: "Chỗ lõm bờ trong bàn chân, sau xương đốt ngón 1 khoảng 1 thốn", chu_tri: "Đau bụng cấp, nôn mửa, viêm dạ dày ruột" },
    { kinh: "Kinh Tỳ", ten: "Thương Khâu", vi_tri: "Chỗ lõm phía dưới trước mắt cá trong chân", chu_tri: "Đầy bụng, tiêu chảy, đau cổ chân, lưỡi cứng" },
    { kinh: "Kinh Tỳ", ten: "Tam Âm Giao", vi_tri: "Từ đỉnh mắt cá trong đo lên 3 thốn, sát bờ sau xương chày", chu_tri: "Mất ngủ, kinh nguyệt không đều, di tinh, tiểu khó" },
    { kinh: "Kinh Tỳ", ten: "Lậu Cốc", vi_tri: "Từ đỉnh mắt cá trong đo lên 6 thốn, sát bờ sau xương chày", chu_tri: "Trướng bụng, phù thũng, tiểu khó, lạnh chi dưới" },
    { kinh: "Kinh Tỳ", ten: "Địa Cơ", vi_tri: "Dưới Âm Lăng Tuyền 3 thốn, sát bờ sau xương chày", chu_tri: "Đau bụng kinh, kinh nguyệt không đều, di tinh, tiêu chảy" },
    { kinh: "Kinh Tỳ", ten: "Âm Lăng Tuyền", vi_tri: "Chỗ lõm dưới đầu xương chày, mặt trong bắp chân", chu_tri: "Phù thũng, tiểu khó, đau gối, di tinh" },
    { kinh: "Kinh Tỳ", ten: "Huyết Hải", vi_tri: "Từ góc trên trong xương bánh chè đo lên 2 thốn", chu_tri: "Kinh nguyệt không đều, mề đay, mẩn ngứa, thiếu máu" },
    { kinh: "Kinh Tỳ", ten: "Cơ Môn", vi_tri: "Mặt trong đùi, trên Âm Lăng Tuyền 6 thốn", chu_tri: "Bí tiểu, đái dầm, sưng đau bẹn" },
    { kinh: "Kinh Tỳ", ten: "Xung Môn", vi_tri: "Chính giữa nếp bẹn, phía ngoài động mạch đùi", chu_tri: "Đau bụng dưới, thoát vị, bí tiểu, khí hư" },
    { kinh: "Kinh Tỳ", ten: "Phủ Xá", vi_tri: "Trên Xung Môn 0.7 thốn, cách đường giữa bụng 4 thốn", chu_tri: "Đau bụng quặn, thoát vị, đau trĩ" },
    { kinh: "Kinh Tỳ", ten: "Phúc Kết", vi_tri: "Dưới Đại Hoành 1.3 thốn, cách đường giữa bụng 4 thốn", chu_tri: "Đau bụng quanh rốn, tiêu chảy, thoát vị" },
    { kinh: "Kinh Tỳ", ten: "Đại Hoành", vi_tri: "Ngang hàng với rốn, cách rốn 4 thốn", chu_tri: "Táo bón lâu ngày, tiêu chảy, đau bụng dưới" },
    { kinh: "Kinh Tỳ", ten: "Phúc Ai", vi_tri: "Trên Đại Hoành 3 thốn, cách đường giữa bụng 4 thốn", chu_tri: "Đau bụng, tiêu chảy, táo bón, ăn không tiêu" },
    { kinh: "Kinh Tỳ", ten: "Thực Đậu", vi_tri: "Khoang liên sườn 5, cách đường giữa ngực 6 thốn", chu_tri: "Đau trướng ngực sườn, ợ chua, nôn mửa" },
    { kinh: "Kinh Tỳ", ten: "Thiên Khê", vi_tri: "Khoang liên sườn 4, cách đường giữa ngực 6 thốn", chu_tri: "Ho suyễn, đau ngực, thiếu sữa, viêm tuyến vú" },
    { kinh: "Kinh Tỳ", ten: "Hung Hương", vi_tri: "Khoang liên sườn 3, cách đường giữa ngực 6 thốn", chu_tri: "Đau ngực sườn, ho suyễn, không xoay người được" },
    { kinh: "Kinh Tỳ", ten: "Chu Vinh", vi_tri: "Khoang liên sườn 2, cách đường giữa ngực 6 thốn", chu_tri: "Ho suyễn, đau tức ngực, nuốt vướng" },
    { kinh: "Kinh Tỳ", ten: "Đại Bao", vi_tri: "Khoang liên sườn 6, trên đường nách giữa", chu_tri: "Đau tức ngực sườn, suy nhược toàn thân, hen suyễn" },

    // --- KINH TÂM (9 huyệt) ---
    { kinh: "Kinh Tâm", ten: "Cực Tuyền", vi_tri: "Chính giữa hố nách, sát động mạch nách", chu_tri: "Đau tim, hồi hộp, đau thắt ngực, liệt tay" },
    { kinh: "Kinh Tâm", ten: "Thanh Linh", vi_tri: "Mặt trong cánh tay, trên Thiếu Hải 3 thốn", chu_tri: "Đau tim, đau cánh tay, mắt vàng, đau sườn" },
    { kinh: "Kinh Tâm", ten: "Thiếu Hải", vi_tri: "Chỗ lõm đầu trong nếp gấp khuỷu tay khi co khuỷu", chu_tri: "Đau vùng tim, tê tay, run tay, lao hạch" },
    { kinh: "Kinh Tâm", ten: "Linh Đạo", vi_tri: "Trên lằn chỉ cổ tay 1.5 thốn, sát bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Đau vùng tim, khàn tiếng đột ngột, co rút cẳng tay" },
    { kinh: "Kinh Tâm", ten: "Thông Lý", vi_tri: "Trên lằn chỉ cổ tay 1 thốn, sát bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Hồi hộp, mất tiếng, lưỡi cứng không nói được, đau cổ tay" },
    { kinh: "Kinh Tâm", ten: "Âm Khích", vi_tri: "Từ huyệt Thần Môn đo thẳng lên 0.5 thốn", chu_tri: "Đau tim, ra mồ hôi trộm, nôn ra máu" },
    { kinh: "Kinh Tâm", ten: "Thần Môn", vi_tri: "Trên lằn chỉ cổ tay, chỗ lõm bờ ngoài gân cơ gấp cổ tay trụ", chu_tri: "Mất ngủ, hồi hộp, hay quên, điên cuồng, đau tim" },
    { kinh: "Kinh Tâm", ten: "Thiếu Phủ", vi_tri: "Lòng bàn tay, giữa xương đốt ngón 4 và 5 (chỗ đầu ngón út chạm vào khi nắm tay)", chu_tri: "Hồi hộp, đau tim, tiểu khó, ngứa bộ phận sinh dục" },
    { kinh: "Kinh Tâm", ten: "Thiếu Xung", vi_tri: "Bờ ngoài ngón tay út, cách góc móng tay 0.1 thốn", chu_tri: "Trúng phong hôn mê, sốt cao, hồi hộp, đau ngực" },

    // --- KINH TIỂU TRƯỜNG (19 huyệt) ---
    { kinh: "Kinh Tiểu Trường", ten: "Thiếu Trạch", vi_tri: "Bờ ngoài ngón út, cách góc móng tay 0.1 thốn", chu_tri: "Sốt cao, tắc sữa, đau đầu, đau mắt" },
    { kinh: "Kinh Tiểu Trường", ten: "Tiền Cốc", vi_tri: "Chỗ lõm phía trước khớp ngón-bàn tay 5, bờ ngoài", chu_tri: "Sốt không mồ hôi, tắc sữa, đau đầu, ù tai" },
    { kinh: "Kinh Tiểu Trường", ten: "Hậu Khê", vi_tri: "Chỗ lõm phía sau khớp ngón-bàn tay 5 khi nắm tay lại", chu_tri: "Đau cổ gáy, ù tai, động kinh, ra mồ hôi trộm" },
    { kinh: "Kinh Tiểu Trường", ten: "Uyển Cốt", vi_tri: "Chỗ lõm bờ ngoài mu bàn tay trước xương tháp", chu_tri: "Đau cổ tay, hoàng đản, sốt không ra mồ hôi" },
    { kinh: "Kinh Tiểu Trường", ten: "Dương Cốc", vi_tri: "Chỗ lõm sát bờ ngoài cổ tay, giữa xương mỏm trâm trụ và xương tháp", chu_tri: "Đau cổ tay, sưng họng, ù tai, sốt cao" },
    { kinh: "Kinh Tiểu Trường", ten: "Dưỡng Lão", vi_tri: "Chỗ lõm phía trên mỏm trâm xương trụ khi xoay cẳng tay", chu_tri: "Giảm thị lực, đau vai cẳng tay, đau thắt lưng" },
    { kinh: "Kinh Tiểu Trường", ten: "Chi Chánh", vi_tri: "Trên Dương Cốc 5 thốn, đường nối Dương Cốc - Tiểu Hải", chu_tri: "Cổ cứng, đau khuỷu tay, điên cuồng, mụn nhọt" },
    { kinh: "Kinh Tiểu Trường", ten: "Tiểu Hải", vi_tri: "Chỗ lõm giữa mỏm khuỷu xương trụ và mỏm trên củ trong xương cánh tay", chu_tri: "Đau khuỷu tay, đau cổ gáy, điên cuồng, sưng má" },
    { kinh: "Kinh Tiểu Trường", ten: "Kiên Trinh", vi_tri: "Thẳng trên nếp gấp nách sau 1 thốn khi khép tay", chu_tri: "Đau khớp vai, liệt cánh tay, trúng phong, đau bả vai" },
    { kinh: "Kinh Tiểu Trường", ten: "Nhu Du", vi_tri: "Thẳng từ nếp gấp nách sau lên, dưới bờ dưới gai xương bả vai", chu_tri: "Đau vai bả vai, yếu cẳng tay, sưng cổ" },
    { kinh: "Kinh Tiểu Trường", ten: "Thiên Tông", vi_tri: "Chính giữa hố dưới gai xương bả vai", chu_tri: "Đau vai bả vai, đau cánh tay, viêm tuyến vú" },
    { kinh: "Kinh Tiểu Trường", ten: "Bỉnh Phong", vi_tri: "Chính giữa hố trên gai xương bả vai", chu_tri: "Đau bả vai, tê vai cẳng tay, không giơ tay được" },
    { kinh: "Kinh Tiểu Trường", ten: "Khúc Viên", vi_tri: "Chỗ lõm bờ trên trong hố trên gai xương bả vai", chu_tri: "Đau nhức bả vai, cứng cổ gáy" },
    { kinh: "Kinh Tiểu Trường", ten: "Kiên Ngoại Du", vi_tri: "Dưới đốt sống ngực 1 (Đại Chùy) đo ngang ra 3 thốn", chu_tri: "Đau vai gáy, cứng cổ, liệt chi trên" },
    { kinh: "Kinh Tiểu Trường", ten: "Kiên Trung Du", vi_tri: "Dưới gai đốt sống cổ 7 (Đại Chùy) đo ngang ra 2 thốn", chu_tri: "Đau vai gáy, ho suyễn, giảm thị lực" },
    { kinh: "Kinh Tiểu Trường", ten: "Thiên Song", vi_tri: "Bờ sau cơ ức đòn chũm, ngang mức sụn giáp", chu_tri: "Ù tai, điếc tai, sưng họng, cổ cứng đau" },
    { kinh: "Kinh Tiểu Trường", ten: "Thiên Dung", vi_tri: "Phía sau góc hàm, bờ trước cơ ức đòn chũm", chu_tri: "Sưng họng, ù tai, cổ sưng đau, nghẹn cổ" },
    { kinh: "Kinh Tiểu Trường", ten: "Quyền Liêu", vi_tri: "Thẳng dưới khóe mắt ngoài, chỗ lõm bờ dưới xương gò má", chu_tri: "Liệt mặt, đau răng, giật mi mắt, vàng mắt" },
    { kinh: "Kinh Tiểu Trường", ten: "Thính Cung", vi_tri: "Chỗ lõm phía trước giữa bình tai khi mở miệng", chu_tri: "Ù tai, điếc tai, đau tai, viêm tai giữa" },

    // --- KINH BÀNG QUANG (67 huyệt) ---
    { kinh: "Kinh Bàng Quang", ten: "Tình Minh", vi_tri: "Cách khóe mắt trong 0.1 thốn về phía mũi (Tử huyệt)", chu_tri: "Cận thị, chảy nước mắt khi ra gió, viêm màng tiếp hợp" },
    { kinh: "Kinh Bàng Quang", ten: "Toản Trúc", vi_tri: "Chỗ lõm đầu trong chân mày thẳng lên", chu_tri: "Đau đầu, đau mắt, giật cơ mắt, liệt mặt" },
    { kinh: "Kinh Bàng Quang", ten: "Mông Xung", vi_tri: "Sau Thần Đình 0.5 thốn, cách đường giữa đầu 0.5 thốn", chu_tri: "Đau đầu, nghẹt mũi, co giật, mờ mắt" },
    { kinh: "Kinh Bàng Quang", ten: "Khúc Sai", vi_tri: "Trên mép tóc trán 0.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, nghẹt mũi, chảy máu cam, giảm thị lực" },
    { kinh: "Kinh Bàng Quang", ten: "Ngũ Xứ", vi_tri: "Sau Khúc Sai 0.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đỉnh đầu, chóng mặt, động kinh, mờ mắt" },
    { kinh: "Kinh Bàng Quang", ten: "Thừa Quang", vi_tri: "Sau Ngũ Xứ 1.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, nghẹt mũi, mờ mắt" },
    { kinh: "Kinh Bàng Quang", ten: "Thông Thiên", vi_tri: "Sau Thừa Quang 1.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, nghẹt mũi, chảy máu cam" },
    { kinh: "Kinh Bàng Quang", ten: "Lạc Khước", vi_tri: "Sau Thông Thiên 1.5 thốn, cách đường giữa đầu 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, điên cuồng, ù tai" },
    { kinh: "Kinh Bàng Quang", ten: "Ngọc Chẩm", vi_tri: "Ngang bờ trên u chẩm ngoài, cách đường giữa đầu 1.3 thốn", chu_tri: "Đau sau đầu, nghẹt mũi, đau mắt, chóng mặt" },
    { kinh: "Kinh Bàng Quang", ten: "Thiên Trụ", vi_tri: "Vùng tóc gáy, dưới u chẩm, ngoài mạch Đốc 1.3 thốn", chu_tri: "Đau đầu, đau vai gáy, nghẹt mũi, vẹo cổ" },
    { kinh: "Kinh Bàng Quang", ten: "Đại Trữ", vi_tri: "Dưới gai đốt sống ngực 1 đo ngang ra 1.5 thốn (Hội của cốt)", chu_tri: "Ho, sốt, đau vai gáy, đau nhức xương khớp" },
    { kinh: "Kinh Bàng Quang", ten: "Phong Môn", vi_tri: "Dưới gai đốt sống ngực 2 đo ngang ra 1.5 thốn", chu_tri: "Cảm mạo, ho suyễn, sốt, đau vai gáy" },
    { kinh: "Kinh Bàng Quang", ten: "Phế Du", vi_tri: "Dưới gai đốt sống ngực 3 đo ngang ra 1.5 thốn", chu_tri: "Ho, hen suyễn, sốt, ho ra máu, mồ hôi trộm" },
    { kinh: "Kinh Bàng Quang", ten: "Quyết Âm Du", vi_tri: "Dưới gai đốt sống ngực 4 đo ngang ra 1.5 thốn", chu_tri: "Đau tim, hồi hộp, ho suyễn, tức ngực" },
    { kinh: "Kinh Bàng Quang", ten: "Tâm Du", vi_tri: "Dưới gai đốt sống ngực 5 đo ngang ra 1.5 thốn", chu_tri: "Hồi hộp, mất ngủ, hay quên, đau tim, động kinh" },
    { kinh: "Kinh Bàng Quang", ten: "Đốc Du", vi_tri: "Dưới gai đốt sống ngực 6 đo ngang ra 1.5 thốn", chu_tri: "Đau tim, đau bụng, ho suyễn, rụng tóc" },
    { kinh: "Kinh Bàng Quang", ten: "Cách Du", vi_tri: "Dưới gai đốt sống ngực 7 đo ngang ra 1.5 thốn (Huyệt hội của huyết)", chu_tri: "Nấc cục, nôn mửa, thiếu máu, xuất huyết, ho ra máu" },
    { kinh: "Kinh Bàng Quang", ten: "Can Du", vi_tri: "Dưới gai đốt sống ngực 9 đo ngang ra 1.5 thốn", chu_tri: "Đau hông sườn, vàng da, đỏ mắt, chóng mặt" },
    { kinh: "Kinh Bàng Quang", ten: "Đảm Du", vi_tri: "Dưới gai đốt sống ngực 10 đo ngang ra 1.5 thốn", chu_tri: "Đắng miệng, vàng da, đau hông sườn, sốt rét" },
    { kinh: "Kinh Bàng Quang", ten: "Tỳ Du", vi_tri: "Dưới gai đốt sống ngực 11 đo ngang ra 1.5 thốn", chu_tri: "Đầy bụng, tiêu chảy, nôn mửa, phù thũng" },
    { kinh: "Kinh Bàng Quang", ten: "Vị Du", vi_tri: "Dưới gai đốt sống ngực 12 đo ngang ra 1.5 thốn", chu_tri: "Đau dạ dày, chướng bụng, nôn mửa, tiêu hóa kém" },
    { kinh: "Kinh Bàng Quang", ten: "Tam Tiêu Du", vi_tri: "Dưới gai đốt sống thắt lưng 1 đo ngang ra 1.5 thốn", chu_tri: "Trướng bụng, tiêu chảy, phù thũng, đau lưng" },
    { kinh: "Kinh Bàng Quang", ten: "Thận Du", vi_tri: "Dưới gai đốt sống thắt lưng 2 đo ngang ra 1.5 thốn", chu_tri: "Đau lưng, ù tai, di tinh, liệt dương, hen suyễn kinh niên" },
    { kinh: "Kinh Bàng Quang", ten: "Khí Hải Du", vi_tri: "Dưới gai đốt sống thắt lưng 3 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, trướng bụng, kinh nguyệt không đều, trĩ" },
    { kinh: "Kinh Bàng Quang", ten: "Đại Trường Du", vi_tri: "Dưới gai đốt sống thắt lưng 4 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, táo bón, tiêu chảy, liệt chi dưới" },
    { kinh: "Kinh Bàng Quang", ten: "Quan Nguyên Du", vi_tri: "Dưới gai đốt sống thắt lưng 5 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, tiêu chảy mạn, tiểu khó" },
    { kinh: "Kinh Bàng Quang", ten: "Tiểu Trường Du", vi_tri: "Dưới gai đốt sống cùng 1 đo ngang ra 1.5 thốn", chu_tri: "Đau bụng dưới, đái dắt, tiêu chảy, trĩ" },
    { kinh: "Kinh Bàng Quang", ten: "Bàng Quang Du", vi_tri: "Dưới gai đốt sống cùng 2 đo ngang ra 1.5 thốn", chu_tri: "Bí tiểu, đái dầm, tiêu chảy, đau thắt lưng" },
    { kinh: "Kinh Bàng Quang", ten: "Trung Lữ Du", vi_tri: "Dưới gai đốt sống cùng 3 đo ngang ra 1.5 thốn", chu_tri: "Đau thắt lưng, tiêu chảy, đau trĩ, đái dắt" },
    { kinh: "Kinh Bàng Quang", ten: "Bạch Hoàn Du", vi_tri: "Dưới gai đốt sống cùng 4 đo ngang ra 1.5 thốn", chu_tri: "Di tinh, di niệu, khí hư, đau thắt lưng" },
    { kinh: "Kinh Bàng Quang", ten: "Thượng Liêu", vi_tri: "Chính lỗ xương cùng thứ nhất", chu_tri: "Đau thắt lưng, di tinh, khí hư, khó đẻ" },
    { kinh: "Kinh Bàng Quang", ten: "Thứ Liêu", vi_tri: "Chính lỗ xương cùng thứ hai", chu_tri: "Đau thắt lưng, kinh nguyệt không đều, liệt chi dưới" },
    { kinh: "Kinh Bàng Quang", ten: "Trung Liêu", vi_tri: "Chính lỗ xương cùng thứ 3", chu_tri: "Đau thắt lưng, đái dắt, khí hư, táo bón" },
    { kinh: "Kinh Bàng Quang", ten: "Hạ Liêu", vi_tri: "Chính lỗ xương cùng thứ 4", chu_tri: "Đau thắt lưng, đau bụng dưới, tiểu khó, khí hư" },
    { kinh: "Kinh Bàng Quang", ten: "Hội Dương", vi_tri: "Hai bên chóp xương cụt, đo ngang ra 0.5 thốn", chu_tri: "Trĩ, lỵ, tiêu chảy, khí hư, đau xương cụt" },
    { kinh: "Kinh Bàng Quang", ten: "Thừa Phù", vi_tri: "Chính giữa nếp gấp mông", chu_tri: "Đau thần kinh tọa, trĩ, tiểu khó, liệt chi dưới" },
    { kinh: "Kinh Bàng Quang", ten: "Ân Môn", vi_tri: "Dưới huyệt Thừa Phù 6 thốn, trên đường nối Thừa Phù - Ủy Trung", chu_tri: "Đau thắt lưng, đau thần kinh tọa, liệt chi dưới" },
    { kinh: "Kinh Bàng Quang", ten: "Phù Khích", vi_tri: "Trên huyệt Ủy Dương 1 thốn, sát bờ trong gân cơ nhị đầu đùi", chu_tri: "Đau khoeo chân, co rút đùi, táo bón" },
    { kinh: "Kinh Bàng Quang", ten: "Ủy Dương", vi_tri: "Mặt sau khoeo chân, bờ ngoài nếp gấp khoeo, sát gân cơ nhị đầu đùi", chu_tri: "Co rút đùi gối, trướng bụng, tiểu khó" },
    { kinh: "Kinh Bàng Quang", ten: "Ủy Trung", vi_tri: "Chính giữa lằn chỉ nếp gấp khoeo chân (Huyệt chủ vùng lưng)", chu_tri: "Đau lưng cấp, đau thần kinh tọa, liệt chân, sốt cao" },
    { kinh: "Kinh Bàng Quang", ten: "Phụ Phân", vi_tri: "Dưới gai đốt sống ngực 2 đo ngang ra 3 thốn", chu_tri: "Đau vai gáy, cứng cổ, tê cánh tay" },
    { kinh: "Kinh Bàng Quang", ten: "Phách Hộ", vi_tri: "Dưới gai đốt sống ngực 3 đo ngang ra 3 thốn", chu_tri: "Ho suyễn, đau lưng gáy, lao phổi" },
    { kinh: "Kinh Bàng Quang", ten: "Cao Hoang", vi_tri: "Dưới gai đốt sống ngực 4 đo ngang ra 3 thốn", chu_tri: "Suy nhược cơ thể, ho lao, ho suyễn, di tinh" },
    { kinh: "Kinh Bàng Quang", ten: "Thần Đường", vi_tri: "Dưới gai đốt sống ngực 5 đo ngang ra 3 thốn", chu_tri: "Ho, hen suyễn, tức ngực, đau vai gáy" },
    { kinh: "Kinh Bàng Quang", ten: "Y Hỷ", vi_tri: "Dưới gai đốt sống ngực 6 đo ngang ra 3 thốn", chu_tri: "Đau ngực sườn, ho suyễn, ợ chua" },
    { kinh: "Kinh Bàng Quang", ten: "Cách Quan", vi_tri: "Dưới gai đốt sống ngực 7 đo ngang ra 3 thốn", chu_tri: "Đau lưng, nấc cục, nuốt vướng, ợ hơi" },
    { kinh: "Kinh Bàng Quang", ten: "Hồn Môn", vi_tri: "Dưới gai đốt sống ngực 9 đo ngang ra 3 thốn", chu_tri: "Đau hông sườn, nôn mửa, tiêu chảy, đau lưng" },
    { kinh: "Kinh Bàng Quang", ten: "Dương Cương", vi_tri: "Dưới gai đốt sống ngực 10 đo ngang ra 3 thốn", chu_tri: "Vàng da, đau hông sườn, tiêu chảy, nôn mửa" },
    { kinh: "Kinh Bàng Quang", ten: "Ý Xá", vi_tri: "Dưới gai đốt sống ngực 11 đo ngang ra 3 thốn", chu_tri: "Trướng bụng, nôn mửa, tiêu chảy, nuốt vướng" },
    { kinh: "Kinh Bàng Quang", ten: "Vị Thương", vi_tri: "Dưới gai đốt sống ngực 12 đo ngang ra 3 thốn", chu_tri: "Đau dạ dày, trướng bụng, ăn không tiêu" },
    { kinh: "Kinh Bàng Quang", ten: "Hoang Môn", vi_tri: "Dưới gai đốt sống thắt lưng 1 đo ngang ra 3 thốn", chu_tri: "Đau bụng dưới, táo bón, đau thắt lưng, nổi mụn vú" },
    { kinh: "Kinh Bàng Quang", ten: "Chí Thất", vi_tri: "Dưới gai đốt sống thắt lưng 2 đo ngang ra 3 thốn", chu_tri: "Di tinh, liệt dương, tiểu dắt, đau thắt lưng, sưng sinh dục" },
    { kinh: "Kinh Bàng Quang", ten: "Bào Hoang", vi_tri: "Dưới gai đốt sống cùng 2 đo ngang ra 3 thốn", chu_tri: "Trướng bụng, bí tiểu, đau thần kinh tọa, đau lưng" },
    { kinh: "Kinh Bàng Quang", ten: "Trật Biên", vi_tri: "Dưới gai đốt sống cùng 4 đo ngang ra 3 thốn", chu_tri: "Đau thắt lưng, đau thần kinh tọa, trĩ, liệt chi dưới" },
    { kinh: "Kinh Bàng Quang", ten: "Hợp Dương", vi_tri: "Dưới huyệt Ủy Trung 2 thốn, giữa hai bắp cơ sinh đôi", chu_tri: "Đau lưng, đau thần kinh tọa, băng lậu, thoát vị" },
    { kinh: "Kinh Bàng Quang", ten: "Thừa Cân", vi_tri: "Giữa bắp chân, trên đường nối Hợp Dương - Thừa Sơn", chu_tri: "Chuột rút bắp chân, đau thắt lưng, trĩ, đau cẳng chân" },
    { kinh: "Kinh Bàng Quang", ten: "Thừa Sơn", vi_tri: "Chỗ lõm giữa bắp chân, nơi hai bắp cơ sinh đôi tách ra", chu_tri: "Chuột rút bắp chân, trĩ, táo bón, liệt chi dưới" },
    { kinh: "Kinh Bàng Quang", ten: "Phi Dương", vi_tri: "Từ huyệt Côn Lôn đo thẳng lên 7 thốn", chu_tri: "Đau đầu, nghẹt mũi, đau lưng, trị trĩ" },
    { kinh: "Kinh Bàng Quang", ten: "Phụ Dương", vi_tri: "Từ đỉnh mắt cá ngoài đo lên 3 thốn, sát bờ ngoài gân gót", chu_tri: "Đau thắt lưng, đau cổ chân, liệt chi dưới, đau gáy" },
    { kinh: "Kinh Bàng Quang", ten: "Côn Lôn", vi_tri: "Chỗ lõm giữa đỉnh mắt cá ngoài và gân gót chân", chu_tri: "Đau đầu, cứng cổ gáy, đau thắt lưng, khó đẻ" },
    { kinh: "Kinh Bàng Quang", ten: "Bộc Tham", vi_tri: "Chỗ lõm mặt ngoài xương gót, dưới Thần Mạch 0.5 thốn", chu_tri: "Đau gót chân, đau cổ chân, động kinh" },
    { kinh: "Kinh Bàng Quang", ten: "Thần Mạch", vi_tri: "Chỗ lõm ngay dưới đỉnh mắt cá ngoài 0.5 thốn", chu_tri: "Đau đầu, mất ngủ, chóng mặt, động kinh, đau cổ chân" },
    { kinh: "Kinh Bàng Quang", ten: "Kim Môn", vi_tri: "Phía dưới trước mắt cá ngoài, chỗ lõm xương hộp", chu_tri: "Đau đầu, động kinh, đau cổ chân, co giật trẻ em" },
    { kinh: "Kinh Bàng Quang", ten: "Kinh Cốt", vi_tri: "Chỗ lõm phía dưới ngoài mấu củ xương bàn chân thứ 5", chu_tri: "Đau đầu, cứng cổ gáy, đau thắt lưng, động kinh" },
    { kinh: "Kinh Bàng Quang", ten: "Thúc Cốt", vi_tri: "Chỗ lõm phía sau khớp ngón-bàn chân thứ 5, bờ ngoài", chu_tri: "Đau đầu, cứng gáy, đau lưng, đau mông đùi" },
    { kinh: "Kinh Bàng Quang", ten: "Thông Cốc", vi_tri: "Chỗ lõm phía trước khớp ngón-bàn chân thứ 5, bờ ngoài", chu_tri: "Đau đầu, cứng cổ gáy, chảy máu cam, chóng mặt" },
    { kinh: "Kinh Bàng Quang", ten: "Chí Âm", vi_tri: "Bờ ngoài ngón chân út cách gốc móng 0.1 thốn", chu_tri: "Ngôi thai ngược (cứu), đau đầu, nghẹt mũi" },
        // --- KINH THẬN (27 huyệt) ---
    { kinh: "Kinh Thận", ten: "Dũng Tuyền", vi_tri: "Chỗ lõm gan bàn chân, tại 1/3 trước đường nối ngón 2 và gót", chu_tri: "Mất ngủ, nhức đầu, ho khan, đỉnh đầu đau, hạ huyết áp" },
    { kinh: "Kinh Thận", ten: "Nhiên Cốc", vi_tri: "Chỗ lõm trước dưới củ xương thuyền bàn chân", chu_tri: "Kinh nguyệt không đều, di tinh, đau họng, tiểu buốt, đái dầm" },
    { kinh: "Kinh Thận", ten: "Thái Khê", vi_tri: "Chỗ lõm giữa đỉnh mắt cá trong và gân gót chân", chu_tri: "Đau lưng, ù tai, hen suyễn, mất ngủ, di tinh" },
    { kinh: "Kinh Thận", ten: "Đại Chung", vi_tri: "Dưới sau mắt cá trong, sát bờ trong gân gót", chu_tri: "Ho ra máu, suyễn, bí tiểu, đau gót chân" },
    { kinh: "Kinh Thận", ten: "Thủy Tuyền", vi_tri: "Dưới huyệt Thái Khê 1 thốn, chỗ lõm bờ ngoài xương gót", chu_tri: "Đau bụng kinh, bế kinh, sa tử cung, tiểu khó" },
    { kinh: "Kinh Thận", ten: "Chiếu Hải", vi_tri: "Chỗ lõm dưới đỉnh mắt cá trong 1 thốn", chu_tri: "Kinh nguyệt không đều, hầu họng khô đau, mất ngủ" },
    { kinh: "Kinh Thận", ten: "Phục Lưu", vi_tri: "Từ Thái Khê đo thẳng lên 2 thốn, sát bờ trước gân gót", chu_tri: "Phù thũng, tiêu chảy, ra mồ hôi trộm hoặc không ra mồ hôi" },
    { kinh: "Kinh Thận", ten: "Giao Tín", vi_tri: "Trên huyệt Thái Khê 2 thốn, trước Phục Lưu 0.5 thốn", chu_tri: "Băng lậu, sa tử cung, đau cẳng chân, tiêu chảy" },
    { kinh: "Kinh Thận", ten: "Trúc Tân", vi_tri: "Từ Thái Khê đo lên 5 thốn, chỗ lõm bờ dưới cơ bụng chân", chu_tri: "Điên cuồng, đau bắp chân, sưng đau hernia" },
    { kinh: "Kinh Thận", ten: "Âm Cốc", vi_tri: "Mặt trong khoeo chân, giữa 2 gân cơ bán gân và bán màng", chu_tri: "Liệt dương, băng lậu, đau bụng dưới, tiểu buốt" },
    { kinh: "Kinh Thận", ten: "Hoành Cốt", vi_tri: "Bờ trên xương mu, cách đường giữa bụng 0.5 thốn", chu_tri: "Bí tiểu, đau thoát vị, di tinh, liệt dương" },
    { kinh: "Kinh Thận", ten: "Đại Hách", vi_tri: "Dưới rốn 4 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Di tinh, liệt dương, khí hư, đau bụng dưới" },
    { kinh: "Kinh Thận", ten: "Khí Huyệt", vi_tri: "Dưới rốn 3 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Kinh nguyệt không đều, tiêu chảy, bí tiểu" },
    { kinh: "Kinh Thận", ten: "Tứ Mãn", vi_tri: "Dưới rốn 2 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Trướng bụng, đau bụng kinh, phù thũng, tiêu chảy" },
    { kinh: "Kinh Thận", ten: "Trung Chú", vi_tri: "Dưới rốn 1 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau bụng quanh rốn, táo bón, kinh nguyệt không đều" },
    { kinh: "Kinh Thận", ten: "Hoang Du", vi_tri: "Ngang rốn, cách rốn 0.5 thốn về phía trong", chu_tri: "Đau bụng quanh rốn, trướng bụng, táo bón, nôn mửa" },
    { kinh: "Kinh Thận", ten: "Thương Khúc", vi_tri: "Trên rốn 2 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, đau bụng, ăn không tiêu" },
    { kinh: "Kinh Thận", ten: "Thạch Quan", vi_tri: "Trên rốn 3 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, nôn mửa, táo bón, đau bụng" },
    { kinh: "Kinh Thận", ten: "Âm Đô", vi_tri: "Trên rốn 4 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, đầy trướng ngực sườn, ợ hơi" },
    { kinh: "Kinh Thận", ten: "Thông Cốc (Thận)", vi_tri: "Trên rốn 5 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, nôn mửa, ho suyễn, trướng bụng" },
    { kinh: "Kinh Thận", ten: "U Môn", vi_tri: "Trên rốn 6 thốn, cách đường giữa bụng 0.5 thốn", chu_tri: "Đau dạ dày, nôn mửa, ợ chua, đau hông sườn" },
    { kinh: "Kinh Thận", ten: "Bộ Lang", vi_tri: "Khoang liên sườn 5, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực sườn, nôn mửa" },
    { kinh: "Kinh Thận", ten: "Thần Phong", vi_tri: "Khoang liên sườn 4, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau tức ngực, viêm tuyến vú" },
    { kinh: "Kinh Thận", ten: "Linh Khư", vi_tri: "Khoang liên sườn 3, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực sườn, nôn mửa, mất vị giác" },
    { kinh: "Kinh Thận", ten: "Thần Tàng", vi_tri: "Khoang liên sườn 2, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực, nôn mửa" },
    { kinh: "Kinh Thận", ten: "Hoắc Trung", vi_tri: "Khoang liên sườn 1, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau tức ngực, nghẹn cổ" },
    { kinh: "Kinh Thận", ten: "Du Phủ", vi_tri: "Chỗ lõm bờ dưới xương đòn, cách đường giữa ngực 2 thốn", chu_tri: "Ho suyễn, đau ngực, hen phế quản, nuốt vướng" },

    // --- KINH TÂM BÀO (9 huyệt) ---
    { kinh: "Kinh Tâm Bào", ten: "Thiên Trì", vi_tri: "Khoang liên sườn 4, ngoài núm vú 1 thốn", chu_tri: "Đau ngực, ho, sưng hạch nách, đau hông sườn" },
    { kinh: "Kinh Tâm Bào", ten: "Thiên Tuyền", vi_tri: "Dưới nếp gấp nách trước 2 thốn, giữa hai đầu cơ nhị đầu cánh tay", chu_tri: "Đau ngực, ho, đau vai cẳng tay, hồi hộp" },
    { kinh: "Kinh Tâm Bào", ten: "Khúc Trạch", vi_tri: "Trên nếp gấp khuỷu tay, bờ trong gân cơ nhị đầu", chu_tri: "Đau tim, hồi hộp, nôn mửa, sốt cao, run tay" },
    { kinh: "Kinh Tâm Bào", ten: "Tích Môn", vi_tri: "Từ lằn chỉ cổ tay đo lên 5 thốn, giữa hai gân cơ", chu_tri: "Đau vùng tim, hồi hộp, ho ra máu, nôn ra máu" },
    { kinh: "Kinh Tâm Bào", ten: "Gian Sử", vi_tri: "Từ lằn chỉ cổ tay đo thẳng lên 3 thốn, giữa hai gân cơ", chu_tri: "Đau vùng tim, sốt rét, điên cuồng, nôn mửa" },
    { kinh: "Kinh Tâm Bào", ten: "Nội Quan", vi_tri: "Từ lằn chỉ cổ tay đo thẳng lên 2 thốn, giữa hai gân cơ", chu_tri: "Đau thắt ngực, mất ngủ, nôn mửa, say tàu xe, hồi hộp" },
    { kinh: "Kinh Tâm Bào", ten: "Đại Lăng", vi_tri: "Chính giữa lằn chỉ cổ tay, giữa hai gân cơ", chu_tri: "Đau vùng tim, loét miệng, đau đầu, đỏ mắt" },
    { kinh: "Kinh Tâm Bào", ten: "Lao Cung", vi_tri: "Trong lòng bàn tay, giữa xương đốt ngón 2-3 (chỗ đầu ngón giữa chạm vào khi nắm tay)", chu_tri: "Loét miệng, hôi miệng, tim hồi hộp, động kinh" },
    { kinh: "Kinh Tâm Bào", ten: "Trung Xung", vi_tri: "Chính giữa đầu ngón tay giữa cách móng 0.1 thốn", chu_tri: "Sốt cao, trúng phong hôn mê, đau tim, say nắng" },

    // --- KINH TAM TIÊU (23 huyệt) ---
    { kinh: "Kinh Tam Tiêu", ten: "Quan Xung", vi_tri: "Bờ ngoài ngón áp út, cách gốc móng 0.1 thốn", chu_tri: "Sốt cao, đau đầu, ù tai, đau họng" },
    { kinh: "Kinh Tam Tiêu", ten: "Dịch Môn", vi_tri: "Mu bàn tay, chỗ kẽ giữa ngón 4 và 5 đo lên 0.5 thốn", chu_tri: "Sốt, đau đầu, sưng họng, ù tai, đau cẳng tay" },
    { kinh: "Kinh Tam Tiêu", ten: "Trung Chử", vi_tri: "Mu bàn tay, chỗ lõm giữa xương đốt ngón tay 4 và 5", chu_tri: "Ù tai, điếc tai, đau đầu, đau mắt đỏ, co rút ngón tay" },
    { kinh: "Kinh Tam Tiêu", ten: "Dương Trì", vi_tri: "Chính giữa nếp gấp sau cổ tay, bờ ngoài gân cơ duỗi chung các ngón", chu_tri: "Đau cổ tay, đau họng, sốt rét, tiêu hóa kém" },
    { kinh: "Kinh Tam Tiêu", ten: "Ngoại Quan", vi_tri: "Từ lằn chỉ cổ tay mặt sau đo lên 2 thốn, đối diện Nội Quan", chu_tri: "Cảm mạo sốt, đau đầu, đau khớp vai gáy, ù tai" },
    { kinh: "Kinh Tam Tiêu", ten: "Chi Câu", vi_tri: "Từ lằn chỉ cổ tay mặt sau đo lên 3 thốn", chu_tri: "Táo bón, đau hông sườn, sốt không ra mồ hôi" },
    { kinh: "Kinh Tam Tiêu", ten: "Hội Tông", vi_tri: "Trên lằn cổ tay sau 3 thốn, phía ngoài Ngoại Quan 1 khoát ngón tay", chu_tri: "Ù tai, điếc tai, đau cánh tay, động kinh" },
    { kinh: "Kinh Tam Tiêu", ten: "Tam Dương Lạc", vi_tri: "Trên lằn cổ tay sau 4 thốn, giữa xương quay và trụ", chu_tri: "Điếc tai, mất tiếng đột ngột, đau cẳng tay" },
    { kinh: "Kinh Tam Tiêu", ten: "Tứ Độc", vi_tri: "Dưới mỏm khuỷu tay 5 thốn, giữa xương quay và trụ", chu_tri: "Điếc tai, sưng họng, đau cẳng tay, mất tiếng" },
    { kinh: "Kinh Tam Tiêu", ten: "Thanh Lãnh Uyên", vi_tri: "Trên mỏm khuỷu tay 2 thốn khi co khuỷu", chu_tri: "Đau khớp khuỷu, đau vai gáy, nhức đầu" },
    { kinh: "Kinh Tam Tiêu", ten: "Tiêu Lạc", vi_tri: "Mặt sau cánh tay, giữa Thanh Lãnh Uyên và Nhu Hội", chu_tri: "Đau gáy cổ, đau cánh tay, đau đầu" },
    { kinh: "Kinh Tam Tiêu", ten: "Nhu Hội", vi_tri: "Bờ sau cơ delta, dưới Kiên Liêu 3 thốn", chu_tri: "Đau vai cẳng tay, bướu cổ, cứng gáy" },
    { kinh: "Kinh Tam Tiêu", ten: "Kiên Liêu", vi_tri: "Chỗ lõm phía sau dưới mỏm cùng vai khi dang tay", chu_tri: "Đau khớp vai, liệt cánh tay, không giơ tay được" },
    { kinh: "Kinh Tam Tiêu", ten: "Thiên Liêu", vi_tri: "Chính giữa đoạn nối Kiên Tỉnh và góc trên xương bả vai", chu_tri: "Đau vai gáy, đau cổ gáy, bả vai co rút" },
    { kinh: "Kinh Tam Tiêu", ten: "Thiên Dũ", vi_tri: "Bờ sau cơ ức đòn chũm, dưới Phong Trì, ngang góc hàm", chu_tri: "Đau đầu, điếc tai, cổ cứng đau, mắt sưng" },
    { kinh: "Kinh Tam Tiêu", ten: "Ế Phong", vi_tri: "Chỗ lõm phía sau dái tai, sát bờ trước xương chũm (Tử huyệt)", chu_tri: "Ù tai, điếc tai, liệt mặt, đau răng, quai bị" },
    { kinh: "Kinh Tam Tiêu", ten: "Kế Mạch", vi_tri: "Sau tai, tại điểm nối 1/3 dưới đường Giác Tôn - Ế Phong", chu_tri: "Đau đầu, ù tai, co giật trẻ em, điếc tai" },
    { kinh: "Kinh Tam Tiêu", ten: "Lô Tức", vi_tri: "Sau vành tai, đường nối Giác Tôn - Ế Phong (1/3 trên)", chu_tri: "Đau đầu, ù tai, nôn mửa, sưng đau tai" },
    { kinh: "Kinh Tam Tiêu", ten: "Giác Tôn", vi_tri: "Chính giữa đường chân tóc trên vành tai khi gấp vành tai về trước", chu_tri: "Đau đầu, sưng tai, mờ mắt, đau răng" },
    { kinh: "Kinh Tam Tiêu", ten: "Nhĩ Môn", vi_tri: "Chỗ lõm phía trên khuyết trước vành tai, khi há miệng có chỗ lõm", chu_tri: "Ù tai, điếc tai, viêm tai giữa, đau răng" },
    { kinh: "Kinh Tam Tiêu", ten: "Hòa Liêu (Tam Tiêu)", vi_tri: "Chỗ lõm phía trước trên chân vành tai, sát động mạch thái dương nông", chu_tri: "Đau đầu, ù tai, cứng hàm, méo miệng" },
    { kinh: "Kinh Tam Tiêu", ten: "Ty Trúc Không", vi_tri: "Chỗ lõm sát đầu ngoài chân mày", chu_tri: "Đau đầu, đau mắt, giật cơ mi mắt, liệt mặt" },

    // --- KINH ĐỞM (44 huyệt) ---
    { kinh: "Kinh Đởm", ten: "Đồng Tử Liêu", vi_tri: "Cách khóe mắt ngoài 0.1 thốn", chu_tri: "Đau đầu, đau mắt, cận thị, liệt mặt" },
    { kinh: "Kinh Đởm", ten: "Thính Hội", vi_tri: "Phía trước bờ dưới rãnh bình tai, khi mở miệng có chỗ lõm", chu_tri: "Ù tai, điếc tai, viêm tai giữa, liệt mặt" },
    { kinh: "Kinh Đởm", ten: "Thượng Quan", vi_tri: "Chỗ lõm bờ trên cung tiếp gò má, thẳng trên Hạ Quan", chu_tri: "Đau đầu, ù tai, điếc tai, đau răng, méo miệng" },
    { kinh: "Kinh Đởm", ten: "Hàm Yến", vi_tri: "Trong mép tóc thái dương, 1/4 trên đường nối Đầu Duy - Khúc Tần", chu_tri: "Đau nửa đầu, chóng mặt, giật mi mắt, đau răng" },
    { kinh: "Kinh Đởm", ten: "Huyền Lô", vi_tri: "Trong mép tóc thái dương, điểm giữa đường nối Đầu Duy - Khúc Tần", chu_tri: "Đau nửa đầu, sưng mặt, đau răng" },
    { kinh: "Kinh Đởm", ten: "Huyền Ly", vi_tri: "Trong mép tóc thái dương, 3/4 dưới đường nối Đầu Duy - Khúc Tần", chu_tri: "Đau nửa đầu, đau mắt đỏ, đau răng" },
    { kinh: "Kinh Đởm", ten: "Khúc Tần", vi_tri: "Giao điểm đường chân tóc ngang trước tai và đường dọc đỉnh tai", chu_tri: "Đau nửa đầu, đau má, cứng hàm" },
    { kinh: "Kinh Đởm", ten: "Suất Cốc", vi_tri: "Thẳng từ đỉnh tai lên vào trong tóc 1.5 thốn", chu_tri: "Đau nửa đầu, chóng mặt, nôn mửa do say rượu" },
    { kinh: "Kinh Đởm", ten: "Thiên Xung", vi_tri: "Thẳng trên phía sau tai 2 thốn, sau Suất Cốc 0.5 thốn", chu_tri: "Đau đầu, động kinh, sưng chân răng" },
    { kinh: "Kinh Đởm", ten: "Phù Bạch", vi_tri: "Sau đỉnh tai, điểm nối 1/3 trên đường Thiên Xung - Hoàn Cốt", chu_tri: "Đau đầu, ù tai, điếc tai, sưng họng" },
    { kinh: "Kinh Đởm", ten: "Đầu Khiếu Âm", vi_tri: "Sau vành tai, điểm nối 2/3 dưới đường Thiên Xung - Hoàn Cốt", chu_tri: "Đau đầu, ù tai, đau cổ gáy, đắng miệng" },
    { kinh: "Kinh Đởm", ten: "Hoàn Cốt", vi_tri: "Chỗ lõm phía sau dưới mỏm chũm", chu_tri: "Đau đầu, đau răng, méo miệng, ù tai" },
    { kinh: "Kinh Đởm", ten: "Bản Thần", vi_tri: "Trên đường chân tóc trán 0.5 thốn, thẳng trên khóe mắt ngoài", chu_tri: "Đau đầu, động kinh, co giật trẻ em" },
    { kinh: "Kinh Đởm", ten: "Dương Bạch", vi_tri: "Thẳng trên đồng tử, trên lông mày 1 thốn", chu_tri: "Đau trán, sụp mi mắt, giật cơ mi, ngứa mắt" },
    { kinh: "Kinh Đởm", ten: "Đầu Lâm Khấp", vi_tri: "Thẳng trên đồng tử, vào trong chân tóc 0.5 thốn", chu_tri: "Đau đầu, nghẹt mũi, chảy nước mắt, mờ mắt" },
    { kinh: "Kinh Đởm", ten: "Mục Song", vi_tri: "Sau Đầu Lâm Khấp 1 thốn, trên đường thẳng dọc mắt", chu_tri: "Đau đầu, mờ mắt, đau mắt đỏ, chảy nước mắt" },
    { kinh: "Kinh Đởm", ten: "Chính Dinh", vi_tri: "Sau Mục Song 1 thốn, trên đường thẳng dọc mắt", chu_tri: "Đau đầu, chóng mặt, đau răng" },
    { kinh: "Kinh Đởm", ten: "Thừa Linh", vi_tri: "Sau Chính Dinh 1.5 thốn, trên đường thẳng dọc mắt", chu_tri: "Đau đầu, chảy máu cam, nghẹt mũi" },
    { kinh: "Kinh Đởm", ten: "Não Không", vi_tri: "Sau Thừa Linh 1.5 thốn, ngang bờ trên u chẩm ngoài", chu_tri: "Đau gáy cổ, đau đầu, ho hen, mờ mắt" },
    { kinh: "Kinh Đởm", ten: "Phong Trì", vi_tri: "Chỗ lõm dưới xương chẩm, bờ ngoài cơ thang (Huyệt đặc hiệu trừ phong)", chu_tri: "Đau đầu, chóng mặt, cảm mạo, đau vai gáy, tăng huyết áp" },
    { kinh: "Kinh Đởm", ten: "Kiên Tỉnh", vi_tri: "Điểm giữa đường nối đốt sống cổ 7 (Đại Chùy) và mỏm vai (Tử huyệt)", chu_tri: "Đau vai gáy, liệt tay, tắc sữa, viêm tuyến vú" },
    { kinh: "Kinh Đởm", ten: "Uyên Dịch", vi_tri: "Khoang liên sườn 4, trên đường nách giữa, dưới nách 3 thốn", chu_tri: "Đau ngực sườn, sưng hạch nách, đau cánh tay" },
    { kinh: "Kinh Đởm", ten: "Triếp Cân", vi_tri: "Khoang liên sườn 4, trước huyệt Uyên Dịch 1 thốn", chu_tri: "Ho suyễn, đau ngực sườn, ợ chua, nôn mửa" },
    { kinh: "Kinh Đởm", ten: "Nhật Nguyệt", vi_tri: "Khoang liên sườn 7, thẳng dưới núm vú (Huyệt mộ của Đởm)", chu_tri: "Đau hông sườn, nôn mửa, nấc cục, vàng da" },
    { kinh: "Kinh Đởm", ten: "Kinh Môn", vi_tri: "Bờ dưới đầu tự do xương sườn 12 (Huyệt mộ của Thận)", chu_tri: "Đau hông sườn, trướng bụng, tiêu chảy, đau thắt lưng" },
    { kinh: "Kinh Đởm", ten: "Đới Mạch", vi_tri: "Dưới đầu sườn 11, ngang hàng với rốn", chu_tri: "Kinh nguyệt không đều, khí hư, đau bụng lâm râm" },
    { kinh: "Kinh Đởm", ten: "Ngũ Khu", vi_tri: "Trước dưới gai chậu trước trên, ngang dưới rốn 3 thốn", chu_tri: "Đau bụng dưới, thoát vị, khí hư" },
    { kinh: "Kinh Đởm", ten: "Duy Đạo", vi_tri: "Phía trước dưới Ngũ Khu 0.5 thốn", chu_tri: "Đau bụng dưới, sa tử cung, táo bón" },
    { kinh: "Kinh Đởm", ten: "Cư Liêu", vi_tri: "Điểm giữa đường nối gai chậu trước trên và mấu chuyển lớn xương đùi", chu_tri: "Đau thắt lưng, đau háng, liệt chi dưới" },
    { kinh: "Kinh Đởm", ten: "Hoàn Khiêu", vi_tri: "Nơi tiếp giáp 1/3 ngoài và 2/3 trong đường nối ụ ngồi và mấu chuyển lớn xương đùi", chu_tri: "Đau thần kinh tọa, liệt chi dưới, đau khớp háng" },
    { kinh: "Kinh Đởm", ten: "Phong Thị", vi_tri: "Mặt ngoài đùi, trên nếp khoeo 7 thốn (Xuôi tay thẳng, đầu ngón giữa chạm vào đùi)", chu_tri: "Liệt chi dưới, ngứa toàn thân, đau đùi" },
    { kinh: "Kinh Đởm", ten: "Trung Độc", vi_tri: "Mặt ngoài đùi, dưới Phong Thị 2 thốn", chu_tri: "Liệt chi dưới, đau thần kinh tọa, đau đùi" },
    { kinh: "Kinh Đởm", ten: "Tất Dương Quan", vi_tri: "Chỗ lõm phía trên lồi cầu ngoài xương đùi, trên Độc Tỵ 3 thốn", chu_tri: "Đau khớp gối, co rút gân khoeo, tê cẳng chân" },
    { kinh: "Kinh Đởm", ten: "Dương Lăng Tuyền", vi_tri: "Chỗ lõm phía dưới trước đầu xương mác (Huyệt hội của cân)", chu_tri: "Co rút cơ, đau thần kinh tọa, đau hông sườn, viêm gan" },
    { kinh: "Kinh Đởm", ten: "Dương Giao", vi_tri: "Từ đỉnh mắt cá ngoài đo lên 7 thốn, bờ sau xương mác", chu_tri: "Đau ngực sườn, đầy trướng, cuồng điên, đau cẳng chân" },
    { kinh: "Kinh Đởm", ten: "Ngoại Khâu", vi_tri: "Từ đỉnh mắt cá ngoài đo lên 7 thốn, bờ trước xương mác", chu_tri: "Đau ngực sườn, đau cẳng chân, động kinh" },
    { kinh: "Kinh Đởm", ten: "Quang Minh", vi_tri: "Từ đỉnh mắt cá ngoài đo thẳng lên 5 thốn", chu_tri: "Đau mắt, giảm thị lực, đau cẳng chân" },
    { kinh: "Kinh Đởm", ten: "Dương Phụ", vi_tri: "Từ đỉnh mắt cá ngoài đo lên 4 thốn, bờ trước xương mác", chu_tri: "Đau nửa đầu, đau họng, đau ngực sườn, đau khớp cổ chân" },
    { kinh: "Kinh Đởm", ten: "Huyền Chung", vi_tri: "Từ đỉnh mắt cá ngoài đo thẳng lên 3 thốn (Huyệt hội của tủy)", chu_tri: "Liệt chi dưới, cứng cổ gáy, đau thần kinh tọa" },
    { kinh: "Kinh Đởm", ten: "Khâu Khư", vi_tri: "Chỗ lõm phía dưới trước mắt cá ngoài chân", chu_tri: "Đau cổ chân, đau hông sườn, mắt sưng đỏ" },
    { kinh: "Kinh Đởm", ten: "Túc Lâm Khấp", vi_tri: "Chỗ lõm phía sau khớp ngón-bàn chân thứ 4 và 5", chu_tri: "Đau đầu, đau hông sườn, kinh nguyệt không đều, tắc sữa" },
    { kinh: "Kinh Đởm", ten: "Địa Ngũ Hội", vi_tri: "Chỗ lõm giữa xương bàn chân 4 và 5, trước Túc Lâm Khấp 0.5 thốn", chu_tri: "Sưng đau mu bàn chân, viêm tuyến vú, đau mắt" },
    { kinh: "Kinh Đởm", ten: "Hiệp Khê", vi_tri: "Chỗ kẽ giữa ngón chân 4 và 5 đo lên 0.5 thốn", chu_tri: "Đau đầu, chóng mặt, ù tai, sưng họng, đau ngực sườn" },
    { kinh: "Kinh Đởm", ten: "Túc Khiếu Âm", vi_tri: "Bờ ngoài góc móng chân thứ 4 cách gốc móng 0.1 thốn", chu_tri: "Đau đầu, đau hông sườn, sưng họng, sốt" },

    // --- KINH CAN (14 huyệt) ---
    { kinh: "Kinh Can", ten: "Đại Đôn", vi_tri: "Bờ ngoài góc móng chân cái cách gốc móng 0.1 thốn", chu_tri: "Sa tử cung, thoát vị bẹn, băng lậu, tiểu dắt" },
    { kinh: "Kinh Can", ten: "Hành Gian", vi_tri: "Chỗ kẽ giữa ngón chân 1 và 2 đo lên 0.5 thốn", chu_tri: "Đau đầu, mắt đỏ sưng, kinh nguyệt nhiều, mất ngủ" },
    { kinh: "Kinh Can", ten: "Thái Xung", vi_tri: "Chỗ lõm từ kẽ ngón chân 1-2 đo lên 1.5 thốn (Huyệt nguyên của kinh Can)", chu_tri: "Tăng huyết áp, nhức đầu, cáu gắt, đau hông sườn, đột quỵ" },
    { kinh: "Kinh Can", ten: "Trung Phong", vi_tri: "Chỗ lõm phía trước mắt cá trong chân 1 thốn", chu_tri: "Đau sinh dục, đái dắt, di tinh, đau cổ chân" },
    { kinh: "Kinh Can", ten: "Lãi Câu", vi_tri: "Từ đỉnh mắt cá trong đo lên 5 thốn, sát bờ sau xương chày", chu_tri: "Ngứa bộ phận sinh dục, khí hư, tiểu khó" },
    { kinh: "Kinh Can", ten: "Trung Đô", vi_tri: "Từ đỉnh mắt cá trong đo lên 7 thốn, sát bờ sau xương chày", chu_tri: "Đau bụng dưới, tiêu chảy, băng lậu, đau cẳng chân" },
    { kinh: "Kinh Can", ten: "Tất Quan", vi_tri: "Dưới đầu trong xương chày (Âm Lăng Tuyền) sau 1 thốn", chu_tri: "Đau khớp gối, hạn chế vận động chân" },
    { kinh: "Kinh Can", ten: "Khúc Tuyền", vi_tri: "Đầu trong nếp gấp khoeo chân khi co gối", chu_tri: "Đau gối, đau sinh dục, di tinh, tiểu khó" },
    { kinh: "Kinh Can", ten: "Âm Bao", vi_tri: "Mặt trong đùi, trên lồi cầu trong xương đùi 4 thốn", chu_tri: "Đau bụng dưới, kinh nguyệt không đều, tiểu khó" },
    { kinh: "Kinh Can", ten: "Ngũ Lý (Can)", vi_tri: "Dưới nếp bẹn 3 thốn, sát bờ trong cơ lược", chu_tri: "Bí tiểu, đái dầm, sưng đau bẹn" },
    { kinh: "Kinh Can", ten: "Âm Liêm", vi_tri: "Dưới nếp bẹn 2 thốn, sát bờ trong cơ lược", chu_tri: "Kinh nguyệt không đều, khí hư, đau đùi bẹn" },
    { kinh: "Kinh Can", ten: "Cấp Mạch", vi_tri: "Bờ dưới xương mu, cách đường giữa bụng 2.5 thốn", chu_tri: "Đau bộ phận sinh dục, sa tử cung, thoát vị bẹn" },
    { kinh: "Kinh Can", ten: "Chương Môn", vi_tri: "Dưới đầu xương sườn tự do thứ 11 (Huyệt hội của tạng)", chu_tri: "Đau bụng, đầy chướng, tiêu chảy, đau hông sườn" },
    { kinh: "Kinh Can", ten: "Kỳ Môn", vi_tri: "Khoang liên sườn 6, thẳng hàng dưới núm vú (Huyệt mộ của Can)", chu_tri: "Đau tức ngực sườn, viêm gan, nôn mửa, nấc cục" },

    // --- MẠCH NHÂM (24 huyệt) ---
    { kinh: "Mạch Nhâm", ten: "Hội Âm", vi_tri: "Chính giữa vùng tầng sinh môn (giữa hậu môn và cơ quan sinh dục)", chu_tri: "Cấp cứu chết đuối, di tinh, đái dắt, ngứa âm hộ, trĩ" },
    { kinh: "Mạch Nhâm", ten: "Khúc Cốt", vi_tri: "Chính giữa bờ trên xương mu", chu_tri: "Di tinh, liệt dương, tiểu dắt, khí hư" },
    { kinh: "Mạch Nhâm", ten: "Trung Cực", vi_tri: "Dưới rốn thẳng xuống 4 thốn, trên bờ trên xương mu 1 thốn", chu_tri: "Đái dầm, bí tiểu, di tinh, liệt dương, đau bụng kinh" },
    { kinh: "Mạch Nhâm", ten: "Quan Nguyên", vi_tri: "Dưới rốn thẳng xuống 3 thốn (Vùng Đan điền - Huyệt trường thọ)", chu_tri: "Suy nhược cơ thể, liệt dương, di tinh, kinh nguyệt không đều, tiêu chảy mạn" },
    { kinh: "Mạch Nhâm", ten: "Thạch Môn", vi_tri: "Dưới rốn thẳng xuống 2 thốn", chu_tri: "Trướng bụng, tiêu chảy, bí tiểu, băng lậu" },
    { kinh: "Mạch Nhâm", ten: "Khí Hải", vi_tri: "Dưới rốn thẳng xuống 1.5 thốn (Bể của nguyên khí)", chu_tri: "Đau bụng, đái dắt, suy nhược, kinh nguyệt không đều" },
    { kinh: "Mạch Nhâm", ten: "Âm Giao", vi_tri: "Dưới rốn thẳng xuống 1 thốn", chu_tri: "Trướng bụng, đau bụng quanh rốn, khí hư, băng lậu" },
    { kinh: "Mạch Nhâm", ten: "Thần Khuyết", vi_tri: "Chính giữa rốn (Tử huyệt - Cấm châm, chỉ cứu)", chu_tri: "Đau bụng cấp, ỉa chảy mạn, choáng ngất, chân tay lạnh" },
    { kinh: "Mạch Nhâm", ten: "Thủy Phân", vi_tri: "Trên rốn thẳng lên 1 thốn", chu_tri: "Phù thũng, trướng bụng, tiêu chảy, nôn mửa" },
    { kinh: "Mạch Nhâm", ten: "Hạ Quản", vi_tri: "Trên rốn 2 thốn, trên đường giữa bụng", chu_tri: "Đau dạ dày, trướng bụng, tiêu chảy, nôn mửa" },
    { kinh: "Mạch Nhâm", ten: "Kiến Lý", vi_tri: "Trên rốn thẳng lên 3 thốn", chu_tri: "Đau dạ dày, nôn mửa, trướng bụng, chán ăn" },
    { kinh: "Mạch Nhâm", ten: "Trung Quản", vi_tri: "Từ rốn đo thẳng lên 4 thốn (Huyệt hội của phủ)", chu_tri: "Đau dạ dày, nôn mửa, đầy bụng, nấc cục, tiêu hóa kém" },
    { kinh: "Mạch Nhâm", ten: "Thượng Quản", vi_tri: "Trên rốn 5 thốn, trên đường giữa bụng", chu_tri: "Đau dạ dày, nôn mửa, ợ chua, nấc cục, động kinh" },
    { kinh: "Mạch Nhâm", ten: "Cự Khuyết", vi_tri: "Trên rốn thẳng lên 6 thốn (Huyệt mộ của Tâm)", chu_tri: "Đau tim, hồi hộp, ợ chua, nôn mửa, điên cuồng" },
    { kinh: "Mạch Nhâm", ten: "Cửu Vĩ", vi_tri: "Dưới mũi ức 0.5 thốn, trên rốn 7 thốn", chu_tri: "Đau vùng tim, ho suyễn, động kinh, cuồng điên" },
    { kinh: "Mạch Nhâm", ten: "Trung Đình", vi_tri: "Ngang khoang liên sườn 5, giao điểm sụn khớp xiphoid và cán ức", chu_tri: "Đau ngực, nôn mửa, nghẹn cổ, nuốt khó" },
    { kinh: "Mạch Nhâm", ten: "Đản Trung", vi_tri: "Điểm giữa đường nối hai núm vú ở nam giới (Huyệt hội của khí)", chu_tri: "Ho, hen suyễn, đau ngực, tắc sữa, tim đập nhanh" },
    { kinh: "Mạch Nhâm", ten: "Ngọc Đường", vi_tri: "Khoang liên sườn 3, trên đường giữa ngực", chu_tri: "Ho suyễn, đau ngực, sưng họng, nuốt khó" },
    { kinh: "Mạch Nhâm", ten: "Tử Cung (Nhâm)", vi_tri: "Khoang liên sườn 2, trên đường giữa ngực", chu_tri: "Ho suyễn, đau ngực, nuốt vướng, nghẹn cổ" },
    { kinh: "Mạch Nhâm", ten: "Hoa Cái", vi_tri: "Khoang liên sườn 1, trên đường giữa ngực", chu_tri: "Ho suyễn, đau ngực, sưng họng" },
    { kinh: "Mạch Nhâm", ten: "Toàn Cơ", vi_tri: "Giữa xương cán ức, dưới Thiên Đột 1 thốn", chu_tri: "Ho suyễn, đau ngực, nuốt vướng" },
    { kinh: "Mạch Nhâm", ten: "Thiên Đột", vi_tri: "Chính giữa chỗ lõm bờ trên xương ức", chu_tri: "Ho suyễn, đau họng, mất tiếng, nuốt vướng nghẹn" },
    { kinh: "Mạch Nhâm", ten: "Liêm Tuyền", vi_tri: "Chính giữa bờ trên sụn giáp, chỗ lõm trên xương móng", chu_tri: "Mất tiếng, sưng đau họng, lưỡi dầy cứng, nuốt khó" },
    { kinh: "Mạch Nhâm", ten: "Thừa Tương", vi_tri: "Chính giữa chỗ lõm dưới môi dưới (rãnh môi cằm)", chu_tri: "Liệt mặt, đau răng hàm dưới, chảy dãi, sưng lợi" },

    // --- MẠCH ĐỐC (28 huyệt) ---
    { kinh: "Mạch Đốc", ten: "Trường Cường", vi_tri: "Đầu chóp xương cụt thẳng xuống 0.5 thốn", chu_tri: "Trĩ, lòi dom, táo bón, đau lưng" },
    { kinh: "Mạch Đốc", ten: "Yêu Du", vi_tri: "Chính giữa chỗ lõm mỏm gai xương cùng 4", chu_tri: "Đau thắt lưng xương cùng, trĩ, đái dắt, kinh nguyệt không đều" },
    { kinh: "Mạch Đốc", ten: "Yêu Dương Quan", vi_tri: "Dưới gai đốt sống thắt lưng 4, ngang đường nối 2 mào chậu", chu_tri: "Đau thắt lưng, di tinh, liệt dương, đau thần kinh tọa" },
    { kinh: "Mạch Đốc", ten: "Mệnh Môn", vi_tri: "Dưới gai đốt sống thắt lưng 2, đối diện rốn qua cột sống", chu_tri: "Đau thắt lưng, liệt dương, di tinh, chân tay lạnh, tiểu đêm" },
    { kinh: "Mạch Đốc", ten: "Huyền Khu", vi_tri: "Dưới gai đốt sống thắt lưng 1", chu_tri: "Đau thắt lưng, tiêu chảy, trướng bụng" },
    { kinh: "Mạch Đốc", ten: "Tích Trung", vi_tri: "Dưới gai đốt sống ngực 11", chu_tri: "Đau cột sống thắt lưng, trướng bụng, hoàng đản" },
    { kinh: "Mạch Đốc", ten: "Trung Khu", vi_tri: "Dưới gai đốt sống ngực 10", chu_tri: "Đau lưng, đau dạ dày, chán ăn" },
    { kinh: "Mạch Đốc", ten: "Cân Súc", vi_tri: "Dưới gai đốt sống ngực 9, trên đường giữa lưng", chu_tri: "Đau lưng, đau dạ dày, co giật, nôn mửa" },
    { kinh: "Mạch Đốc", ten: "Chí Dương", vi_tri: "Dưới gai đốt sống ngực 7, ngang góc dưới xương bả vai", chu_tri: "Đau ngực sườn, ho suyễn, hoàng đản, đau cột sống" },
    { kinh: "Mạch Đốc", ten: "Linh Đài", vi_tri: "Dưới gai đốt sống ngực 6", chu_tri: "Ho suyễn, đau cột sống lưng, mụn nhọt độc" },
    { kinh: "Mạch Đốc", ten: "Thần Đạo", vi_tri: "Dưới gai đốt sống ngực 5", chu_tri: "Đau tim, hồi hộp, mất ngủ, ho suyễn, động kinh" },
    { kinh: "Mạch Đốc", ten: "Thân Trụ", vi_tri: "Dưới gai đốt sống ngực 3", chu_tri: "Ho suyễn, động kinh trẻ em, sốt cao co giật, đau lưng" },
    { kinh: "Mạch Đốc", ten: "Đào Đạo", vi_tri: "Dưới gai đốt sống ngực 1", chu_tri: "Cảm mạo, sốt cao, ho suyễn, cứng cột sống gáy" },
    { kinh: "Mạch Đốc", ten: "Đại Chùy", vi_tri: "Chỗ lõm dưới gai đốt sống cổ 7 và trên đốt sống ngực 1", chu_tri: "Sốt cao, sốt rét, cảm cúm, ho suyễn, cứng cổ gáy" },
    { kinh: "Mạch Đốc", ten: "Á Môn", vi_tri: "Chính giữa gáy, dưới u chẩm đo xuống 0.5 thốn (Tử huyệt)", chu_tri: "Mất tiếng, nói ngọng, cứng lưỡi, liệt nửa người" },
    { kinh: "Mạch Đốc", ten: "Phong Phủ", vi_tri: "Từ Á Môn đo thẳng lên 0.5 thốn, ngay chỗ lõm dưới u chẩm (Tử huyệt)", chu_tri: "Đau đầu, cứng cổ gáy, trúng phong, liệt nửa người" },
    { kinh: "Mạch Đốc", ten: "Não Hộ", vi_tri: "Thẳng trên Phong Phủ 1.5 thốn, ngay bờ trên u chẩm ngoài", chu_tri: "Đau đầu, cứng gáy, chóng mặt, động kinh" },
    { kinh: "Mạch Đốc", ten: "Cường Gian", vi_tri: "Thẳng trên Não Hộ 1.5 thốn", chu_tri: "Đau đầu, cứng gáy, điên cuồng, động kinh" },
    { kinh: "Mạch Đốc", ten: "Hậu Đỉnh", vi_tri: "Thẳng trên Cường Gian 1.5 thốn, sau Bách Hội 1.5 thốn", chu_tri: "Đau đầu, chóng mặt, cuồng điên, động kinh" },
    { kinh: "Mạch Đốc", ten: "Bách Hội", vi_tri: "Giao điểm của đường dọc chính giữa đầu và đường nối hai đỉnh tai (Huyệt hội thiên dương)", chu_tri: "Sa tử cung, sa trực tràng, trúng phong, nhức đầu, mất ngủ, chóng mặt" },
    { kinh: "Mạch Đốc", ten: "Tiền Đỉnh", vi_tri: "Trước Bách Hội 1.5 thốn, trên đường giữa đầu", chu_tri: "Đau đầu, chóng mặt, sưng đỉnh đầu, co giật trẻ em" },
    { kinh: "Mạch Đốc", ten: "Tín Hội", vi_tri: "Trước Bách Hội 3 thốn, nơi thóp trước trẻ em", chu_tri: "Đau đầu, chóng mặt, nghẹt mũi, động kinh" },
    { kinh: "Mạch Đốc", ten: "Thượng Tinh", vi_tri: "Trên chân tóc trán 1 thốn, chính giữa đường dọc đầu", chu_tri: "Đau trán, chảy máu cam, nghẹt mũi, đau mắt" },
    { kinh: "Mạch Đốc", ten: "Thần Đình", vi_tri: "Trên chân tóc trán 0.5 thốn, chính giữa đường dọc đầu", chu_tri: "Đau đầu, chóng mặt, chảy nước mũi, mất ngủ" },
    { kinh: "Mạch Đốc", ten: "Tố Liêu", vi_tri: "Chính giữa đầu chóp mũi", chu_tri: "Nghẹt mũi, chảy máu cam, cấp cứu ngất, hạ huyết áp" },
    { kinh: "Mạch Đốc", ten: "Nhân Trung", vi_tri: "Tại điểm nối 1/3 trên và 2/3 dưới của rãnh nhân trung (Huyệt cấp cứu)", chu_tri: "Ngất, hôn mê, co giật, động kinh, méo miệng" },
    { kinh: "Mạch Đốc", ten: "Đoài Đoan", vi_tri: "Chính giữa bờ môi trên", chu_tri: "Đau răng môi, chảy máu cam, điên cuồng" },
    { kinh: "Mạch Đốc", ten: "Ngân Giao", vi_tri: "Chính giữa nếp hãm môi trên, trong nướu răng", chu_tri: "Sưng đau nướu răng, đau mũi, ngứa mắt" },

    // --- KỲ HUYỆT (Huyệt Ngoài Kinh - 33 huyệt) ---
    { kinh: "Kỳ Huyệt", ten: "Tứ Thần Thông", vi_tri: "Bốn huyệt xung quanh Bách Hội, cách Bách Hội 1 thốn (Tiền, Hậu, Tả, Hữu)", chu_tri: "Đau đầu, chóng mặt, mất ngủ, giảm trí nhớ, động kinh" },
    { kinh: "Kỳ Huyệt", ten: "Ấn Đường", vi_tri: "Điểm chính giữa đường nối hai đầu trong lông mày", chu_tri: "Đau đầu vùng trán, nghẹt mũi, chảy máu cam, mất ngủ, giải căng thẳng" },
    { kinh: "Kỳ Huyệt", ten: "Thái Dương", vi_tri: "Chỗ lõm sau điểm giữa đường nối đuôi lông mày và khóe mắt ngoài 1 thốn", chu_tri: "Đau nửa đầu, đau mắt đỏ, cảm mạo, liệt mặt" },
    { kinh: "Kỳ Huyệt", ten: "Ngư Yêu", vi_tri: "Chính giữa lông mày, thẳng trên đồng tử mắt", chu_tri: "Giật mi mắt, sụp mi, đau mắt đỏ, đau trán" },
    { kinh: "Kỳ Huyệt", ten: "Cầu Hậu", vi_tri: "Bờ dưới hốc mắt, nối 1/4 ngoài và 3/4 trong", chu_tri: "Cận thị, teo thần kinh thị giác, viễn thị, đục thủy tinh thể" },
    { kinh: "Kỳ Huyệt", ten: "Tỵ Thông", vi_tri: "Chỗ lõm đầu trên rãnh mũi má (phía trên Nghinh Hương)", chu_tri: "Viêm mũi dị ứng, nghẹt mũi, polip mũi" },
    { kinh: "Kỳ Huyệt", ten: "Kim Tân", vi_tri: "Dưới lưỡi, bên trái tĩnh mạch hãm lưỡi", chu_tri: "Loét miệng, lưỡi sưng cứng, nôn mửa, tiêu khát" },
    { kinh: "Kỳ Huyệt", ten: "Ngọc Dịch", vi_tri: "Dưới lưỡi, bên phải tĩnh mạch hãm lưỡi", chu_tri: "Loét miệng, mất tiếng, tiêu khát, nôn mửa" },
    { kinh: "Kỳ Huyệt", ten: "An Miên", vi_tri: "Giữa huyệt Ế Phong và Phong Trì", chu_tri: "Mất ngủ, chóng mặt, đau đầu, tâm thần cuồng" },
    { kinh: "Kỳ Huyệt", ten: "Bách Lao", vi_tri: "Từ Đại Chùy đo lên 2 thốn, đo ngang ra 1 thốn", chu_tri: "Ho lao, vẹo cổ, mồ hôi trộm, đau cổ gáy" },
    { kinh: "Kỳ Huyệt", ten: "Định Suyễn", vi_tri: "Dưới gai đốt sống cổ 7 (Đại Chùy) đo ngang ra 0.5 thốn", chu_tri: "Hen suyễn, ho, đau vai gáy, gập cứng cổ" },
    { kinh: "Kỳ Huyệt", ten: "Hoa Đà Giáp Tích", vi_tri: "28 cặp huyệt hai bên cột sống từ C1-S4, cách đường giữa 0.5 thốn", chu_tri: "Điều trị bệnh lý tạng phủ tương ứng, đau cột sống" },
    { kinh: "Kỳ Huyệt", ten: "Vị Quản Hạ Du", vi_tri: "Dưới gai đốt sống ngực 8 đo ngang ra 1.5 thốn (Huyệt Tụy Du)", chu_tri: "Đái tháo đường (tiêu khát), đau dạ dày, đau ngực sườn" },
    { kinh: "Kỳ Huyệt", ten: "Yêu Nhãn", vi_tri: "Dưới gai đốt sống thắt lưng 4 đo ngang ra 3.5 thốn, chỗ lõm thắt lưng", chu_tri: "Đau thắt lưng mạn tính, tiểu nhiều, lao thắt lưng" },
    { kinh: "Kỳ Huyệt", ten: "Thập Tuyên", vi_tri: "Chính giữa đầu 10 ngón tay, cách móng 0.1 thốn", chu_tri: "Cấp cứu sốt cao co giật, trúng phong hôn mê, tê đầu ngón tay" },
    { kinh: "Kỳ Huyệt", ten: "Bát Tà", vi_tri: "Kẽ 5 ngón tay mặt mu tay, nơi tiếp giáp da mu-lòng bàn tay (8 huyệt)", chu_tri: "Tê đau ngón tay, sưng bàn tay, liệt ngón tay" },
    { kinh: "Kỳ Huyệt", ten: "Tứ Phùng", vi_tri: "Mặt lòng các ngón tay 2, 3, 4, 5 tại nếp gấp khớp ngón 1-2", chu_tri: "Cam tích trẻ em, suy dinh dưỡng, ho suyễn" },
    { kinh: "Kỳ Huyệt", ten: "Bát Phong", vi_tri: "Kẽ các ngón chân mặt mu chân (8 huyệt)", chu_tri: "Tê đau ngón chân, sưng mu bàn chân, gút" },
    { kinh: "Kỳ Huyệt", ten: "Khí Hải Đan", vi_tri: "Dưới rốn 1.5 thốn, ngang Khí Hải đo ra 3 thốn", chu_tri: "Đau bụng dưới, thoát vị, ruột thừa viêm mạn" },
    { kinh: "Kỳ Huyệt", ten: "Tử Cung (Kỳ Huyệt)", vi_tri: "Dưới rốn 4 thốn, đo ngang ra 3 thốn", chu_tri: "Sa tử cung, bế kinh, vô sinh nữ, đau bụng kinh" },
    { kinh: "Kỳ Huyệt", ten: "Lạc Chẩm", vi_tri: "Mu bàn tay, giữa kẽ xương bàn ngón 2 và 3, đo lên 0.5 thốn", chu_tri: "Vẹo cổ cấp, đau vai gáy, đau tay" },
    { kinh: "Kỳ Huyệt", ten: "Trung Khôi", vi_tri: "Chính giữa nếp gấp khớp ngón gần của ngón tay giữa", chu_tri: "Nấc cục, nôn mửa, chán ăn, ợ chua" },
    { kinh: "Kỳ Huyệt", ten: "Đương Dương", vi_tri: "Thẳng trên đồng tử, vào trong chân tóc trán 1 thốn", chu_tri: "Đau đầu, cảm mạo, chóng mặt, đau mắt" },
    { kinh: "Kỳ Huyệt", ten: "Cảnh Tý", vi_tri: "Bờ sau cơ ức đòn chũm, trên xương đòn 1 thốn", chu_tri: "Tê đau chi trên, liệt chi trên, đau vai gáy" },
    { kinh: "Kỳ Huyệt", ten: "Bĩ Căn", vi_tri: "Dưới gai đốt sống thắt lưng 1 đo ngang ra 3.5 thốn", chu_tri: "Đau thắt lưng, khối bĩ, tiêu hóa kém" },
    { kinh: "Kỳ Huyệt", ten: "Nội Cung", vi_tri: "Mặt trong đùi, trên bờ trên xương bánh chè 4 thốn", chu_tri: "Liệt chi dưới, đau khớp gối, phong thấp" },
    { kinh: "Kỳ Huyệt", ten: "Khí Môn", vi_tri: "Dưới rốn 3 thốn (Quan Nguyên), đo ngang ra 3 thốn", chu_tri: "Đau bụng kinh, bế kinh, sa tử cung, băng lậu" },
    { kinh: "Kỳ Huyệt", ten: "Nhĩ Trung", vi_tri: "Chính giữa cơ hoành vành tai (ngay trên lỗ tai)", chu_tri: "Nấc cục, dạ dày co thắt, ngứa da, vàng da" },
    { kinh: "Kỳ Huyệt", ten: "Thừa Mệnh", vi_tri: "Phía sau dái tai 0.5 thốn", chu_tri: "Liệt mặt, ù tai, đau răng" },
    { kinh: "Kỳ Huyệt", ten: "Nội Hoài Tiêm", vi_tri: "Chỗ lõm bờ dưới mắt cá trong chân", chu_tri: "Đau cổ chân, sưng bàn chân" },
    { kinh: "Kỳ Huyệt", ten: "Ngoại Hoài Tiêm", vi_tri: "Chỗ lõm bờ dưới mắt cá ngoài chân", chu_tri: "Đau cổ chân, vẹo cổ chân" },
    { kinh: "Kỳ Huyệt", ten: "Tam Thương", vi_tri: "Ba huyệt ở bờ ngoài gốc móng ngón tay cái", chu_tri: "Sưng đau họng, sốt cao, chảy máu cam" },
    { kinh: "Kỳ Huyệt", ten: "Cân Cốt Phụ", vi_tri: "Điểm giữa nếp gấp khoeo chân kéo sang hai bên 1 thốn", chu_tri: "Co rút khoeo chân, đau khớp gối" },
];
